### ISSUE TITLE
Question about potentially unsafe code

### ISSUE THREAD

**Issue by tzieleniewski** [LibrePDF/OpenPDF#100]
Hi Team,

Could You please share some thoughts about possible "code fragments that infringe other people's copyrights".
IText team states that such fragments were present until they removed them in version 5.1.
https://developers.itextpdf.com/question/versions-older-than-5
Do you have any knowledge about such code in version 4.2.0 from which OpenPDF was forked.

**Comment by Lonzak** [comment]
I agree - every such code should be removed. Unfortunatly I didn't have the time to do so yet.
Some hint is given here:
https://opensource.stackexchange.com/questions/435/what-happens-if-stolen-software-is-published-as-open-source/437

I would look at the svn history and see what was removed and also remove it in openPDF

**Comment by andreasrosdal** [comment]
> I would look at the svn history and see what was removed and also remove it in openPDF

I have done this. The review of this has been done here:
https://github.com/LibrePDF/OpenPDF/wiki/OpenPDF---License-MPL---LGPL-background-info
https://github.com/LibrePDF/OpenPDF/issues/89
https://github.com/LibrePDF/OpenPDF/pull/90

So an effort in good faith has been done to review and clean this up. Please let me know if further changes are required.
