### ISSUE TITLE
how to download packages

### ISSUE THREAD

**Issue by samuelhutauruk2** [LibrePDF/OpenPDF#1001]
Cannot resolve packages from github.

![image](https://github.com/LibrePDF/OpenPDF/assets/28714809/5b827449-984f-4835-9bd4-4dceba995b7d)
![image](https://github.com/LibrePDF/OpenPDF/assets/28714809/2b45b450-2b8e-4f6f-8a0c-b39c89b660b8)

**Comment by andreasrosdal** [comment]
Please try this:

```
<dependency>
  <groupId>com.github.librepdf</groupId>
  <artifactId>openpdf-fonts-extra</artifactId>
  <version>1.3.33</version>
</dependency>

```

**Comment by samuelhutauruk2** [comment]
![Uploading image.png…]()

can't resolve

**Comment by samuelhutauruk2** [comment]
![image](https://github.com/LibrePDF/OpenPDF/assets/28714809/46a3261e-0841-4ef7-8648-654643c5044a)

**Comment by andreasrosdal** [comment]
Importing OpenPDF works correctly on my machine (TM).

Try "Reload All Maven Projects" as in this screenshot.

![image](https://github.com/LibrePDF/OpenPDF/assets/41650711/b6bd31f6-28a8-42bd-9259-80a46789ade4)


Do you have a file in .m2/settings.xml with some special Maven settings?

**Comment by andreasrosdal** [comment]
https://repo.maven.apache.org/maven2/com/github/librepdf/openpdf/1.3.33/
