### ISSUE TITLE
Remove reflection use from MappedRandomAccessFile.java and other files

### ISSUE THREAD

**Issue by chiralsoftware** [LibrePDF/OpenPDF#1008]
I am trying to use this in a GraalVM native-image build. It's failing because there is reflection used in MappedRandomAccessFile.java. This is to support obsolete JVM versions which should be dropped:

```
Warning: Reflection method java.lang.Class.getMethod invoked at com.lowagie.text.pdf.MappedRandomAccessFile.lambda$cleanOldsJDK$1(MappedRandomAccessFile.java:242)
Warning: Reflection method java.lang.Class.getMethod invoked at com.lowagie.text.pdf.MappedRandomAccessFile.lambda$cleanOldsJDK$1(MappedRandomAccessFile.java:247)
Warning: Reflection method java.lang.Class.getDeclaredConstructor invoked at com.lowagie.text.Image.getInstance(Image.java:917)
Warning: Reflection method java.lang.Class.getDeclaredFields invoked at com.lowagie.text.pdf.PdfName.<clinit>(PdfName.java:2146)
```

I suggest to remove the code in MappedRandomAccessFile.java that handles end of life JVM versions.

Another alternative would be to use GraalVM native image hints, but it's simpler just to delete the unused code.

**Comment by andreasrosdal** [comment]
Pull requests welcome, thank you!

**Comment by andreasrosdal** [comment]
Added a fix for this here:  https://github.com/LibrePDF/OpenPDF/commit/5a81749f0b7cee186ac13f44afea9929cd65f160

Can you please verify that this solves the problem?

@chiralsoftware

**Comment by xexes** [comment]
As far as I know, the minimum version of the supported Java version is still 8, so in my opinion these methods should remain, or alternatively use a specialized class for java 9+

**Comment by chiralsoftware** [comment]
> Added a fix for this here: [5a81749](https://github.com/LibrePDF/OpenPDF/commit/5a81749f0b7cee186ac13f44afea9929cd65f160)

Thank you! I tested that out and it's good. There still is reflection in the Image abstract class. I'll work on a pull request to fix that.

> As far as I know, the minimum version of the supported Java version is still 8, so in my opinion these methods should remain, or alternatively use a specialized class for java 9+

Is there any sane reason to support Java 8? There have been 3 _other_ LTS releases of Java since Java 8. Java 8 is about to celebrate its 10th birthday. Good support for GraalVM native images is a lot more exciting than good support for something which no one should be using anymore.  Anyone who really wants to stick with a long-obsolete JVM can just run older versions of OpenPDF or iText PDF.

**Comment by xexes** [comment]
.Java 8 is  nearly 33% of applications using it in production  
https://newrelic.com/sites/default/files/2023-04/new-relic-2023-state-of-the-java-ecosystem-2023-04-20.pdf
can't we just use Multi-Release JAR Files for compatibility?

**Comment by xexes** [comment]
I don't know if GraalVM supports it

**Comment by andreasrosdal** [comment]
OpenPDF now requires Java 9 or later.

**Comment by andreasrosdal** [comment]
Can you please submit a PR to remove the usage of reflection? This can be part of modernizing OpenPDF.
