### ISSUE TITLE
Illegal reflective access operation warning in Java 10

### ISSUE THREAD

**Issue by jjkarppi** [LibrePDF/OpenPDF#101]
Building a project using OpenPDF 1.2.2 with JDK 10.0.2 gives the following warning:

-----
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.lowagie.text.pdf.MappedRandomAccessFile$1 (file:/[local path removed from here]/openpdf.jar) to method java.nio.DirectByteBuffer.cleaner()
WARNING: Please consider reporting this to the maintainers of com.lowagie.text.pdf.MappedRandomAccessFile$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
-----

This should be fixed before a Java version that prevents this kind of access completely is released.

**Comment by andreasrosdal** [comment]
Thanks. Pull requests welcome.

**Comment by andreasrosdal** [comment]
@Lonzak what do you think of this?

Could MappedRandomAccessFile be replaced or removed? Can we use a library instead? Do you want to fix this?
