### ISSUE TITLE
Borders are disappeared  parsing html to a pdf using HTMLWorker

### ISSUE THREAD

**Issue by ztcarrot** [LibrePDF/OpenPDF#1016]
**Describe the bug**
when i use htmlWorker to parse a html, and convert it to a pdf, the table/div borders are disappeared, 

**To Reproduce**
```

    public static void main(String[] args) throws IOException {

        String htmlString = """
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
 <head>
     <meta charset="UTF-8"/>
 </head>
 <body>
<table width="100%" style="border-style:solid;border-color:black;border-width:1pt;">
<tr>
    <td width="100%" style="padding:3pt;padding-top:1pt;">
        <table width="100%" cellspacing="0">
            <tr>
                <td colspan="2" align="left" style="font-style:italic;font-size:11.5pt;padding-top:0pt;padding-right:5pt"><br/>test board</td>
            </tr>
            <tr>
                <td colspan="3" height="18" style="background-color:#0064d2;">test background color</td>
            </tr>
            <tr>
                <td colspan="3" align="center" style="padding-top:15pt;padding-bottom:10pt;font-family: arial, sans-serif;font-size:9pt;font-weight:bold;"></td>
            </tr>
        </table>
    </td>
</tr>
</table>
<br/><br/>
<div style="page-break-before:always;font-family: arial, sans-serif;font-size: 7pt;font-weight: normal;padding-top:30pt;padding-left:20pt"></div>
 </body>
</html>
""";
        Document document = new Document(PageSize.A4, 20, 20, 5, 15);

        // create a writer that listens to the document and directs a PDF-stream to a file
        PdfWriter.getInstance(document, new FileOutputStream("/Users/tzhang4/exampleold.pdf"));
        document.open();
        HTMLWorker htmlWorker = new HTMLWorker(document);
        htmlWorker.parse(new StringReader(htmlString));

        document.close();
    }

```

**Expected behavior**
borders and background color are shown

 - OS: MacOS Monterey
 - version: oponpdf : v1.3.5
 - jdk 17

**Comment by ztcarrot** [comment]
![image](https://github.com/LibrePDF/OpenPDF/assets/15632850/47d489f6-9890-472a-8cb5-95be6b1e53a8)

**Comment by andreasrosdal** [comment]
Are you using OpenPDF version 1.3.5?

Can you try with the latest version 1.3.35?

Can you try with an earlier version of OpenPDF?

Do you get the same problem in itext 2.1.7?

Thank you for reporting.

**Comment by andreasrosdal** [comment]
Possibly OpenPDF doesn't support this CSS style. 

Try:
<table border="1">

**Comment by ztcarrot** [comment]
Hi  @andreasrosdal 
i am using v1.3.35, 
<table border="1"> works to me!  

  but i have other questions, how to set border only for bottom, and how to set border colors,  and the background color.  . is there a document saying which CSS is supported ? thanks in advance.

**Comment by andreasrosdal** [comment]
You can study https://github.com/LibrePDF/OpenPDF/blob/master/openpdf/src/main/java/com/lowagie/text/html/simpleparser/HTMLWorker.java

It lists the HTML tags which are supported. 

You can also try https://github.com/flyingsaucerproject/flyingsaucer/ which has more advanced HTML support.
