### ISSUE TITLE
Document.add(PdfPTable) is very slow in versions 1.3.32 and higher

### ISSUE THREAD

**Issue by zinntech** [LibrePDF/OpenPDF#1017]
**Describe the bug**
Document.add(PdfPTable) is very slow in versions 1.3.32 and higher
When creating a table with 10,000 rows versions 1.3.32 takes 90,000 ms
In previous versions, this would take less than 200 ms.

**To Reproduce**
Attached is a simple program to reproduce the issue.
[slowPdfTableDemo.zip](https://github.com/LibrePDF/OpenPDF/files/13854146/slowPdfTableDemo.zip)

To run it:
mvn clean package
cd target 
java -jar slowPdfTableDemo-1.0-SNAPSHOT.jar

**Expected behavior**
In previous versions, this code would run in about 280ms.

**Screenshots**
None

**System (please complete the following information):**
 - OS:  Windows 11
 - Used Font: Default

**Additional context**

**Comment by andreasrosdal** [comment]
These are the changes is 1.3.32: https://github.com/LibrePDF/OpenPDF/releases/tag/1.3.32 @Lonzak 

This change looks related:
https://github.com/LibrePDF/OpenPDF/pull/865 by @fellmann
The algorithm has 4 nested for-loops, which is likely to be slow with large data sets. 

@zinntech Are you able to manually revert this change in OpenPDF, and see if this solves the performance problem?

So possible solutions are:
* Consider to revert #865 
* Find faster algorithm for height calculation for table rows with rowspan

**Comment by fellmann** [comment]
Hi, unfortunately I can confirm this change causes the performance drop. This is because the redistribution of row height is not calculated once per row, but at least x^2. I will try find to a simple fix.

**Comment by andreasrosdal** [comment]
Please try to find a simple fix, @fellmann.  There is also the possibility to revert it as in #1018. Thank you.

**Comment by andreasrosdal** [comment]
What are your opinions on this issue? @zinntech @asturio @Lonzak

**Comment by fellmann** [comment]
I will provide a fix today.

**Comment by fellmann** [comment]
@andreasrosdal This fix should resolve the performance problem.While testing I found another problem concerning missing lines when a row continues after a page wrap. I will create a separate ticket for it, as I believe it is not related this bug.

**Comment by andreasrosdal** [comment]
Thank you, I have verified that the performance issue is solved now. 
Please create a separate ticket for the problem concerning missing lines when a row continues after a page wrap.

**Comment by andreasrosdal** [comment]
I plan on making a new release of OpenPDF tomorrow with this fix included.

**Comment by fellmann** [comment]
@andreasrosdal Created https://github.com/LibrePDF/OpenPDF/issues/1021

**Comment by zinntech** [comment]
I just finished testing our product this morning with the 1.3.36 release and it is working great.

I certainly did not expect this issue to be analyzed, fixed and a new version released in less than 24 hours of posting this bug.

Thank you for the fast resolution of this issue, it is much appreciated by my team.

**Comment by andreasrosdal** [comment]
You are welcome. Now I have updated the latest master branch of OpenPDF to require Java 11. This is part of modernizing OpenPDF to work in Java 11+. It would be helpful if you could please test this development branch and see if OpenPDF works correctly in Java 11 for you. Thank you.
