### ISSUE TITLE
Java 8 (Java 1.8) support II

### ISSUE THREAD

**Issue by Lonzak** [LibrePDF/OpenPDF#1034]
Since you already [closed the last issue](https://github.com/LibrePDF/OpenPDF/issues/1033) - I couldn't even reply anymore. I would appreciate if you would allow me to respond and let a discussion take place and not close this issue so quickly. 

> If you need to use Java 8 then you can use version 1.3.36 or earlier.

Yes but this means no bugfixes, security fixes etc anymore.

> The latest version of the Spring library now requires Java 17: https://github.com/spring-projects/spring-framework/wiki/Spring-Framework-Versions
> Pdfbox also requires Java 11 now:
> https://github.com/apache/pdfbox/blob/trunk/pom.xml#L130

The examples you referenced are all **major** updates:
It is pdfbox 4.0 (note that there is a 2.0 and 3.0 Branch), which isn't even [released yet](https://pdfbox.apache.org/4.0/migration.html). 
And Spring Framwork 5.3 is still maintained, bugfixed and does still support Java 8.

=> So my first point is: Such a major update needs to be reflected in the version: openPDF 2.0.0. and not 1.3.X
=> Secondly I wanted to ask whether other users also face this problem - if I am the only one - ok - but maybe there are others facing this? So we should discuss our options here. Which could be to maintain a Java8 compatible branch ...

**Comment by Lonzak** [comment]
I think this is a community project where contributors to the project should be able to ask questions, raise concerns and challenge decisions imho. I have basically two out of three points (1 and 2) which are done differently in most other java projects (you even did quot some):

1.   An increase in the minimum Java version should be reflected in the project: So instead of 1.3.37 it should be 2.0.0 (as did PdfBox 3.0.1->4.0.0 or Spring 5.3.0 -> 6.0.0 or many others) This is the semantic version principle.
2. Most of these projects maintain a Java8 compatible branch (PdfBox 2.0, 3.0, Spring 5.3 and so on) (ok sure: one can decide against that)
3. I did contribute several times to the project in the past and just pointed out that this change makes it much more difficult for me (and maybe for others as well) to do so in future. My roadmap to migrate our changes to openPDF is heavily affected by this.

> If there is a need for bugfixes to the last Java 8 compatible version in the future that will be made available.
And what version should that be? 1.3.36.X?

So even you decide against maintaining a java8 compatible version the current state is not a good decision because no developer expects this heavy-impact change to be part of a bugfix version.

**Comment by andreasrosdal** [comment]
I recommend that you please try to update to Java 11 or later. The new Java version requirement is clearly described in the release notes.

Java 8 was released on March 18, 2014.

**Comment by asturio** [comment]
The other discussion still open, as I think it is important to know it many users are still using Java 8.
But as @andreasrosdal said, it is very important since java 9 to update your projects to newer versions of Java. And it is not easy to have many branches for different Java Versions.
At this time Java 8, 11, 17 and 21 are supported LTS. But probably OpenPDF will like continue for some time using Java 11, and at some point switch to Java 17, and at another point to 21 (and at that time there will be hopefully now so many jumps extra to do). In every such point, the old version of OpenPDF won't get much attention anymore. Probably only dependency updates.
