### ISSUE TITLE
Fix code scanning alert - Use of a broken or risky cryptographic algorithm

### ISSUE THREAD

**Issue by andreasrosdal** [LibrePDF/OpenPDF#1044]
CodeQL: Cryptographic algorithm MD5 is weak and should not be used. 

https://github.com/LibrePDF/OpenPDF/blob/fafed7e71b504f9ed932c22eb91bdc8a68efb321/openpdf/src/main/java/com/lowagie/text/pdf/PdfSmartCopy.java#L159-L159

Tracking issue for:
- [ ] https://github.com/LibrePDF/OpenPDF/security/code-scanning/4

**Comment by mkl-public** [comment]
> CodeQL: Cryptographic algorithm MD5 is weak and should not be used.

> https://github.com/LibrePDF/OpenPDF/blob/fafed7e71b504f9ed932c22eb91bdc8a68efb321/openpdf/src/main/java/com/lowagie/text/pdf/PdfSmartCopy.java#L159-L159

MD5 is used here merely to calculate a `HashMap` key for streams during copy. In particular this is not security relevant.
