### ISSUE TITLE
Remaining issue with form flattening

### ISSUE THREAD

**Issue by Lonzak** [LibrePDF/OpenPDF#1047]
Recently I added some code to fix form flattening problems with certain PDF documents (#992). It improved a lot of things however our QA found a bug. I added red rectangles to show the problem.  Without the rectangle it was difficult to spot:

Original with form fields:
![grafik](https://github.com/LibrePDF/OpenPDF/assets/1830174/5c3d302d-6243-4265-bcd6-162ab704e33d)

Flattened document:
![grafik](https://github.com/LibrePDF/OpenPDF/assets/1830174/44dc54b7-1952-4c57-a61e-b9d66a3f35a1)

The content of the form fields are minimally shifted to the top. I checked the code but couldn't spot it on a first glance. @mkl-public Maybe you have an idea? The document is landscape - maybe this is the cause?

[Example-SmallShift.pdf](https://github.com/LibrePDF/OpenPDF/files/14270045/Example-SmallShift.pdf)

**Comment by andreasrosdal** [comment]
Hello, as you are the form-flattening specialist on this project, pull requests to improve this is welcome.

**Comment by mkl-public** [comment]
The page has a page rotation value of 270. My guess would be that the issue is related to that.

**Comment by Lonzak** [comment]
I commented the following line:
```
rotation = rotation % 360; 
if (rotation == 90 || rotation == 270) {
   //x += box.getWidth();
}
```
And it works. So probably the following might be correct. This really needs testing...
```
rotation = rotation % 360; 
if (rotation == 90) {
   x += box.getWidth();
}
```

**Comment by mkl-public** [comment]
Indeed, it seems to be the 270° rotation.

In `com.lowagie.text.pdf.PdfStamperImp.flatFields()` starting at line 993 there is

```
rotation = rotation % 360; 
if (rotation == 90 || rotation == 270) {
    x += box.getWidth();
}
if (rotation == 180 || rotation == 270) {
    y += box.getHeight();
}
```

but I think it should be

```
rotation = rotation % 360; 
if (rotation == 90 || rotation == 180) {
    x += box.getWidth();
}
if (rotation == 180 || rotation == 270) {
    y += box.getHeight();
}
```

That error sneaked in while discussing and improving #992. But please test before integrating.

**Comment by Lonzak** [comment]
Yes you were right - I tested it with 0, 90, 180, 270 and 360° and it works with your suggested solution. Thanks for sparing with me...
