### ISSUE TITLE
PDF/A bug OutIndexBoundsException

### ISSUE THREAD

**Issue by nt11ae** [LibrePDF/OpenPDF#1048]
**Describe the bug**
When generating a pdf report through JasperReport and selecting PDF/A. A bug is generated through the openpdf library. 

com.lowagie.text.pdf.PdfStructureTreeRoot generates an OutIndexBoundsException, i really dont know what the cause is of the problem but the code in openpdf is not safe. Line 122 does not check if the array is empty.
if (obj != null && obj.isArray() && !((PdfArray) obj).getElements().**get(0)**.isNumber()) {

Some sort of check need to be placed:
**((PdfArray) obj).getElements()>0**.

**System (please complete the following information):**
 - OS: Ubuntu Linux

**Additional context**

**Comment by andreasrosdal** [comment]
This is the code in PdfStructureTreeRoot generating the OutIndexBoundsException: 

https://github.com/LibrePDF/OpenPDF/blob/master/openpdf/src/main/java/com/lowagie/text/pdf/PdfStructureTreeRoot.java#L122

**Comment by andreasrosdal** [comment]
I have committed a fix for this here:  https://github.com/LibrePDF/OpenPDF/commit/29ff601ceddbb81778db01ee6b0032bc91de2f6c

Please try the latest master branch and see if this solves the issue.

**Comment by nt11ae** [comment]
Yes this does solve my problem, thanks, when is the next release coming out? next month?

**Comment by andreasrosdal** [comment]
OpenPDF 1.4.0 will be released 2024-03-01.
