### ISSUE TITLE
Modernization of OpenPDF in 2.0.0

### ISSUE THREAD

**Issue by andreasrosdal** [LibrePDF/OpenPDF#1049]
Modernization of OpenPDF in 2.0.0:
* Removal of 108 deprecated old methods and fields. Started here: https://github.com/LibrePDF/OpenPDF/commit/be388653bc948ebfc707be58192da61eec71abd1 This will allow a cleaner API with less technical debt. See JavaDoc for the methods marked as deprecated in 1.3.40 and the new methods to use instead: https://javadoc.io/doc/com.github.librepdf/openpdf/latest/index.html 
* Allow breaking API changes to allow modern Java 17+ syntax, using generics and modern methods.
* Use modern Java 17+ compatible syntax and libraries.
* Java 17 will be required for OpenPDF 2.0.0.  https://blogs.oracle.com/javamagazine/post/its-time-to-move-your-applications-to-java-17-heres-why-and-heres-how
* Fix compilation warnings 

Pull request for modernizing OpenPDF for version 2.0.0 is welcome. 

Suggested release date for OpenPDF 2.0.0 can be 2024-03-01. After this release I imagine a long period of stable API.

**Comment by Lonzak** [comment]
According to semantic versioning this needs to be version 2.0.0

**Comment by andreasrosdal** [comment]
Okay, so the next version will be 2.0.0, where we focus on this. If you have proposals for new incompatible API changes, this is the time to do it.

**Comment by andreasrosdal** [comment]
https://github.com/flyingsaucerproject/flyingsaucer has been compiled and tested now with OpenPDF 2.0.0-SNAPSHOT, where the deprecated methods are removed. So flyingsaucer is not using any of the removed deprecated methods.

**Comment by andreasrosdal** [comment]
@rtfarte @albfernandez @sixdouglas @raodienne 
I would like to encourage you to help modernize OpenPDF further now for Java 17+.

**Comment by NicolaIsotta** [comment]
Also Java 8 -> 11 should have been a major...

**Comment by Lonzak** [comment]
@NicolaIsotta I totally agree however my issues pointing this out were closed (#1033, #1034) and a [discussion](https://github.com/LibrePDF/OpenPDF/discussions/1037) about this topic started by @stevendegroote was deleted.

**Comment by andreasrosdal** [comment]
So in this issue we can discuss modernization of OpenPDF. In particular how the API can be improved by taking advantage of new Java versions. Previous releases is not much to do about now. So I encourage you to submit proposals on how to modernize OpenPDF here.

**Comment by andreasrosdal** [comment]
It's important for this project to listen to the users of the library, so therefore feedback about how to modernize the library is welcome. 

It seems that some users are not able to update their Java versions so easily, and for these users we can maintain separate branches for old Java version, if you specifically request it. Over time most users are able to update their Java versions eventually.

**Comment by andreasrosdal** [comment]
Furthermore, it's very much possible to volunteer to help maintain this fine library, and to help maintain branches and releases for old Java versions. It's also possible to create forks on Github, and create your own releases with specific features.

**Comment by sixdouglas** [comment]
The code is dealing with dates as `Calendar` maybe we could bring some support for the `java.time.*` API [here](https://docs.oracle.com/javase/8/docs/api/java/time/package-summary.html)

**Comment by andreasrosdal** [comment]
Closing this now. So the two modernizations in OpenPDF 2.0 will be removal of 108 deprecated methods and fields, and requirement for Java 17. Pull requests for further modernization is welcome, however, these two improvements is all for now that I'll implement.
