### ISSUE TITLE
Support of OpenPDF 1.3.x branch?

### ISSUE THREAD

**Issue by bsanchezb** [LibrePDF/OpenPDF#1054]
Hello,

As the comments section is closed within #1049, I create a new issue with the question.

As [OpenPDF 2.0.0](https://github.com/LibrePDF/OpenPDF/releases/tag/2.0.0) version has been released, the question arises whether the old Java 8 compatible branch is going to be maintained?

What is the reason for so quick migration to 2.x version and dropping everything below Java 17? Is OpenPDF using any dependencies requiring Java 17 or higher? To my opinion, it would be good to support the least possible version of Java, which could be at least Java 11...

KR,
Aleksandr

_P.S. I see that some new versions have been released starting from end of 2023 increasing the minimum version of Java, starting to Java 9 and then Java 11. But this move seems too quick without providing users sufficient time for migration._

**Comment by Lonzak** [comment]
I gave up starting a discussion about this topic (which lead to the [following discussion](https://github.com/LibrePDF/OpenPDF/discussions/1053))

**Comment by andreasrosdal** [comment]
Volunteers to maintain this retro branch is welcome.

**Comment by Lonzak** [comment]
> Volunteers to maintain this retro branch is welcome.

It doesn't seem so - I was starting discussion #1052 about exactly this topic and it was locked and closed immediately. (As were others like #1037 started by @stevendegroote)

But okay let's discuss this here then because I think there is the need from the community to maintain a java8 branch.

**Comment by andreasrosdal** [comment]
So I am gradually understanding the need for maintaining old support for ancient Java versions. Contact asturio if you would like to volunteer for this. I am gradually retiring from OpenPDF maintenance.

**Comment by asturio** [comment]
So, I released

https://github.com/LibrePDF/OpenPDF/releases/tag/1.4.1 (Java 11) and
https://github.com/LibrePDF/OpenPDF/releases/tag/1.3.41 (Java 8)

As I mentioned before, main-development will be only in **master** (2.0.x). So if you think a bugfix should be backported to 1.3 or 1.4, just create a new issue or pull request with the cherry picks from master.
