### ISSUE TITLE
2.0.0: java.lang.NoSuchMethodError: 'void fr.opensagres.poi.xwpf.converter.pdf.internal.elements.StylableDocumentSection$SectionPdfPTable.addCell(com.lowagie.text.pdf.PdfPCell)

### ISSUE THREAD

**Issue by henricook** [LibrePDF/OpenPDF#1055]
**Describe the bug**
When trying to bump to 2.0.0 I see this **runtime** error in a test of mine that does a 
```scala
PdfConverter.getInstance()
      .convert(
        new XWPFDocument(GFiles.asByteSource(docx.toFile).openStream())
        ...
        )
```

```
[info]   java.lang.NoSuchMethodError: 'void fr.opensagres.poi.xwpf.converter.pdf.internal.elements.StylableDocumentSection$SectionPdfPTable.addCell(com.lowagie.text.pdf.PdfPCell)'
[info]   at fr.opensagres.poi.xwpf.converter.pdf.internal.elements.StylableDocumentSection.createLayoutTable(StylableDocumentSection.java:424)
[info]   at fr.opensagres.poi.xwpf.converter.pdf.internal.elements.StylableDocumentSection.createLayoutTable(StylableDocumentSection.java:401)
[info]   at fr.opensagres.poi.xwpf.converter.pdf.internal.elements.StylableDocument.setActiveMasterPage(StylableDocument.java:318)
[info]   at fr.opensagres.poi.xwpf.converter.pdf.internal.PdfMapper.setActiveMasterPage(PdfMapper.java:254)
[info]   at fr.opensagres.poi.xwpf.converter.pdf.internal.PdfMapper.setActiveMasterPage(PdfMapper.java:123)
[info]   at fr.opensagres.poi.xwpf.converter.core.MasterPageManager.fireSectionChanged(MasterPageManager.java:173)
[info]   at fr.opensagres.poi.xwpf.converter.core.MasterPageManager.initialize(MasterPageManager.java:102)
[info]   at fr.opensagres.poi.xwpf.converter.core.XWPFDocumentVisitor.visitBodyElements(XWPFDocumentVisitor.java:249)
[info]   at fr.opensagres.poi.xwpf.converter.core.XWPFDocumentVisitor.start(XWPFDocumentVisitor.java:216)
[info]   at fr.opensagres.poi.xwpf.converter.pdf.PdfConverter.doConvert(PdfConverter.java:57)
```

I think that these dependencies are entirely inside OpenPDF so I don't think it's (for example) an eviction problem in my project and appears related to this change: https://github.com/LibrePDF/OpenPDF/pull/844

Could it be an issue with how the release was built?

**Comment by andreasrosdal** [comment]
In OpenPDF 2.0 in #844 there was an API change. So the fr.opensagres.poi library needs a small change to fix this.

**Comment by andreasrosdal** [comment]
https://github.com/opensagres/xdocreport/blob/master/thirdparties-extension/fr.opensagres.poi.xwpf.converter.pdf.itext5/src/main/java/fr/opensagres/poi/xwpf/converter/pdf/internal/elements/StylableDocumentSection.java

**Comment by henricook** [comment]
Ah I see thanks, looks like it might take a while! 😢

**Comment by andreasrosdal** [comment]
The change is easy, so I suggest you to submit a bugreport or PR to xdocreport and encourage them to make a new release.

**Comment by henricook** [comment]
Is it? It looks like they're using itext and not openpdf. Sorry if I'm being dense 😅

**Comment by henricook** [comment]
https://github.com/opensagres/xdocreport/issues/635

**Comment by henricook** [comment]
Thank you for creating an MR for this in xdocreport @andreasrosdal , very kind
