### ISSUE TITLE
Generating PDF from HTML containing CSS font-size property fails with IllegalArgumentException

### ISSUE THREAD

**Issue by RadekWikturna** [LibrePDF/OpenPDF#1057]
**Describe the bug**
When converting HTML to PDF, using `HTMLWorker.parseToList` and the HTML contains the [CCS font-size property](https://www.w3schools.com/cssref/pr_font_font-size.php), such as in the test below, rendering to PDF fails with 

> IllegalArgumentException: font size too small: 0.0

**To Reproduce**
```
@Test	
public void testCCSFonts() throws Exception {
	StringReader reader = new StringReader("<span style=\"font-size:xx-small\">Text xx-small</span><br/> <span style=\"font-size:x-small\">Text x-small</span><br/> <span style=\"font-size:small\">Text small</span><br/> <span style=\"font-size:medium\">Text medium</span><br/> <span style=\"font-size:large\">Text large</span><br/> <span style=\"font-size:x-large\">Text x-large</span><br/> <span style=\"font-size:xx-large\">Text xx-large</span><br/>");
	StyleSheet styleSheet = new StyleSheet();
	Map<String, Object> interfaceProps = new HashMap<>();
	List<Element> elements = HTMLWorker.parseToList(reader, styleSheet, interfaceProps);
		
        Document document = new Document();
        PdfWriter instance = PdfWriter.getInstance(document, new FileOutputStream("CCS Fonts.pdf"));
        document.open();
        instance.getInfo().put(PdfName.CREATOR, new PdfString(Document.getVersion()));
        for(Element e: elements) {
        	document.add(e);
        }
        document.close();
}

```
**Expected behavior**
The generated PDF should show approximately the same output as the HTML in a browser and should not fail with exception.

**Screenshots**
The HTML snippet below shows correctly in a browser:
![image](https://github.com/LibrePDF/OpenPDF/assets/120576514/8bebe446-4c44-4a6a-a39c-b6ede4b40039)

**System (please complete the following information):**
 - OS: Windows 11
 - Used Font: default

**Comment by asturio** [comment]
Pull requests are welcome!
