### ISSUE TITLE
Font style gets ignored when instantiating a new font

### ISSUE THREAD

**Issue by jjkarppi** [LibrePDF/OpenPDF#106]
When a new font is created using _FontFactory.getFont()_ with _style_ as one parameter, the style parameter gets ignored and _Font.NORMAL_ style gets applied. E.g.

`FontFactory.registerDirectories();`
`Font titleFont = FontFactory.getFont("Trebuchet MS", 16, Font.BOLD);`

results in that _titleFont_ style is _Font.NORMAL_ (value 0) instead of _Font.BOLD_ (value 1).

Debugging, this the error seems to happen in _FontFactoryImp.getFont(String fontname, String encoding, boolean embedded, float size, int style, Color color, boolean cached)_ here:

`if (style != Font.UNDEFINED && found) {`
`    style &= ~fs;`
`}`

If I understand correctly, _style_ and _fs_ have the same value inside this _if_ clause, and therefore a bitwise AND operation on a value and its complement always results in 0, which is the value for _Font.NORMAL_.

This bug didn't exist in iText 2.1.7. It can be circumvented by applying the desired style after the font is created, e.g.

`FontFactory.registerDirectories();`
`Font titleFont = FontFactory.getFont("Trebuchet MS", 16, Font.BOLD); // Style becomes NORMAL here`
`titleFont.setStyle(Font.BOLD); // Style becomes BOLD`

**Comment by andreasrosdal** [comment]
Thanks for the bugreport. Pull-requests welcome!

**Comment by andreasrosdal** [comment]
@jjkarppi  Can you please verify that this has been fixed in the latest git master version?

**Comment by jjkarppi** [comment]
I tested this with OpenPDF 1.2.7, and it's now fixed.
