### ISSUE TITLE
Version 1.3.x should not contain breaking changes like https://github.com/LibrePDF/OpenPDF/pull/844

### ISSUE THREAD

**Issue by lgemeinhardt** [LibrePDF/OpenPDF#1070]
Version 1.3.x should not contain breaking changes like https://github.com/LibrePDF/OpenPDF/pull/844, because this minor version update (like 1.3.40 to 1.3.41) does not reflect this.
For Version 1.4.x or better 2.x this is totally fine.

**Comment by asturio** [comment]
Pull requests are welcome. Should the commit 9d358579f2f7789df1efd55012a93aa97b2d9bd1 be reverted?

As only the return value was changed from "void" to PdfPCell, we were not expecting any issues with this. Your code should compile fine. It may be necessary to recompile, but without changes.

**Comment by lgemeinhardt** [comment]
Revert this (for sure only in the 1.3 branch) would be fine.
For sure recompiled code does not have any issues, but w/o (like using an "external" jar) runs into a NoSuchMethodError (because the return type is part of the bytecode signature).

**Comment by asturio** [comment]
Reverted, comming in next release of 1.3
