### ISSUE TITLE
Unable to render text with "HelveticaNeueLTPro"

### ISSUE THREAD

**Issue by stefanbethke** [LibrePDF/OpenPDF#1071]
**Describe the bug**
Registering a TTC font file with FontFactory.registerDirectory() loads the TTC file that I received from the font vendor, and FontFactory.getRegisteredFonts() lists the different faces contained in the file successfully.

However, when I try to render text using the font, all glyphs render on top of each other, as if each glyph was zero width. Using for example chunk.setCharacterSpacing(5) will show the glyphs separately, but they clearly don't have the correct widths.

The font file works fine in macOS and Windows, and I can create PDFs successfully using other tools.

**To Reproduce**
```
public class OpenPDFBug {
  @Test
  @Disabled("only manual execution in IDE")
  public void demonstrateOpenPDFBug() throws IOException, URISyntaxException {
    registerFonts();

    OutputStream os = new FileOutputStream(new File ("target/openpdfbug.pdf"));
    Document document = new Document();
    PdfWriter pdfWriter = PdfWriter.getInstance(document, os);
    document.open();

    Font times = new Font(Font.TIMES_ROMAN, 12f);
    Font helveticaNeue = FontFactory.getFont("Helvetica Neue", 12f);

    document.add(new Paragraph("A line using Times New Roman.", times));
    document.add(new Paragraph("A line using Helvetica Neue.", helveticaNeue));
    Chunk spacedOut = new Chunk("A line using Helvetica Neue.", helveticaNeue);
    spacedOut.setCharacterSpacing(8f);
    document.add(spacedOut);

    document.close();
    os.close();
  }

  void registerFonts() throws IOException, URISyntaxException {
    URL url = OpenPDFBug.class.getClassLoader().getResource("fonts");
    if (url == null)
      throw new IOException("Unable to open resources/fonts");
    int n = FontFactory.registerDirectory(new File(url.toURI()).getPath(), true);
    if (n == 0) {
      throw new IOException("Unable to register any fonts from " + new File(url.toURI()).getPath());
    }
  }
}
```

**Expected behavior**
Font should be rendered according to its metrics.

**Screenshots**
<img width="414" alt="openpdf-helveticaneue-broken" src="https://github.com/LibrePDF/OpenPDF/assets/3328988/f5e7c67b-ea9f-42d5-b3fa-a3a91ed528b1">
[openpdfbug.pdf](https://github.com/LibrePDF/OpenPDF/files/14370795/openpdfbug.pdf)

**System (please complete the following information):**
 - OS: macOS
 - Java 17
 - OpenPDF 1.4.1
 - Used Font: HelveticaNeue.ttc

**Comment by asturio** [comment]
Oh, that is interesting. When I open your PDF in Firefox, it look like this:
![Bildschirmfoto vom 2024-02-22 11-41-42](https://github.com/LibrePDF/OpenPDF/assets/13033226/63bb0c9d-c801-429e-a65a-adb1282f4de2)
* OS: Linux
* PDF-Viewer: Firefox or Evince

It seems your viewer is not finding the correct font to display the PDF correctly. You could embed the font in the PDF, so it always displays correctly.

**Comment by stefanbethke** [comment]
Ah, thanks, that makes a lot of sense. Let me check if I can get the font embedded.

**Comment by asturio** [comment]
Any success after embedding the font?

**Comment by stefanbethke** [comment]
Not really. I've tried to mark the font for embedding like this:
```
    Font helveticaNeue = FontFactory.getFont("Helvetica Neue", FontFactory.defaultEncoding, true, 12f);
```
The result is not promising, see attached PDF.
[openpdfbug.pdf](https://github.com/LibrePDF/OpenPDF/files/14382897/openpdfbug.pdf)

**Comment by asturio** [comment]
You are probably using the wrong encoding. Try this:

`Font helveticaNeue = FontFactory.getFont("Helvetica Neue", BaseFont.IDENTITY_H, BaseFont.EMBEDDED, 12f);`

**Comment by stefanbethke** [comment]
Unfortunately, not much better.
[openpdfbug.pdf](https://github.com/LibrePDF/OpenPDF/files/14383404/openpdfbug.pdf)

**Comment by asturio** [comment]
I just verified. Loading TTF and TTC fonts are working. Would you mind sending me the font per E-Mail?

**Comment by stefanbethke** [comment]
I will give that a try, thanks.

**Comment by asturio** [comment]
class OpenPDFBug {

    @Test
//    @Disabled("only manual execution in IDE")
    void demonstrateOpenPDFBug() throws IOException {
        registerFonts();

        OutputStream os = new FileOutputStream("target/openpdfbug.pdf");
        Document document = new Document();
        PdfWriter pdfWriter = PdfWriter.getInstance(document, os);
        document.open();

        Font times = new Font(Font.TIMES_ROMAN, 12f);
        Font helveticaNeue1 = FontFactory.getFont("Helvetica Neue Thin", IDENTITY_H, EMBEDDED, 12f);
        Font helveticaNeue2 = new Font(
            BaseFont.createFont("/home/claudio/fonts/backup/HelveticaNeue.ttc,0", IDENTITY_H, EMBEDDED), 12f);
        Font gothic = new Font(
            BaseFont.createFont("/home/claudio/fonts/msgothic.ttc,1", IDENTITY_H, EMBEDDED), 12f);

        int i = 0;
        addTestParagraph(document, ++i, times);
        addTestParagraph(document, ++i, helveticaNeue1);
        addTestParagraph(document, ++i, helveticaNeue2);
        addTestParagraph(document, ++i, gothic);

        document.close();
        os.close();
    }

    private static void addTestParagraph(Document document, int i, Font font) {
        String fontName;
        if (font.getBaseFont() == null) {
            fontName = font.getFamilyname();
        } else {
            fontName = font.getBaseFont().getPostscriptFontName();
        }
        document.add(new Phrase(++i + ": "));
        document.add(new Phrase("A line using " + fontName, font));
        document.add(Chunk.NEWLINE);
    }

    void registerFonts() throws IOException {
        int n = FontFactory.registerDirectory("/home/claudio/fonts");
        if (n == 0) {
            throw new IOException("Unable to register any fonts from ");
        }
    }
}

**Comment by stefanbethke** [comment]
Thank you, that does the trick. The interesting thing is that FontFactory.getRegisteredFonts() does list the fonts registered from the TTC, but somehow they are not working correctly. But unpacking them is not a problem. Thanks for all your help!
