### ISSUE TITLE
Pdf Reader is not adding pdf to new Document

### ISSUE THREAD

**Issue by adityamauryaMog** [LibrePDF/OpenPDF#1096]
I have a various PDF i want to merge all those PDF to one PDF in pages But its not working 

public static void mergePdfFiles(List<String> pdfFiles, String outputFile) throws IOException, DocumentException {

     Document document = new Document(PageSize.A4.rotate());
     FileOutputStream fileOutputStream = new FileOutputStream(outputFile);
    PdfWriter pdfWriter = PdfWriter.getInstance(document,fileOutputStream);
     //document.addWriter(pdfWriter);

        List<PdfReader> readers = new ArrayList<PdfReader>();

        for (String pdfFile : pdfFiles) {
            try {
                readers.add(new PdfReader(pdfFile));
            } catch (IOException e) {
                e.printStackTrace();
            }
        }

        PdfCopy pdfCopy = new PdfCopy(document,fileOutputStream);
        document.open();
        for (PdfReader reader : readers) {
            for (int i = 1; i <= reader.getNumberOfPages(); i++) {
                document.newPage();
                PdfImportedPage page = pdfCopy.getImportedPage(reader, i);
                pdfCopy.addPage(page);

            }
        }
        document.close();

    }

Exception :  com.lowagie.text.ExceptionConverter: The document has no pages.

**Comment by mkl-public** [comment]
You use your `Document document` and your `FileOutputStream fileOutputStream` both for `PdfWriter pdfWriter` and `PdfCopy pdfCopy`. That's extremely likely to cause issues.

If I read your code correctly, there is no need for the `PdfWriter pdfWriter`, so I'd propose to drop it.
