### ISSUE TITLE
Reduce dependencies

### ISSUE THREAD

**Issue by evernat** [LibrePDF/OpenPDF#113]
I suggest reducing dependencies used by openpdf, in order that fewer users have to resolve version conflicts between dependencies and to help users who don't have clean dependency management. (See [this example](https://dzone.com/articles/10-effective-tips-on-using-maven) recommending to explicitly repeat transitive dependencies in their pom, forgetting in my opinion that it will defeat your library updating its dependencies when it's needed.)

For that, I have located three commits adding dependencies which I think don't have a good enough reason to be added in openpdf:
- https://github.com/LibrePDF/OpenPDF/commit/7b2a602fd627eeba69b7aa030551d8ed4cd672d7#comments
- https://github.com/LibrePDF/OpenPDF/commit/8ad6e9bf012d67eb4149bb8064cf8df8f13d3a63#comments
- https://github.com/LibrePDF/OpenPDF/commit/fb4ec297b0e6a555ece9166183f905068c89bf2f#comments

For juniversalchardet and commons-compress dependencies, it is a bit less obvious if they have, or not, a good enough reason to be added (such as fixing bugs), so I do not have a strong opinion on them at the moment.
That said, commons-compress has more risks to have version conflicts than juniversalchardet, so if the only reason is to remove the LZWDecoder class used in PdfReader then I would debate that.

**Comment by andreasrosdal** [comment]
Apache Commons IO and Apache Commons Codec have been replaced.

**Comment by evernat** [comment]
The LZWDecoder.java file is not a problem because it also includes: 

> In a mail dating from January 23, 2008, Brian Burkhalter (@sun.com) gave us permission to use the code under the following version of the BSD license: ...

and there is no problem to include BSD-license code (BSD is permissive) in a MPL/LGPL software. See for example: https://opensource.stackexchange.com/questions/304/can-i-take-bsd-licensed-code-and-distribute-it-under-gpl
provided that you don't remove the copyright "2005 Sun Microsystems, Inc" and the BSD license text from the file.

By the way, iText 5/7 still includes that LZWDecoder.java file:
https://github.com/itext/itextpdf/blob/develop/itext/src/main/java/com/itextpdf/text/pdf/LZWDecoder.java

**Comment by andreasrosdal** [comment]
Okay, I'll fix. Anything else, or can I create a new release then?

**Comment by evernat** [comment]
I think that it's ok for me.

**Comment by andreasrosdal** [comment]
Done. I will create a new release shortly.
