### ISSUE TITLE
Replace existing text by matching pattern in PDF

### ISSUE THREAD

**Issue by andriimanzar** [LibrePDF/OpenPDF#1143]
I've checked the given examples and the wiki for this repository, but I cannot find any methods to replace existing text in a PDF. For example, if I have '{{some_variable}}' in the PDF text, I need to replace it with some actual value. I would be grateful if someone could tell me if there is such a feature?

**Comment by asturio** [comment]
I don't know if this can be done easy. As an existing PDF with that "placeholder", you need to actually read it, all the text, replace what you want, and render it new. Just replacing the placeholder won't really reformat your text in the PDF.
What you need is some kind of PDF-Template, or write a parser to create your PDF with the replaced text.
Please correct my, if I'm wrong.

**Comment by mkl-public** [comment]
>I don't know if this can be done easy

A generic solution of this is somewhere between impossible and very difficult. For very well-behaved PDFs certain short cuts are possible and the task may even be considered easy.

**Comment by andriimanzar** [comment]
Thank you for replies. I truly appreciate it!
