### ISSUE TITLE
PdfCopy cannot be used for writing

### ISSUE THREAD

**Issue by rasmusfaber** [LibrePDF/OpenPDF#1165]
**Is your feature request related to a problem? Please describe.**
`com.lowagie.text.pdf.PdfCopy` extends `PdfWriter`, but it cannot actually be used for writing to a document. It just silently ignores calls that tries to add new pages.

**Describe the solution you'd like**
`PdfCopy` should just add new pages if requested.

**Describe alternatives you've considered**
An alternative is to generate a temporary PDF file with the required new pages and then copy those into the new document with PdfCopy, but that is a bit wasteful.

**Your real name**
Rasmus Faber-Espensen

**Additional context**
PR will follow shortly.

**Comment by asturio** [comment]
The PR is in the queue. I'll merge it soon, if there is no resistance.
