### ISSUE TITLE
Japanese symbols are not rendered into PDF file

### ISSUE THREAD

**Issue by a5a351e7** [LibrePDF/OpenPDF#1196]
### Describe the bug

If Japanese symbols are used, these are not displayed in a generated PDF file.

### To Reproduce

Code to reproduce the issue

```
import com.lowagie.text.Document;
import com.lowagie.text.DocumentException;
import com.lowagie.text.Paragraph;
import com.lowagie.text.pdf.PdfName;
import com.lowagie.text.pdf.PdfString;
import com.lowagie.text.pdf.PdfWriter;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;

public class App {
    public static void main( String[] args ) {
        System.out.println( "Hello World!" );

        // step 1: creation of a document-object
        Document document = new Document();
        try {
            // step 2:
            // we create a writer that listens to the document
            // and directs a PDF-stream to a file
            final PdfWriter instance = PdfWriter.getInstance(document, Files.newOutputStream(Paths.get("HelloWorld.pdf")));

            // step 3: we open the document
            document.open();
            instance.getInfo().put(PdfName.CREATOR, new PdfString(Document.getVersion()));

            // step 4: we add a paragraph to the document
            document.add(new Paragraph("Hello World"));
            document.add(new Paragraph("START こんにちは、これはテストです END"));
            document.add(new Paragraph("Hello World"));
        } catch (DocumentException | IOException de) {
            System.err.println(de.getMessage());
        }

        // step 5: we close the document
        document.close();
    }
}
```

### Expected behavior
I expected the rendering of the Japanese symbols written in the PDF file.

### Screenshots

![Screenshot at 2024-07-26 14-43-22](https://github.com/user-attachments/assets/a15a6110-af95-4631-8754-dcf911dd1292)

### System

(please complete the following information)

- OS: Ubuntu 24.04 LTS
- Used font: default
- OpenPDF version: 2.0.2

## Your real name
Florian aka GitHub user a5a351e7

### Additional context

I am not quire sure, if this problem is related to #[946](https://github.com/LibrePDF/OpenPDF/issues/946)

**Comment by Lonzak** [comment]
Did you include the asian.jar in your classpath?

<dependency>
    <groupId>com.lowagie</groupId>
    <artifactId>itextasian</artifactId>
    <version>1.5.2</version>
</dependency>

**Comment by a5a351e7** [comment]
Hi Lonzak, 

unfortunately, this dependency is not available via Maven Central (https://central.sonatype.com/search?q=itextasian) and OpenMind (via https://mvnrepository.com/artifact/com.lowagie/itextasian/1.5.2 ) apparently no longer offers the file for download.

Which repository are you using?

**Comment by Lonzak** [comment]
Yeah you are right eventhough there are still listed it seems they have been removed:
https://mvnrepository.com/artifact/com.lowagie/itextasian

A quick google search turned up this [repo](http://123.232.10.234:8212/nexus/content/groups/public/com/lowagie/itextasian/1.5.2/). So I would download it there and first try whether this fixes your issue...

**Comment by StevenStreasick** [comment]
You can get these symbols to render. However, I was able to get it to render under two conditions in my test. 

- I had to specify a custom font type that supported Japanese characters
- I also had to specify my encoding type of the font

To fix your demo, try something like
```
FontFactory.register("C:\\Users\\sstreasick\\Downloads\\Meiryo.ttf", "meiryo");
Font japaneseFont = FontFactory.getFont("meiryo", BaseFont.IDENTITY_H, BaseFont.EMBEDDED, 12);
			
Paragraph bilingualParagraph = new Paragraph();
Chunk start = new Chunk("START ");
Chunk japanseText = new Chunk("こんにちは、これはテストです", japaneseFont);
Chunk end = new Chunk(" END");
bilingualParagraph.add(start);
bilingualParagraph.add(japanseText);
bilingualParagraph.add(end);
   
doc.add(bilingualParagraph);
```

**Comment by a5a351e7** [comment]
@Lonzak , Thank you! The repository with the IP address seems somewhat ominous and no longer appropriate, especially in view of the supply chain attacks. Using the new itext-asian library did not work for me either. The characters are not output either.

@StevenStreasick , Thank you! Your suggestion and the code example work. 

In general it seems to be necessary to use a Unicode font instead of the standard Helvetica font, see #363.
IMHO: This feature should be included more prominently in the documentation. 

I am now looking for a beautiful and usable Unicode font. Perhaps Helvetica can also be replaced as the standard font with a Unicode font.

**Comment by vk-github18** [comment]
See https://fonts.google.com/noto

**Comment by a5a351e7** [comment]
@vk-github18 Thank you! Noto looks great to me.

In @StevenStreasick  example, I have to manually specify the font for the particular language in the chunks or paragraphs. Is it possible to make a number of fonts (e.g. all Noto fonts) available as usable in OpenPDF and OpenPDF itself decides when which font must be used?

My problem is that I don't know at this point in the code which characters will be used. What is the best practice here?

**Comment by Lonzak** [comment]
Ok my bad - I thought you know what the itext-asian.jar is for. Those cmaps are utilized internally by openPDF when rendering Asian characters, ensuring that characters are correctly interpreted and displayed.     
> The *.cmap and *.properties files in this jar are necessary to produce PDF files with iText that use CJK fonts.

However you still need the actual font. But for this there are several possibilities.

> Is it possible to make a number of fonts (e.g. all Noto fonts) available as usable in OpenPDF and OpenPDF itself decides when which font must be used?

1. Load the font from the system  (e.g. Google Noto Sans CJK, Arial Unicode MS or Adobe's [Heisei Mincho](https://fonts.adobe.com/fonts/heisei-mincho-std) font-family and [Heisei Kaku Gothic](https://fonts.adobe.com/fonts/heisei-kaku-gothic-std) or Microsoft's [SimHei](https://learn.microsoft.com/en-us/typography/font-list/simhei?source=recommendations) or [SimSun](https://learn.microsoft.com/en-us/typography/font-list/simsun). This however is platform dependent.
2. Include such font in your project: Add the font file to your project resources. Ensure it's accessible within your project structure. You basically bring the font along with your project. 
3. Use font embedding. Use openPDF to embed the font into your PDF. This ensures the PDF will display correctly on any platform.

**Comment by a5a351e7** [comment]
@Lonzak Thank you for clarification!

Fonts such as Noto have different variants, e.g. Noto Sans Korean, Noto Serif Japanese, Noto Naskh Arabic (see https://fonts.google.com/noto/fonts). Each variant is offered in its own font file.

If I have understood correctly, I can only set a font directly on text objects (paragraph, chunk) and not for the entire document. If this assumption is correct, then I ask then how I can dynamically set the correct font for the particular text object.

Sorry for my lack of detailed knowledge on the subject of fonts and their processing.

**Comment by Lonzak** [comment]
> If I have understood correctly, I can only set a font directly on text objects (paragraph, chunk) and not for the entire document.
Yes that is correct. (I think iText starting from version 7 supports this)

> If this assumption is correct, then I ask then how I can dynamically set the correct font for the particular text object.
What exactly do you mean with "dynamically set the correct font"?
Do you mean the type and the style of the font itself? Or loading e.g. a japanese or korean font?
Since you are the creator of the document you know which font you need and this one you'll load ...?
Maybe you can describe this in more detail.

**Comment by a5a351e7** [comment]
My big problem is that I have a template that is made up of a western language and any language. For example an invoice, the template is in English and the data can be any language. From English to French, to Japanese and Arabic.

At the moment I can't exactly say which language/symbols will be used. I am looking for a generally valid way to write Unicode characters (i.e. all fonts) into a PDF.

**Comment by StevenStreasick** [comment]
Look into this class https://librepdf.github.io/OpenPDF/docs-1-2-7/com/lowagie/text/pdf/FontSelector.html

Once I get a bit more time, I will edit this message with whether this class worked or not on my end, and with a demo for you.

**Comment by Lonzak** [comment]
Then use a unicode font which contains "all" languages like Arial Unicode MS. Or like Steven suggested the FontSelector looks promising...

**Comment by a5a351e7** [comment]
@StevenStreasick The FontSelector is great! Thank you very much for mentioning it and for the little code example!

@Lonzak That's exactly what I researched in parallel and found the following font (https://github.com/satbyy/go-noto-universal), which is 15 MB in size and would have worked without the FontSelector.

These two solutions resolved the problem for me perfectly.

I would like to thank everyone involved for their constructive and fast responses to my questions and for clarifying the way it works! 🙏
