### ISSUE TITLE
Duplicate files in deployed Jar

### ISSUE THREAD

**Issue by fl0gru85** [LibrePDF/OpenPDF#121]
Unfortunately there are duplicated maven files (pom.xml, pom.properties) in the deployed jar, see screenshot. 

This causes currently some errors for our application. 

Would it be possible to to remove this files from the built jar?

![openpdf](https://user-images.githubusercontent.com/20721494/49165518-ad39e600-f331-11e8-82df-7b6fc3deaa23.png)

**Comment by andreasrosdal** [comment]
This has been fixed in OpenPDF version 1.2.6.
