### ISSUE TITLE
BidiLine - Handling of indexChars when runDirection is LTR (or RTL)

### ISSUE THREAD

**Issue by PaulCormier** [LibrePDF/OpenPDF#122]
In commit a0754dc4, lines [183 to 197 of BidiLine](https://github.com/LibrePDF/OpenPDF/blob/c4fbcb5f64c241c948c6c88701ccca6fdd8391a2/openpdf/src/main/java/com/lowagie/text/pdf/BidiLine.java#L183L197) were removed because of the removal of the BidiOrder class. But when a runDirection is set to either `PdfWriter.RUN_DIRECTION_LTR` or `PdfWriter.RUN_DIRECTION_RTL` the indexChars array (used by createArrayOfPdfChunks) is no longer initialized correctly. The array is used on [line 461](https://github.com/LibrePDF/OpenPDF/blob/a0754dc4dc8197095839efcf206cd89c9d792090/openpdf/src/main/java/com/lowagie/text/pdf/BidiLine.java#L461) to pick the right letters out of the detailChunks array. When it is all 0s only the first letter is ever printed.

**Comment by andreasrosdal** [comment]
Thanks for reporting this. Can you please submit a pull-request to fix it?

**Comment by PaulCormier** [comment]
I'll keep working on this today.

My main motivation is also to be "on the safe side" and use OpenPDF in place of iText 2.1.7. Specifically, I'm looking at using it with JasperReports. Since JasperReports is meant to support bidirectional text, there needs to be some option for outputting RTL if they are going to adopt OpenPDF. Thoughts?

**Comment by andreasrosdal** [comment]
@PaulCormier Excellent idea. I think you working on supporting OpenPDF in JasperReports will help other people in the same situation. I will gladly review and merge any changes.

**Comment by andreasrosdal** [comment]
There is also this:  https://github.com/TIBCOSoftware/jasperreports/issues/17
