### ISSUE TITLE
Surrogate Pair Character Not Printed After Adding ApacheFOP Dependencies

### ISSUE THREAD

**Issue by r-okui** [LibrePDF/OpenPDF#1252]
### Describe the bug

After adding specific dependencies to `pdf-toolbox/pom.xml` and running `src/main/java/org/librepdf/openpdf/examples/fonts/languages/Japanese.java`, nothing is printed.

### To Reproduce

1. Add the following dependencies to `pdf-toolbox/pom.xml`:
    ```xml
    <dependency>
      <groupId>org.apache.xmlgraphics</groupId>
      <artifactId>fop</artifactId>
      <version>2.10</version>
    </dependency>
    <dependency>
      <groupId>org.apache.xmlgraphics</groupId>
      <artifactId>xmlgraphics-commons</artifactId>
      <version>2.10</version>
    </dependency>
    ```
2. Run the `src/main/java/org/librepdf/openpdf/examples/fonts/languages/Japanese.java` file.

### Expected behavior

The document should print the character `𠮷` (`\uD842\uDFB7`).

### System

- OS: Windows11
- Used font: fonts/GenShinGothic-Normal.ttf
- OpenPDF version: 2.0.3

## Your real name
Ryota Okui

### Additional context

- The dependencies were added as per the instructions provided in the following link: [Multi byte character language support with TTF fonts](https://github.com/LibrePDF/OpenPDF/wiki/Multi-byte-character-language-support-with-TTF-fonts).
- The character `\uD842\uDFB7` is a surrogate pair character.

**Comment by vk-github18** [comment]
See also https://github.com/LibrePDF/OpenPDF/wiki/Accents,-DIN-91379,-non-Latin-scripts for another option

**Comment by r-okui** [comment]
> See also https://github.com/LibrePDF/OpenPDF/wiki/Accents,-DIN-91379,-non-Latin-scripts for another option

Thank you for your guidance. The issue has been successfully resolved.

```
LayoutProcessor.enableKernLiga(); // Add this line
        
// step 0: prepare font with chinese symbols
BaseFont baseFont = BaseFont.createFont(
        Japanese.class.getClassLoader().getResource("fonts/GenShinGothic-Normal.ttf").getFile(),
        BaseFont.IDENTITY_H, BaseFont.EMBEDDED);
```****
