### ISSUE TITLE
openPDF performance decrease 40%, compared version 1.3.29 and 1.3.4

### ISSUE THREAD

**Issue by missFuture** [LibrePDF/OpenPDF#1253]
PLEASE FILL THIS TEMPLATE AS MUCH AS POSSIBLE. REMOVE IRRELEVANT PARTS.

### Describe the bug

A clear and concise description of what the bug is

### To Reproduce

Code to reproduce the issue

1. Sample Code
2. Unit-Test

### System

(please complete the following information)

- Used font:
- OpenPDF version:

## Your real name
Please specify your full name here, so that we can verify your identity. 
If you have a conflict of interest describe this here also.

**Comment by KAHILER0528** [comment]
y
