### ISSUE TITLE
LGTM code review

### ISSUE THREAD

**Issue by andreasrosdal** [LibrePDF/OpenPDF#128]
LGTM code review results in 27 errors, 131 warnings in OpenPDF.
Any help with fixing these issues is welcome! Some of the errors and warnings would be easy to fix for new contributors.

The report can be found here:
https://lgtm.com/projects/g/LibrePDF/OpenPDF/alerts/?mode=list

**Comment by andreasrosdal** [comment]
@sixdouglas can you help?

**Comment by andreasrosdal** [comment]
It's now 3 errors, and 94 warnings!

**Comment by andreasrosdal** [comment]
The repo has been updated now.

**Comment by andreasrosdal** [comment]
OpenPDF now has 0 errors, and 82 warnings!

https://lgtm.com/projects/g/andreasrosdal/OpenPDF/?mode=list

**Comment by mluppi** [comment]
Updated Link: https://lgtm.com/projects/g/LibrePDF/OpenPDF/alerts/?mode=list

**Comment by asturio** [comment]
I think any improvement is an improvement. Some kind of warnings can be bundled and resolved together, buy I think there is no need to remove them all at once.
Other changes may be more important or valuable.

**Comment by sixdouglas** [comment]
Hi @asturio 
Just to be sure to have expressed myself as I intended to, I was talking about removing deprecated functions.

**Comment by andreasrosdal** [comment]
There are now 92 warnings and 1 recommendation, and 0 errors.

https://lgtm.com/projects/g/LibrePDF/OpenPDF/alerts/?mode=list
