### ISSUE TITLE
HEIC image format support

### ISSUE THREAD

**Issue by andreasrosdal** [LibrePDF/OpenPDF#130]
https://en.m.wikipedia.org/wiki/High_Efficiency_Image_File_Format

for iOS.

**Comment by youyumeimei** [comment]
Hello @andreasrosdal , our group are interested in this issue, and we will try to fix it.
---- SE_SUSTech, group: Lanrand

**Comment by andreasrosdal** [comment]
See this issue: https://github.com/haraldk/TwelveMonkeys/issues/440
