### ISSUE TITLE
Since  1.2.0 loading Image with path/URL is not working

### ISSUE THREAD

**Issue by sjalouali** [LibrePDF/OpenPDF#133]
Hi, 

Since  1.2.0 loading Image with path/URL is not working.

For exemple : 
<img width="822" alt="capture d ecran 2019-01-14 a 15 13 16" src="https://user-images.githubusercontent.com/12748603/51117775-0214bb80-180f-11e9-8425-5af89b358093.png">

This code return this (in 1.1.0 version):

<img width="709" alt="capture d ecran 2019-01-14 a 14 53 50" src="https://user-images.githubusercontent.com/12748603/51121278-56239e00-1817-11e9-9b01-da480b171157.png">

 This code return this (Since 1.2.0 version):

<img width="372" alt="capture d ecran 2019-01-14 a 15 15 26" src="https://user-images.githubusercontent.com/12748603/51121306-69cf0480-1817-11e9-9d4a-a42584fb0a2d.png">

So the HtmlWorker no longer works correctly, when converting HTML to PDF that contains images.
<img width="796" alt="capture d ecran 2019-01-14 a 15 09 03" src="https://user-images.githubusercontent.com/12748603/51121991-15c51f80-1819-11e9-8434-fe832bbd1024.png">

Thanks for your help,
Samed

**Comment by andreasrosdal** [comment]
Thanks. Pull-requests welcome.

**Comment by andreasrosdal** [comment]
Please test OpenPDF 1.2.9 to see if this had been fixed. Thanks.

**Comment by sjalouali** [comment]
Thanks, it works perfectly !
