### ISSUE TITLE
How to edit text on a page

### ISSUE THREAD

**Issue by Kh4n** [LibrePDF/OpenPDF#147]
Is it possible to edit the text (not AcroForm data) of a PDF with OpenPDF? I have been trying to see ways to do it in the docs, but all I can do so far is parse the document.

**Comment by andreasrosdal** [comment]
https://medium.com/@sampathsl/changing-the-existing-text-in-a-pdf-d82a16219c5c

**Comment by Kh4n** [comment]
Ok I can see how it is done. A few questions:
1. I see that it is replacing the actual contents stream, and not modifying some sort of object. This means that whenever text is split up (eg. `[(Com)1.4 (put)-2 (e)0.6 (r)] TJ`) I have to manually change each segment. Is there a built-in way to handle this or do I just write it myself?
2. Where are most of the iText tutorials? Many are gone from the site (including this one).
3. Difference between stamper and writer?

**Comment by andreasrosdal** [comment]
There are at least two ways you could find the answer to this: hope that someone here happens to know the answer, OR you could put in the mental effort yourself to find the solution, and share the answers here. I dont know the answers, and this is a volunteer based community project. Good luck.

**Comment by Kh4n** [comment]
I suppose. Thanks for the help.

**Comment by zainabbasibs** [comment]
Hi, I have a .net core application having front end on angular. Now i have a list of documents and in each item i have pdf file path. Now i want to edit the pdf using any thirdparty library or plugin how can i do that. After editing the already existing text i want to save the updated file in same API
