### ISSUE TITLE
examples reference itextdocs.lowagie.com

### ISSUE THREAD

**Issue by GitMensch** [LibrePDF/OpenPDF#149]
See https://github.com/LibrePDF/OpenPDF/search?q=itextdocs.lowagie.com&unscoped_q=itextdocs.lowagie.com

I suggest to either replace it by:

* "was part of the 'iText tutorial' which you can find archived at http://web.archive.org/web/20090703162811/http://itextdocs.lowagie.com/tutorial"
* preferably: replace by a link to a new tutorial

**Comment by andreasrosdal** [comment]
Pull-requests welcome

**Comment by GitMensch** [comment]
I may find some time in the next 3 weeks to PR a change of all those occurrences to change the reference if you want me to.

So, are you fine with the following?

```diff
- * This code is part of the 'iText Tutorial'.
- * You can find the complete tutorial at the following address:
- * http://itextdocs.lowagie.com/tutorial/
+ * This code was part of the 'iText Tutorial'.
+ * You can find an archived version of the tutorial at the following address:
+ * https://web.archive.org/web/20090703162811/http://itextdocs.lowagie.com/tutorial/
```

and

```diff
- response.sendRedirect("http://itextdocs.lowagie.com/tutorial/general/webapp/index.html#HelloWorld");
+ response.sendRedirect("https://web.archive.org/web/20071005033458/http://itextdocs.lowagie.com:80/tutorial/general/webapp/index.html#HelloWorld");
```

**Comment by andreasrosdal** [comment]
Seems good. Thanks.

**Comment by andreasrosdal** [comment]
If you want to write a tutorial, that would be even better.

**Comment by andreasrosdal** [comment]
Please submit a pull-request to link here instead:  https://github.com/LibrePDF/OpenPDF/wiki/Tutorial

**Comment by andreasrosdal** [comment]
Fixed in https://github.com/LibrePDF/OpenPDF/commit/33a64afb63177463229c4289358e048b7bd95487
