### ISSUE TITLE
remove fork status

### ISSUE THREAD

**Issue by GitMensch** [LibrePDF/OpenPDF#150]
While there is no direct option to do this (that I'm aware of) you can write a request to the [GitHub spport](https://github.com/contact) stating that this is the active repository and they will remove the fork status.

**Comment by andreasrosdal** [comment]
I think I'll close this.

**Comment by GitMensch** [comment]
Can you please elaborate? Do you want to PR the changes of this "fork" back to rtfarte or the other way around and/or tell people to better fork from rtfarte and PR there instead of here?
Those are actually the main purposes of the GitHub fork status... You may want to have a look at [About forks][1]. They also have some features missing thought the most important (search) is working, but only [because this "fork" has more stars][2].
If this would be removed we wouldn't have the "This branch is 350 commits ahead, 2 commits behind rtfarte:master." note (which obviously only helps if the "upstream" [currently rtfarte] will have different commits and those from here included).

[1]:https://help.github.com/articles/about-forks/
[2]:https://help.github.com/articles/searching-in-forks/
