### ISSUE TITLE
Question/FR: Extract thumbnail

### ISSUE THREAD

**Issue by GitMensch** [LibrePDF/OpenPDF#151]
Is it possible to extract embedded thumbnails from PDF files (for the complete file / per page) or generate thumbnails?

**Comment by GitMensch** [comment]
If this is not possible I'd also would like to find a minimal alternative in Java (the current one is to use Apache PDFBox [which also needs Apache TextBox], but it is a lot of stuff and a duplicated PDF toolkit for just creating a thumbnail).

**Comment by andreasrosdal** [comment]
This csn be done using OpenPDF and Flyingsaucer, I would think.

**Comment by GitMensch** [comment]
Thank you for the note, but according to its docs http://flyingsaucerproject.github.ioi it can't process PDF - or did you meant to generate HTML + CSS from the PDF with OpenPDF first (if yes, how)?

**Comment by andreasrosdal** [comment]
You're right. You would probably need a PDF-renderer for this to work, something like Acrobat Reader, buy a libraru. So it is not possible. Closing.
