### ISSUE TITLE
Maintain Tutorial on Wiki

### ISSUE THREAD

**Issue by andreasrosdal** [LibrePDF/OpenPDF#152]
A tutorial for OpenPDF can be maintained here on the Wiki:
https://github.com/LibrePDF/OpenPDF/wiki/Tutorial

These are some sources for information about how to create such a tutorial:
https://github.com/ymasory/iText-4.2.0/tree/master/www/tutorial
http://web.archive.org/web/20090703162811/http://itextdocs.lowagie.com/tutorial/
#149 and #61.

**Comment by Doragon-S** [comment]
Can someone please add a Tutorial for making a Table and Placing it in a specific position in the pdf page? It would be very appreciated.

**Comment by flywire** [comment]
Tutorials should be implemented in https://jsfiddle.net/ or similar, even allow users to upload files and process them.

**Comment by sixdouglas** [comment]
Hi all,
It's been a long time since I've contributed here, and would be please to help improve documentation or samples.
How can I help you?

**Comment by andreasrosdal** [comment]
> Hi all, It's been a long time since I've contributed here, and would be please to help improve documentation or samples. How can I help you?

https://github.com/LibrePDF/OpenPDF/wiki/Tutorial  - This tutorial could be improved.

Pull requests to improve the JavaDoc in the code would be useful.

**Comment by sixdouglas** [comment]
What do you think about moving the sample classes to a dedicated maven module, in the same way other projects do?
This way it would be more visible.

**Comment by asturio** [comment]
Many sample classes are in the `pdf-toolbox` module. Contributing there is appreciated.

**Comment by asturio** [comment]
More and more examples should be added to `pdf-toolbox`. Additional info may be added by anyone in the Wiki.

**Comment by backsft** [comment]
not working for bengali font . bengali text is going broken.  there is no problem of my font. if anyone tried html to pdf or text to pdf anything let me know . here is the output : 
![1](https://github.com/user-attachments/assets/9fe905d0-5b01-4a8c-98a4-10bb55047901)

bengali font should display like  : 
![2](https://github.com/user-attachments/assets/5fb4f42d-c54f-4e66-a85e-682a7a2efe78)

i have tried all kind of tools over months same result

**Comment by sixdouglas** [comment]
Hi, @backsft 
Are you sure this comment is really related to this issue?
You should probably explain your issue more precisely and if you could provide a sample of code with the font you're using it would certainly be easier to investigate.

**Comment by backsft** [comment]
package com.OpenPDFBanglaFontTest.Another;
import com.lowagie.text.*;
import com.lowagie.text.pdf.PdfWriter;

import java.io.FileOutputStream;
import java.io.IOException;

public class HelloWorld {

    public static void main(String[] args) {

        // Register TrueTypeFont which supports Hindi
        FontFactory.register("C:\\Users\\kabir\\Desktop\\fonts\\TiroBangla-Regular.ttf");
        Document document = new Document();
        try {
            PdfWriter.getInstance(document,
                    new FileOutputStream("C:\\Users\\kabir\\Desktop\\HelloWorld.pdf"));

            document.open();
            document.add(new Chunk(
                    "আমাদের তরুণ বিপ্লবীরা দেশের মানুষের মনে নতুন বাংলাদেশ গড়ার যে স্বপ্ন জাগিয়ে দিয়েছে",
                    FontFactory.getFont("TiroBangla-Regular", "Identity-H",false,14,2,null)));
        } catch (DocumentException de) {
            System.err.println(de.getMessage());
        } catch (IOException ioe) {
            System.err.println(ioe.getMessage());
        }
        document.close();

    }
}  output came: 
![output](https://github.com/user-attachments/assets/91df6158-8f9c-406e-ac7f-b62298bc1f99)

expected result should be : আমাদের তরুণ বিপ্লবীরা দেশের মানুষের মনে নতুন বাংলাদেশ গড়ার যে স্বপ্ন জাগিয়ে দিয়েছে
