### ISSUE TITLE
I made a quick logo, is it okay?

### ISSUE THREAD

**Issue by bengolder** [LibrePDF/OpenPDF#16]
@andreasrosdal I made a logo for [LibrePDF](//github.com/LibrePDF). I didn't spend much time on it. I just wanted the account to look a little better than the default generated image.

Is it okay? I'm happy to remove it or make _minor_ adjustments if not.

![librepdf logo](https://cloud.githubusercontent.com/assets/451510/22400667/2dc9e0c6-e570-11e6-8230-9c5c97676c46.png)

**Comment by andreasrosdal** [comment]
Look good
