### ISSUE TITLE
com.lowagie.text.pdf.ExtendedColo Class not found issue 

### ISSUE THREAD

**Issue by niosdeveloper** [LibrePDF/OpenPDF#167]
re-init on previously-failed class java.lang.Class<com.lowagie.text.pdf.ExtendedColor>: java.lang.NoClassDefFoundError: Failed resolution of: Ljava/awt/Color;

**Comment by andreasrosdal** [comment]
Hello @niosdeveloper  Can you please give us more information? 
How do you get this error? Share some source code, please.

**Comment by niosdeveloper** [comment]
Hello @andreasrosdal Thank you for your response. 

App.gradle 
-  minSdkVersion 19
dependencies{
    implementation 'com.github.librepdf:pdf-html:1.2.11'
}

Rectangle.Java-> **java.awt.Color**-> Cannot resolve symbol `Color`
![image](https://user-images.githubusercontent.com/25150469/55392017-163b9f80-5558-11e9-8ae7-31fad4cd0496.png)

**Comment by andreasrosdal** [comment]
Is this on Android?

**Comment by niosdeveloper** [comment]
Yes

**Comment by andreasrosdal** [comment]
OpenPDF doesn't support Android yet. Please see this:  https://github.com/LibrePDF/OpenPDF/issues/118

**Comment by niosdeveloper** [comment]
@andreasrosdal Can you help me to find best PDF print lib for android.
