### ISSUE TITLE
Add support for very large PDF files

### ISSUE THREAD

**Issue by wil-everlaw** [LibrePDF/OpenPDF#182]
https://itextpdf.com/en/resources/faq/technical-support/itext-5-legacy/what-size-limit-pdf-file

It looks like OpenPDF is forked from a version of iText before they made the change from int byte offsets to long byte offsets, which allows the library to work with PDFs greater than 2GB.  We sometimes run into situations where we need to write PDFs larger than that size.  Is this a problem that has been addressed in OpenPDF or one that could be addressed by changing ints to longs?

**Comment by andreasrosdal** [comment]
I think the 2gb limitation is still in OpenPDF. Pull requests welcome.

**Comment by andreasrosdal** [comment]
This is relevant: https://github.com/itext/itextpdf/commit/e8425d367633fba3d86db3c52fca063695e5b497

**Comment by andreasrosdal** [comment]
@wil-everlaw Can you please submit enough information to reproduce this problem?

**Comment by wil-everlaw** [comment]
@andreasrosdal From what I understand in terms of reproducing this issue, attempting to generate a PDF with size greater than 2GB using PdfWriter will result in a PDF with broken xrefs due to integer overflow.

**Comment by andreasrosdal** [comment]
This Java code allows creating a PDF file which is 12GB. 

So I assume that this 2GB limit is related to using "cross-reference streams" in PDF versions 1.5? How do I enable cross-reference streams?

```
package com.lowagie.text.pdf;

import com.lowagie.text.Document;
import com.lowagie.text.Image;
import com.lowagie.text.Paragraph;
import org.junit.jupiter.api.Test;

public class LargePdfTest {

    @Test
    void testSimplePdf() throws Exception {
        // create document
        Document document = PdfTestBase.createPdf("testLargePdf");
        try {
            // new page with a rectangle
            document.open();
            document.newPage();
            String longString = "Hello Very Large World";
            for (long i = 0; i < 10; i++) {
                longString += longString;
            }

            for (long i = 0; i < 120000; i++) {
                Image jpg = Image.getInstance("../pdf-toolbox/src/test/java/com/lowagie/examples/objects/images/sunflower-back.jpg");
                document.add(jpg);
                document.add(new Paragraph(longString));
            }


        } finally {
            // close document
            if (document != null)
                document.close();
        }

    }

}

```


@wil-everlaw How do I reproduce the problem you are having?

**Comment by andreasrosdal** [comment]
I have just tested writing a new PDF of 13 GB, and that works correctly.

In order to read PDF files larger than 2GB, RandomAccessFileOrArray needs to be updated,
and the xref logic needs to be updated to use long instead of int.

**Comment by andreasrosdal** [comment]
I added a test for large PDF files here: https://github.com/LibrePDF/OpenPDF/commit/c77a03bec1fb766438ee1534de68d11687c93910

**Comment by andreasrosdal** [comment]
2GB should be enough for anyone.

**Comment by wil-everlaw** [comment]
We often run into extremely large document image files that are provided to us by users that need to be converted to PDF in certain use cases.  These can exceed 2GB.  As much as I agree that that is an absurd size for a PDF, it does happen.

**Comment by wil-everlaw** [comment]
@andreasrosdal Closing this now that a pr has been merged.  Thank you for your help.
