### ISSUE TITLE
Automatic-Module Names broken for certain JARs

### ISSUE THREAD

**Issue by ctolkmit** [LibrePDF/OpenPDF#184]
pdf-html-1.2.16.jar specifies Automatic-Module-Name: com.github.librepdf.pdf-html
pdf-xml-1.2.16.jar specifies Automatic-Module-Name: com.github.librepdf.pdf-xml

As Module-Names are PackageOrTypeNames, the allowed characters in are strictly limited to those in Identifiers and "." (dot) as Separator. (ref. Section 3.8 of Java Specification). 
Thus, using a dash ("-") in the name is explicitely forbidden and will lead to compilation errors, if the module name is used.

**Comment by andreasrosdal** [comment]
Fixed in https://github.com/LibrePDF/OpenPDF/commit/aef1d4966b11da93493a7b7e696445d16f34414e

Thanks for reporting this. Can you please verify that the solution solved your problem?

**Comment by ctolkmit** [comment]
@andreasrosdal The generated artifacts (jars/modules) look fine now. Sadly, unless #185 is fixed as well, I cannot test this in my code. 
As a workaround, I am currently building a shadow-jar that contains all my needed OpenPDF-Classes and writes an own manifest.
