### ISSUE TITLE
Module / Split Package Issue with pdf-xml

### ISSUE THREAD

**Issue by ctolkmit** [LibrePDF/OpenPDF#185]
Both the JAR pdf-xml and  openpdf contain a package com.lowagie.text.pdf and com.lowagie.text.xml
This is not allowed in a modular/jigsaw context, unless you use the strongly discouraged patching mechanisms.

**Comment by andreasrosdal** [comment]
How do you propose we fix this, without breaking the exisiting API?
Merge pdf-xml into openpdf?

**Comment by ctolkmit** [comment]
You could in theory merge all jars that contain the same package into one. (I think, there is the same issue
Then you would only have a single module (Sadly, you cannot have multiple Modules in a single JAR) and thus only a single module name.

There are other occurrences of the same problem in the project, as I see:

I use the following command to find the packages used by each jar/module and inspect the (not too long result) manually:

    find */src/main/java -type f -name "*.java" -exec dirname {} \; | sed -E -e 's,^([^/]*).*main/java/,\1 - ,' | uniq | sort -k 2 | uniq |  sed -e 's,/,.,g'

The following packages are split:

* com.lowagie.text.html both in openpdf and pdf-html
* com.lowagie.text.pdf both in openpdf and pdf-xml
* com.lowagie.text.xml both in openpdf and pdf-xml

So, the easiest would probably be to combine openpdf, pdf-html, pdf-xml into a single artifact if you do not want to break external API

**Comment by andreasrosdal** [comment]
@daviddurand @rtfarte @asturio @albfernandez What do you think of this?

**Comment by andreasrosdal** [comment]
There is a proposal to fix this here:  https://github.com/LibrePDF/OpenPDF/pull/187

**Comment by andreasrosdal** [comment]
@Lonzak

**Comment by andreasrosdal** [comment]
@ctolkmit Can you please verify that this is working as you expect now?

**Comment by ctolkmit** [comment]
@andreasrosdal With openpdf-1.2.17-SNAPSHOT built from the current master, everything is fine in my build/runtime now
