### ISSUE TITLE
Java 7

### ISSUE THREAD

**Issue by luberti** [LibrePDF/OpenPDF#188]
I see in github that there is a java7 branch.
How is that stable?
Ar there jar files available? 

Thanks for your work and 
thanks in advance your answer

**Comment by andreasrosdal** [comment]
I suggest you try one of these two releases of OpenPDF for Java 7 support:
https://github.com/LibrePDF/OpenPDF/releases/tag/1.2.3.java7
https://github.com/LibrePDF/OpenPDF/releases/tag/1.0.5

The Java 7 branch is currently unmaintained. See issue #146.

**Comment by andreasrosdal** [comment]
@luberti I could add support for Java 7 again, and maintain the Java 7 branch, for a fee where your company pays me to do the development work. Contact me if this is of interest to you.
