### ISSUE TITLE
Some input files use or override a deprecated API

### ISSUE THREAD

**Issue by ghost** [LibrePDF/OpenPDF#19]
I get these warnings of "Some input files use or override a deprecated API" when compiling the latest version of OpenPDF:

[INFO] --- maven-compiler-plugin:3.2:compile (default-compile) @ openpdf ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 344 source files to C:\Users\andreas\librepdf\OpenPDF\openpdf\target\classes
[INFO] /C:/Users/andreas/librepdf/OpenPDF/openpdf/src/main/java/com/lowagie/text/pdf/PdfPKCS7.java: Some input files use or override a deprecated API.
[INFO] /C:/Users/andreas/librepdf/OpenPDF/openpdf/src/main/java/com/lowagie/text/pdf/PdfPKCS7.java: Recompile with -Xlint:deprecation for details.
[INFO] /C:/Users/andreas/librepdf/OpenPDF/openpdf/src/main/java/com/lowagie/text/pdf/PdfReader.java: Some input files use unchecked or unsafe operations.
[INFO] /C:/Users/andreas/librepdf/OpenPDF/openpdf/src/main/java/com/lowagie/text/pdf/PdfReader.java: Recompile with -Xlint:unchecked for details.

**Comment by andreasrosdal** [comment]
X509CertParser is deprecated. 

https://github.com/LibrePDF/OpenPDF/blob/master/openpdf/src/main/java/com/lowagie/text/pdf/PdfPKCS7.java#L444

"@deprecated use CertificateFactory or the PEMParser in the openssl package (pkix jar)."
https://github.com/bcgit/bc-java/blob/master/prov/src/main/java/org/bouncycastle/jce/provider/X509CertParser.java

**Comment by tlxtellef** [comment]
- [ ]  `org.bouncycastle.asn1.x509.TBSCertificateStructure` in `org.bouncycastle.asn1.x509` has been deprecated
  - [ ]  `com/lowagie/text/pdf/PdfPublicKeySecurityHandler.java:[125,34]`
  - [ ]  `com/lowagie/text/pdf/PdfPKCS7.java:[106,34]`
- [ ]  `org.bouncycastle.jce.provider.X509CertParser` in `org.bouncycastle.jce.provider` has been deprecated
  - [ ]  `com/lowagie/text/pdf/PdfPKCS7.java:[112,37]`
- [ ]  `org.bouncycastle.crypto.engines.AESFastEngine` in `org.bouncycastle.crypto.engines` has been deprecated
  - [ ]  `com/lowagie/text/pdf/crypto/AESCipher.java:[52,39]`
- [ ]  `getArrayList()` in `com.lowagie.text.pdf.PdfArray` has been deprecated
  - [ ]  `com/lowagie/text/pdf/PdfPages.java:[144,42]`
  - [ ]  `com/lowagie/text/pdf/PdfReader.java:[2295,38]`
  - [ ]  `com/lowagie/text/pdf/PdfReader.java:[2305,30]`
  - [ ]  `com/lowagie/text/pdf/PdfReader.java:[2389,42]`
  - [ ]  `com/lowagie/text/pdf/PdfReader.java:[3193,32]`
  - [ ]  `com/lowagie/text/pdf/PdfStructureTreeRoot.java:[121,61]`
  - [ ]  `com/lowagie/text/pdf/PdfStructureTreeRoot.java:[123,29]`

**Comment by asturio** [comment]
I'm working on com/lowagie/text/pdf/PdfPKCS7.java. Please note, that this warnings come after we added the lint flag to the compiler, which has a much aggressive behavior.

**Comment by tlxtellef** [comment]
@asturio Yes, I used `-Xlint:deprecation` to create that list.
