### ISSUE TITLE
Try-with-resources not working properly

### ISSUE THREAD

**Issue by tipenull** [LibrePDF/OpenPDF#197]
We recently updated some of our code using OpenPDF to managing AutoClosable resources with try-with-resources.

In this case a PdfWriter is created for a Document, both of which are managed using try-with-resources. However, closing the PdfWriter before the Document seems to cause a problem.

Is this setup not working properly with try-with-resources deliberate?

This is the (not exactly expressive) exception we're getting:
`Caused by: ExceptionConverter: java.io.IOException: Stream Closed`

Here's the affected code:

        final List<PdfReader> pdfFileReaders = new ArrayList<>();

        for (final var file : fileList) {
            @SuppressWarnings("resource") final var reader = new PdfReader(file.getAbsolutePath());
            pdfFileReaders.add(reader);
        }

        try (final Document doc = new Document()) { // A4 default
            setDocument(doc);
            outputFile = FileUtil.createTempFile();
            final File file1 = outputFile;
            try (final FileOutputStream os = new FileOutputStream(file1);
                    final PdfWriter writer = PdfWriter.getInstance(doc, os)) {
                doc.open();
                final PdfContentByte cb = writer.getDirectContent();

                for (final var pdfReader : pdfFileReaders) {
                    doc.newPage();
                    final var page = writer.getImportedPage(pdfReader, 1);
                    cb.addTemplate(page, 1, 0, 0, 1, 0, 0);
                }

            }
        } finally {
            for (final var pdfReader : pdfFileReaders) {
                try {
                    pdfReader.close();
                } catch (final RuntimeException e) {
                    LOGGER.warn("failed to close pdf reader: " + e.getMessage(), e);
                }
            }

            for (final File oldFile : fileList) {
                LOGGER.trace("Deleting temporary file: " + oldFile);
                if (oldFile.exists() && !oldFile.delete()) {
                    LOGGER.warn("Could not delete file " + oldFile);
                }
            }
            fileList.clear();
        }

**Comment by andreasrosdal** [comment]
@wiktor-k

**Comment by wiktor-k** [comment]
To be honest I've seen this exception before and I had a couple of ideas where to fix it but ultimately I wasn't sure which one is the best (good?) approach.

The issue stems from intricate interactions of PdfWriter/DocWriter/Document closing themselves.

I attached a PR that just checks if a Document object is closed and if so does nothing. That fixes the small repro code I've added.

It would be good if you @tipenull could test PR #198 and report if it fixes it in your case too (I tried to extract more code from your example but it references variables out of scope).

**Comment by mkl-public** [comment]
The original iText usage pattern was to *not* close the writer oneself but instead let it be closed via closing the document.
Thus, the writer indeed should neither be explicitly closed nor be used as a resource of a try-with-resource structure.
Whether there actually can be something missing if you first close the writer, then the document, I have not checked in the code, but it is possible by the design.
As a corollary the fix in #198 might simply stop throwing the exception while at the same time some issue is in the result PDF.
