### ISSUE TITLE
Duplicate entry

### ISSUE THREAD

**Issue by MartinKocour** [LibrePDF/OpenPDF#21]
Hi,

it looks like XmlDomWriter in openpdf dependency is the same as XmlDomWriter in pdf-xml dependency.
Both of them has same package name and also content. 
I have a dependency on pdf-html sources in my android procject.
`compile 'com.github.librepdf:pdf-html:1.0.1'`
When i try to build my project i get 
```
Error:Execution failed for task ':touchPoApp:transformClassesWithJarMergingForTstingDebug'.
> com.android.build.api.transform.TransformException: java.util.zip.ZipException: duplicate entry: com/lowagie/text/xml/XmlDomWriter.class
```

**Comment by andreasrosdal** [comment]
Hi Martin,  could you please submit a pull-request for this?

Andreas

**Comment by andreasrosdal** [comment]
Thanks. I have merged your pull-request.
