### ISSUE TITLE
Clean metadata patch only hide metadata instead of removing

### ISSUE THREAD

**Issue by albfernandez** [LibrePDF/OpenPDF#215]
The pull Request #179 tries to clean metadata from resulting pdf files. It only hides from view in "properties" in pdf viewers, but the metadata is hidden in the file and can be viewed via text editor.

**Comment by andreasrosdal** [comment]
Is this still relevant?

**Comment by albfernandez** [comment]
Yes, it's closed in #230, so I close this issue.
