### ISSUE TITLE
Should metadata be cleaned or maintained by default in pdfstamper?

### ISSUE THREAD

**Issue by albfernandez** [LibrePDF/OpenPDF#216]
The Pull Request #179 clean metadata from resulting pdf files by default.

As noted by @ngs-software, it can cause issues as changes default behavior and some software need the metadata (for indexing purposes)

We have been experiencing issues when signing documents with keywords/metadata previously injected in a document, as these become inaccessible through API after document is stamped.

As far as we have seen, this is due to this pull request, as it make keywords hidden when stamping, removing  references to existing kewords in the document (event if the actual keywords content is still present inside it - can be seen with a regular text editor).

We'd like to know what is the purpose of this modification, and if it responds to any compliance or standard rule we don't know about. From our point of view, metadata cleanup should be offered and some kind of utility helper/class to be used only when required as part of external business logic requirements, and not as a default behavior, as it may be required later for multiple purposes.

We include for your examination 3 pdf files:

- Original File with metadata keywords added to it, that can be seen from Reader application.
- File resulting from signing original file through a unit test with OpenPDF 1.2.15, where metadata is still visible from Reader application.
- File resulting from signing original file through the same unit test with OpenPDF 1.2.16, where metadata disappears from Reader application (but can be seen in document through text editor).

From this analysis, we believe that this modification should be rolled-back and 'refactored' to a helper method that, by the way, should perform a complete cleanup of keywords, in case that's the actual requirement, as in current approach, apart of deleting existing information of original document without request from outer application, it only makes it hidden (but still present in pdf's raw contents).

Looking forward to your comments and considerations,

Best Regards,
ngs

[signed-with-1.2.15.pdf](https://github.com/LibrePDF/OpenPDF/files/3451046/signed-with-1.2.15.pdf)
[signed-with-1.2.16.pdf](https://github.com/LibrePDF/OpenPDF/files/3451047/signed-with-1.2.16.pdf)
[original.pdf](https://github.com/LibrePDF/OpenPDF/files/3451048/original.pdf)

_Originally posted by @ngs-software in https://github.com/LibrePDF/OpenPDF/pull/179#issuecomment-516783017_

**Comment by andreasrosdal** [comment]
What is your recommendation, @albfernandez @asturio ? The proposal from @ngs-software seems sane, can we make a PR for this?

**Comment by asturio** [comment]
I think the expectation described by @ngs-software is correct. When creating a new document, I would expect of having empty fields.
When signing a document I would not expect to have the meta-data hidden or erased. I would also have the case, where I would expect seeing the original meta-data as part of the signed document, so I can see author, and date of a signed document.

A totally agree, that **erasing** meta-data should be done in an utility method, called this way. And the extra call of this method before signing is explicit at the user side.
`eraseMetaData(document);`
`signDocument(document)`

**Comment by albfernandez** [comment]
I've created a Pull request which partially reverts #179 
the documents are created with no metadata(only the metadata specified by the calling code).
On stamper, metadata is preserved. If you want to remove the metadata, you must call cleanMetadata:
```java 
private byte[] cleanMetadata(File origin) throws Exception {
    ByteArrayOutputStream baos = new ByteArrayOutputStream();
    PdfReader reader = new PdfReader(origin.getAbsolutePath());
    PdfStamper stamp = new PdfStamper(reader, baos);
    stamp.cleanMetadata();
    stamp.close();
    return baos.toByteArray();
}
```

cleanMetadata call setInfoDictionary with a special Map with all keys in metadata and null values, who forces the stamper to remove this keys from metadata.

The pull request preserve xmp metadata, maybe in a second PullRequest will remove it if cleanMetadataMethod is called
