### ISSUE TITLE
Compilation error: The default package '.' is not permitted by the Import-Package syntax.

### ISSUE THREAD

**Issue by andreasrosdal** [LibrePDF/OpenPDF#229]
I get this build error on the latest git master branch:

[ERROR] Manifest com.github.librepdf:openpdf:jar:1.3.2-SNAPSHOT : The default package '.' is not permitted by the Import-Package syntax.
 This can be caused by compile errors in Eclipse because Eclipse creates
valid class files regardless of compile errors.
The following package(s) import from the default package null
[ERROR] Error(s) found in manifest configuration
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] OpenPDF - Free and Open PDF 1.3.2-SNAPSHOT ......... SUCCESS [  2.663 s]
[INFO] openpdf ............................................ FAILURE [ 20.488 s]
[INFO] pdf-swing .......................................... SKIPPED
[INFO] pdf-toolbox 1.3.2-SNAPSHOT ......................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 24.349 s
[INFO] Finished at: 2019-08-12T07:26:45+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.felix:maven-bundle-plugin:3.2.0:manifest (bundle-manifest) on project openpdf: Error(s) found in manifest configuration -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :openpdf

**Comment by sixdouglas** [comment]
@andreasrosdal : I'm sorry if I broke anything.
Do you try to launch Maven build from within Eclipse?
Can you explain me with a little more details what you attempted to do?

**Comment by andreasrosdal** [comment]
@sixdouglas I don't think this is caused by your changes. Still, I'm not sure why this has happened. Building on Travis-CI works fine. Maybe there is something on my system?

**Comment by andreasrosdal** [comment]
I deleted some unversioned files on my system ,and now it builds correctly. Sorry about this.

**Comment by KurtTrentch** [comment]
what were the files @andreasrosdal ?
