### ISSUE TITLE
Limited functionality under Google App Engine

### ISSUE THREAD

**Issue by Radagan** [LibrePDF/OpenPDF#23]
Hi, is there a way to get rid of the dependency on java.awt.Color? It's not white listed on GAE, so setting cell colors, etc. will not work. This library is amazing otherwise. I've tried PDFBox and it is years from where this library is.

**Comment by andreasrosdal** [comment]
Hi! Yes, this is possible. Can you please submit a pull-request for this?

**Comment by Radagan** [comment]
Hi Andreas,

I must be doing something wrong... When I press "New Pull Request" it sends me here:

![screen shot 2017-03-09 at 9 45 55 am](https://cloud.githubusercontent.com/assets/648226/23729427/7eef33d2-04ad-11e7-9a4e-b1cc85ef09dd.png)

Happy to do what I can if you'll point me in the right direction.

**Comment by andreasrosdal** [comment]
Hi!

Here is a suggestion:
1. Propose a suggestion about how you suggest you change OpenPDF to work on Google App Engine in this issue. It would be very nice to have OpenPDF working on GAE! However, I don't think we should break the API for existing users of OpenPDF. How can we solve this? Perhaps create a different branch of OpenPDF with java.awt.Color replaced with our own Color class?

2. Then create a fork of /LibrePDF/OpenPDF on github.com/Radagan
3. Then click "pull request" on github.com/Radagan



Andreas

**Comment by Radagan** [comment]
Thanks, Andreas. 

I confess this is the first time I’ve ever contributed to an open source project, much less on GitHub. This should be fun!

I’ll do as you suggest. I suffered with the state of PDFBox up close for a few days, and then found your fork of the old LGPL version of iText. Our company would happily buy iText if they had anything close to a normal software license agreement, but it’s more complex than the current US Tax code. Crazy. 

OpenPDF must not die.

I’ve been coding Java for a couple decades and I’ve got more than a little vested interest in it working on GAE. Thank you for being open to my making a contribution.

Fortunately, it’s working under GAE now so long as you don’t mess with colors. But colors would be nice to have, and there may be other GAE particulars I can help with.

Kind regards,

Rolf
 

Rolf Hunt
Chief Technology Officer
w 2 9504 6000   m 0434 003 245
 <http://www.logicalgroup.net/>
 
 <http://buildingpulse.logicalbuilding.com.au/> <http://afterhours.logicalbuilding.com.au/>

**Comment by andreasrosdal** [comment]
This sounds like a good plan. Your contributions will be very welcome!

**Comment by andreasrosdal** [comment]
Hi again Rolf,

If you are interested, then I could implement this functionality for you as a contracting job.
You could specify the requirements for the functionality you need. The result would be included in OpenPDF. Contact me directly on  andreas.rosdal@gmail.com if this is of interest to you.

Regards,
Andreas

**Comment by jeeban13** [comment]
How to use openPDF object in vbscript and C# because customer installed openPDF software to view and edit pdf files

**Comment by andreasrosdal** [comment]
@Radagan  Any news on this issue?

**Comment by Radagan** [comment]
@Andreas. With Google releasing the flexible environment, this is less of an issue. The library works under standard so long as you don’t use the color methods, and under flexible there are not restrictions. So, I would close the feature request as no longer needed. Even with a standard app engine project, one should be able to break the pdf portion off into a micro-service running under flexible and use all of the features of LibrePDF as written.
