### ISSUE TITLE
Text is not rendered with specific font

### ISSUE THREAD

**Issue by fono** [LibrePDF/OpenPDF#231]
OpenPDF 1.3.2 introduced a new issue: some texts are not rendered. As far as I can see it is font related, I have just experienced the bug only with Roboto. It worked fine with 1.3.1.

I have created a simple test to reproduce the issue:
https://github.com/fono/openpdf-test-image

See `TextTest.testGenerateText()` test (sorry for the lame assert for (not) finding the rendered text...). This test writes text with Roboto font in a PDF and saves it. Using OpenPDF 1.3.2 the result PDF if empty, with 1.3.1 the text is rendered properly.

**Comment by fono** [comment]
Git bisect tells me that the bug was introduced by the commit b8fa1a9c5e0d4d58d74545061ea300070bcee6b2, however, reverting that commit has no effect on the result of the test.

**Comment by andreasrosdal** [comment]
Thanks fono! I guess it's the price of progress.
Can you please help make a fix?

**Comment by andreasrosdal** [comment]
@sixdouglas Can you also please help investigate?

**Comment by sixdouglas** [comment]
@andreasrosdal , @fono I'm looking at it

**Comment by sixdouglas** [comment]
@andreasrosdal : here is the fix

**Comment by andreasrosdal** [comment]
Thanks to you both. Can you please give OpenPDF 1.3.3 a try, and verify that everything works correctly now?

**Comment by fono** [comment]
Thank you, I confirm this works properly.
