### ISSUE TITLE
Internationalization support ( Cyrillic, Chinese....)

### ISSUE THREAD

**Issue by dprutean** [LibrePDF/OpenPDF#239]
I use openPdf to generate diagrams. Users can be from any country. Which is the recommended way to support major charachter sets (at least cyrillic, chinese, japonese ) ? 

I saw few examples of embedding the arialuni.ttf, but maybe is any other simple way to do it?

**Comment by sixdouglas** [comment]
Hello,
You have an example of Arabic in this sample `/pdf-toolbox/src/test/java/com/lowagie/examples/directcontent/graphics2D/ArabicText.java`.

**Comment by sixdouglas** [comment]
@dprutean: does this answer your question or do you need something more general?

**Comment by andreasrosdal** [comment]
Maybe we could add a Cyrillic / Russian example? I would like that a lot.

**Comment by dprutean** [comment]
I tried to use the following code. If possible please review this code:

First I try to scan the text to check if is using non-latin characters (need unicode font):

```
public boolean useUnicodeFont( String text ){
        if ( text != null ) {
            final StringCharacterIterator iterator = new StringCharacterIterator(text);
            char character = iterator.current();
            while (character != CharacterIterator.DONE) {
                if ( character != '\r' && Character.UnicodeBlock.of(character) != Character.UnicodeBlock.BASIC_LATIN) {
                    return true;
                }
                character = iterator.next();
            }
        }
        return false;
    }
```

If I need an unicode font I do:

```
if ( useUnicodeFont ){
    FontFactory.register( pathToUnicodeFont, "Unicode");
}

public Font getFont( float size, int bold, Color color ){
   return useUnicodeFont ? FontFactory.getFont("Unicode", BaseFont.WINANSI, true, size, bold, color ) : new Font(Font.HELVETICA, size, bold, color );
}

public BaseFont getBaseFont() throws IOException {
    return useUnicodeFont ?
           BaseFont.createFont( LOCAL_FONT_FILE.getAbsolutePath(), BaseFont.IDENTITY_H, BaseFont.EMBEDDED) :
            BaseFont.createFont( BaseFont.HELVETICA, BaseFont.WINANSI, false);
}
```

This can be used in tables or any text:
```
PdfPCell cell = new PdfPCell(new Phrase(text, getFont( 10, bold ? Font.BOLD : Font.PLAIN, Color.BLACK )));
```

and direct drawing:
```
pdfContentByte.setFontAndSize( getBaseFont(), 12 );
```
The font ttf file I found has cyrillic andd chinese glyphs. It is 15Mbyte large.
I expected the Pdf file to become also 15Mb large, but wasn't like this. Does Pdf include only the used glyphs ?

[Sample Pdf](https://www.dbschema.com/test2.pdf)

**Comment by asturio** [comment]
Hi @dprutean ,
As far as I know, you can create PDF without embedding Fonts, which is not Portable, as the document will only display correctly if the needed font is present in the viewing system.
When embedding fonts PDF will only to this, embedding the used glyphs, as there may be legal issues using a font.
The logic is: if you embed all the complete font, someone could just extract it from the PDF-document, and start using a font, he doesn't have the license to use. Embedding just the used glyphs, is normally what is permitted by the common licenses.
This of course is not bullet-proof, as you can simply generate a PDF containing all glyphs if a font.

**Comment by asturio** [comment]
Oh, and there is a small Example using the included Liberation-Font (which should be Unicode-capable) here:
openpdf/src/test/java/com/lowagie/text/pdf/UnicodePdfTest.java

Just use the same font, and you should create documents using Greek or Cyrillic symbols.

**Comment by asturio** [comment]
I just wrote some more examples for Cyrillic and Greek. Please see take a look at:

openpdf/src/test/java/com/lowagie/text/pdf/GreekAndCyrillicTest.java

Your posted code is interesting, but I think, you shouldn't need to detect if the text contains unicode characters. Just use a Font that support Unicode always, and everything should be correct. I can't see why anybody should use non-unicode fonts at all, for normal text.

@dprutean: Does this solve your question?
