### ISSUE TITLE
Nullpointer on Font create

### ISSUE THREAD

**Issue by renierr** [LibrePDF/OpenPDF#24]
in class: BaseFont
Line: 856

You always get null if you do not cache the font (cache = false).
Lines before will put it inside the cache.
You just habe to return the var here.

**Comment by andreasrosdal** [comment]
Hi! Do you have a suggestion about how to fix this? Can you submit a pull-request?

**Comment by renierr** [comment]
Yes, change this (i do not have an own fork):

		if (cached) {
			fontCache.putIfAbsent(key, fontBuilt);
		}
		return fontCache.get(key);

to:

		if (cached) {
			fontCache.putIfAbsent(key, fontBuilt);
                        return fontCache.get(key);
		}
               return fontBuilt;

A more detailed explanation is:
When you pass 'false' to the cached parameter, you never fill the cache, so getting the return value from cache will always return null, even so you already have the return value inside the fontBuilt variable.

This will always result in a Nullpointer if you use Flying saucer and declare a 'font-face' in your HTML to render as PDF, cause flying saucer will always pass 'false' as cached value.

**Comment by andreasrosdal** [comment]
Thanks. Can you please submit a pull-request for this?

**Comment by renierr** [comment]
Is there a plan to make a patch relase for this?
All flying saucer users who generates via OpenPdf and define own fonts will have this issue.
Or all that uses Fonts withtout cache

**Comment by andreasrosdal** [comment]
@bengolder Maybe you can please do your release magic and create a new release?
