### ISSUE TITLE
Convert PDF to image

### ISSUE THREAD

**Issue by andreasrosdal** [LibrePDF/OpenPDF#249]
Support for converting PDF to image would be nice.

JPedal has this: https://www.idrsolutions.com/jpedal/convert-pdf-to-image/

**Comment by Lonzak** [comment]
Jpedal is not the way to go, believe me. I maintain one of the forks of the last open source version of jpedal (https://github.com/Lonzak/JPedal) and we used it for years in our products. But we recently switched to PdfBox for PDF to image conversion. We did heavy testing with over 400+ PDFs and compared the results. Altough PdfBox is not perfect the results were quite clear: Jpedal image conversion is not to be used anymore... Besides there is no open source version anymore. (and maybe the commercial version has improved in that matter)

**Comment by Lonzak** [comment]
But I didn't want to stall the discussion ;-)
