### ISSUE TITLE
Producer value gets scambled

### ISSUE THREAD

**Issue by debuglevel** [LibrePDF/OpenPDF#254]
I'm filling a PDF form ([PDF form.zip](https://github.com/LibrePDF/OpenPDF/files/3612627/PDF.form.zip), created with LibreOffice 6.0) with OpenPDF and noticed that the "Producer" value in the PDF gets scrambled after OpenPDF 1.3.8/PdfStamper processing (at least for my sample PDF):

![Producer before](https://user-images.githubusercontent.com/2401265/64907081-66658300-d6ee-11e9-9427-a8881ad81d20.png)
```
19 0 obj
<</Creator<FEFF005700720069007400650072>
/Producer<FEFF004C0069006200720065004F0066006600690063006500200036002E0030>
/CreationDate(D:20190913224645+02'00')>>
endobj
```

becomes
![Producer after](https://user-images.githubusercontent.com/2401265/64907080-66658300-d6ee-11e9-8731-a4cee4219cf0.png)
```
19 0 obj
<</Creator<feff005700720069007400650072>/ModDate(D:20190913234441+02'00')/CreationDate(D:20190913224645+02'00')/Producer(þÿLibreOffice 6.0; modified using OpenPDF 1.3.8)>>
endobj
```

**Comment by andreasrosdal** [comment]
@debuglevel Can you please confirm that this has been fixed in the latest git master branch version?

**Comment by debuglevel** [comment]
Cool, works perfectly :-). Thank you and @albfernandez very much!

![image](https://user-images.githubusercontent.com/2401265/64913294-95efac00-d73d-11e9-98a7-86731bc759c3.png)

I tested it with the 'com.github.LibrePDF.OpenPDF:openpdf:6ceda3dec2' dependency via [JitPack](https://jitpack.io/#LibrePDF/OpenPDF/6ceda3dec2)
