### ISSUE TITLE
Incorrect buttom height calculation in table cell

### ISSUE THREAD

**Issue by rammetzger** [LibrePDF/OpenPDF#258]
For long texts (more than one page) within a table cell, it can happen that a line is printed twice. One time on the last page and one time on the next. The cause is an incorrect calculation of the available cell height.

The bug is in the calculation of cell height in class PdfPRow on lines 609-612:
```
float bottom = cell.getTop() + cell.getEffectivePaddingBottom() - newHeight;
float top = cell.getTop() - cell.getEffectivePaddingTop();
```
The bottom value does not consider EffectivePaddingTop. The code should look something like this:
```
float top = cell.getTop() - cell.getEffectivePaddingTop();
float bottom = top + cell.getEffectivePaddingBottom() - newHeight;
```

Please take over the correction in one of the next versions.
Thanks in advance.

**Comment by andreasrosdal** [comment]
https://github.com/LibrePDF/OpenPDF/blob/master/openpdf/src/main/java/com/lowagie/text/pdf/PdfPRow.java#L609

Pull requests welcome!

**Comment by PalAditya** [comment]
Added a PR (#260) to help out with this 😁

**Comment by andreasrosdal** [comment]
@rammetzger Can you please verify that this has been fixed in the master branch?

**Comment by rammetzger** [comment]
Hi Andreas,

the bug seems to be fixed. I can’t reproduce it any more.

Thanks for the quick fix.

Viele Grüße / Best regards
Michael Metzger

Von: Andreas Rosdal <notifications@github.com>
Gesendet: Montag, 16. September 2019 17:45
An: LibrePDF/OpenPDF <OpenPDF@noreply.github.com>
Cc: Michael Metzger | RA Consulting <M.Metzger@rac.de>; Mention <mention@noreply.github.com>
Betreff: Re: [LibrePDF/OpenPDF] Incorrect buttom height calculation in table cell (#258)


@rammetzger<https://github.com/rammetzger> Can you please verify that this has been fixed in the master branch?
