### ISSUE TITLE
setMargins() not working after document.open() and before document.newPage()

### ISSUE THREAD

**Issue by MaurizioCasciano** [LibrePDF/OpenPDF#259]
The `setMargins()` command doesn't seem to be working when I want to change the margins for a new page.

The version of OpenPDF that I'm using is the **1.3.10**

Here the minimum working example to reproduce the error:

```
package my.project;

import com.lowagie.text.Document;
import com.lowagie.text.Image;
import com.lowagie.text.PageSize;
import com.lowagie.text.Paragraph;
import com.lowagie.text.pdf.PdfWriter;

import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.net.URL;

public class ReportBuilder {
    public void addCover(Document document) {
        URL coverURL = this.getClass().getResource("/images/report/Cover.png");

        this.addCover(document, coverURL);
    }

    public void addCover(Document document, URL coverURL) {
        try {
            Image cover = Image.getInstance(coverURL);
            cover.scaleAbsolute(document.getPageSize().getWidth(), document.getPageSize().getHeight());

            document.add(cover);
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    public static void main(String[] args) {

        try (Document document = new Document(PageSize.A4, 0, 0, 0, 0)) {
            PdfWriter writer = PdfWriter.getInstance(document, new FileOutputStream("Document.pdf"));
            document.open();

            ReportBuilder reportBuilder = new ReportBuilder();
            reportBuilder.addCover(document);

            document.setMargins(40, 40, 40, 40);
            document.newPage();

            StringBuilder builder = new StringBuilder();
            for (int i = 0; i < 100; i++) {
                builder.append("Hey there " + i);
            }

            document.add(new Paragraph(builder.toString()));
        } catch (FileNotFoundException e) {
            e.printStackTrace();
        }
    }
}
```

and this is the output I'm getting, with the maring not corresponding to the ones that I did set:
![Schermata da 2019-09-16 16-14-52](https://user-images.githubusercontent.com/12021064/64967126-4a094800-d8a0-11e9-81b6-97483576536a.png)

**Comment by izio7** [comment]
@andreasrosdal

**Comment by andreasrosdal** [comment]
Thanks for reporting this. Pull requests welcome!

**Comment by vic0075** [comment]
> The setMargins() command doesn't seem to be working when I want to change the margins for a new page.

Isn't this a wrong practice to start with ie. setting margin after document is opened.
I have slightly updated your piece of code with
`Document document = new Document(PageSize.A4, 0, 0, 0, 0);
        PdfWriter writer = PdfWriter.getInstance(document, new FileOutputStream("testSetMargin.pdf"));
        document.open();
        document.setMargins(40, 40, 40, 40);
        document.newPage();
        StringBuilder builder = new StringBuilder();
        for (int i = 0; i < 100; i++) {
            builder.append("Hey there ").append(i);
        }
        document.add(new Paragraph(builder.toString()));
        document.newPage();
        builder.setLength(0);
        for (int i = 0; i < 100; i++) {
            builder.append("Hey there ").append(i);
        }
        document.add(new Paragraph(builder.toString()));
        document.close();`

and got the expected response
<img width="315" alt="Screenshot 2020-01-20 at 12 37 41 PM" src="https://user-images.githubusercontent.com/6236263/72705510-ac8d9000-3b81-11ea-97cc-d456fd885724.png">

See, second page has desired margin. I am not sure if this qualifies as a bug.

**Comment by ObsisMc** [comment]
@vic0075 So setMargins() only comes into effect in the second page and pages after that?

**Comment by mkl-public** [comment]
If anything, this may be a _documentation_ issue because the behavior makes sense. iText / OpenPDF design details:

* The margins are considered whenever a new page is created.
* `Document.open` creates the first document page.
* `Document.newPage` is ignored by `PdfDocument` if nothing has been added to the current page yet.

Thus, after
```lang-java
document.open(); 
document.setMargins(40, 40, 40, 40); 
document.newPage();
```
you're still on the first page with the original margins created by `open`, not on a next page with the new margins created by `newPage`, because the `newPage` call has been ignored.
