### ISSUE TITLE
How to use openPDF in vbscript and C#

### ISSUE THREAD

**Issue by jeeban13** [LibrePDF/OpenPDF#26]
How to use openPDF object in vbscript and C# because customer installed openPDF software to view and edit pdf files

**Comment by andreasrosdal** [comment]
OpenPDF is a Java library. I don't know how you could use that in Vbscript or C#.

**Comment by andreasrosdal** [comment]
Closing, as OpenPDF is a Java library, not C#.

**Comment by b9chris** [comment]
You would need to build the bridge code between Java and .Net libraries, similar to the way parts of Lucene were originally ported to the .Net platform. Or, if you're OK with a much narrower bottleneck, you could just call the Java version with command-line calls via Process.Start(). Or you could do the hardest thing, which is to translate the Java version to C#, perhaps starting with an automated tool to begin the process - as Lucene.Net has done. But it is more likely that you'd be better off just using a C# PDF writer, which LibrePDF is not. The following however are:

https://ironpdf.com/
http://www.pdfsharp.net

**Comment by suryapratap** [comment]
Or you could use IKVM
