### ISSUE TITLE
Using this library for a commercial use?

### ISSUE THREAD

**Issue by smartgatto** [LibrePDF/OpenPDF#269]
Hi, my name's Marco and I write my first app. I'd like to use this library for create a PDF report. My app will be used for medical commercial use. It is possible to use it? Thank you and excuse my bad english!

**Comment by andreasrosdal** [comment]
Yes, you can use OpenPDF is commercial projects.

For the details, see: http://www.gnu.org/licenses/lgpl.html
and: 
https://github.com/LibrePDF/OpenPDF/blob/master/License.md
