### ISSUE TITLE
PdfPTable not visible in Paragraph if keepTogether is set to true

### ISSUE THREAD

**Issue by matija137** [LibrePDF/OpenPDF#271]
First and foremost I would like apologize if this is not a place for this question. Essentially I'm repeating the question I asked a while ago on [Stackoverflow](https://stackoverflow.com/questions/57787275/why-is-pdfptable-not-visible-in-paragraph-if-keeptogether-is-set-to-true).

I'm trying to group table with two texts (one above, and one below table) to prevent splitting of elements when they don't fit in remaining empty space on page.

Elements are added to Paragraph with _keepTogether_ set to true. I noticed peculiar behavior when using _setKeepTogether(true)_.

[If _setKeepTogether(true)_ is called, table won't appear, other elements will.](https://i.stack.imgur.com/43Q48.png)
[If _setKeepTogether(false)_ - everything works as expected.](https://i.stack.imgur.com/ehYBE.png)

Here is my code example:
```java
public static void main(String[] args) throws DocumentException, FileNotFoundException {
  Document document = new Document();
  PdfWriter pdfWriter = PdfWriter.getInstance(document, new FileOutputStream(DEST));
  document.open();

  PdfPTable table = new PdfPTable(2);
  table.addCell("Lorem");
  table.addCell("ipsum");
  table.addCell("dolor");
  table.addCell("sit");

  Paragraph mainParagraph = new Paragraph();
  Paragraph paragraph1 = new Paragraph("Text above table");
  Paragraph paragraph2 = new Paragraph("Text below table");

  mainParagraph.add(paragraph1);
  mainParagraph.add(table);
  mainParagraph.add(paragraph2);

  // if keeptogether is true, table is not visible
  mainParagraph.setKeepTogether(true);

  document.add(mainParagraph);

  document.close();
}
```
Any clue as to what is happening?

Code is tested with latest (1.3.11) OpenPdf version and openjdk 1.8.0_192.

For what it's worth I also tested with itext 2.1.7 and 5.5.13. Version 2.1.7 has the same problem and in 5.5.13 table is visible with _keepTogether_ set to true.

**Comment by razilein** [comment]
I think the Problem is, if keepTogether is set to true, then all elements of the paragraph are added to a new table without borders. If I try to add a table to a cell of a table it isn't visible.

https://github.com/LibrePDF/OpenPDF/blob/master/openpdf/src/main/java/com/lowagie/text/pdf/PdfDocument.java#L529
