### ISSUE TITLE
Hacktoberfest

### ISSUE THREAD

**Issue by sixdouglas** [LibrePDF/OpenPDF#273]
Can you imagine some improvements that could be done in the context of the Hacktoberfest?

https://hacktoberfest.digitalocean.com/details

**Comment by triyasniko** [comment]
actually, i think you are only required to do 4 verified pulls

**Comment by sixdouglas** [comment]
@triyasniko I agree with you. But with the tag on some issues the project would be more visible and we would get some help 😉

**Comment by asturio** [comment]
The open issues are not really "nice" and "self contained". Maybe not this year, but I think this is a great idea.

**Comment by sixdouglas** [comment]
Ok, lets keep it in mind for next year so.
