### ISSUE TITLE
Parsing nested lists with HTMLWorker

### ISSUE THREAD

**Issue by rammetzger** [LibrePDF/OpenPDF#288]
The HTMLWorker.parseToList() method has a bug when parsing nested lists, e.g.
```
<ol>
	<li>Element-1
		<ol>
			<li>Element-1-1</li>
			<li>Element-1-2</li>
		</ol>
	</li>
	<li>Element-2
		<ol>
			<li>Element-2-1</li>
			<li>Element-2-2</li>
		</ol>
	</li>
</ol>
```
As a result, only the first-level elements are returned: ['Element-1', 'Element-2'].

The bug is in the HTMLWorker.endElement() method:
```
542: 	if (tag.equals(HtmlTags.UNORDEREDLIST)
543:		|| tag.equals(HtmlTags.ORDEREDLIST)) {
...
558:	((TextElementArray) stack.peek()).add((Element) obj);
```
For nested lists, variable 'obj' is of type 'com.lowagie.text.List', but it is casted to type 'Element'. Therefore the method 'add(Element o)' is called, but this method does not handle lists. 
The proper method is 'add(List nested)' in class 'com.lowagie.text.List'. So the above code should look like this:
```
558:	{
559:		Object peek = stack.peek();
560:		if (peek instanceof com.lowagie.text.List && obj instanceof com.lowagie.text.List) {
561:			((com.lowagie.text.List) peek).add((com.lowagie.text.List) obj);
562:		}
563:		else 
564:		{
565:			((TextElementArray) peek).add((Element) obj);
566:		}                  
567:	}

```
Please fix this bug so we can use the official version again. Thank you in advance.

Best regards
Michael

**Comment by sixdouglas** [comment]
@rammetzger can you check my [PR](https://github.com/LibrePDF/OpenPDF/pull/290) and tell me what would be the expected result?

**Comment by andreasrosdal** [comment]
This has been merged to the master branch now. 
@rammetzger @sixdouglas Can you please confirm that this is working as expected now?
