### ISSUE TITLE
Change package name to com.github.librepdf

### ISSUE THREAD

**Issue by renber** [LibrePDF/OpenPDF#29]
Since the maven groupId and the java package name of the library have nothing in common now, wouldn't it be better to move all class from com.lowagie to com.github.librepdf / com.github.librepdf.openpdf?

**Comment by andreasrosdal** [comment]
Yes. We could change the package name at some point. However, as this will cause trouble for existing users of OpenPDF, I do not want to do this change yet.

**Comment by renber** [comment]
Maybe this can be done with a potential 2.0 release? Provided enough differences to the basic itext exist then, setting this library apart.

**Comment by andreasrosdal** [comment]
Yes, possibly. I'm thinking this could happen in 2018 or 2019.  We need more users of OpenPDF still first. Once OpenPDF is well established as the main dominating development branch for this code-base, then possibly the package name could be changed, iff the users wants it. There are few reasons why the end-users of OpenPDF should care very much for the package name, though.

A start would be to convince the Flyingsaucer project to switch to OpenPDF. Any help with that can be done here:  https://github.com/flyingsaucerproject/flyingsaucer/pull/123

**Comment by andreasrosdal** [comment]
Thanks for reporting this. I am closing this issue now, and will revisit this issue again in 2019. The main reason for closing is that I want to keep stable API compatibility for a longer period of time.
