### ISSUE TITLE
Multilingual fonts not supported properly as typography rules not implemented.

### ISSUE THREAD

**Issue by codecracker2014** [LibrePDF/OpenPDF#297]

**Comment by sixdouglas** [comment]
@codecracker2014 thanks for this issue but what would you mean? Any particular issue? Code to reproduce it?

**Comment by codecracker2014** [comment]
Current output: 
![image](https://user-images.githubusercontent.com/6597998/69200240-92730980-0b60-11ea-8b68-13b952258923.png)

Expected output:
![image](https://user-images.githubusercontent.com/6597998/69200399-044b5300-0b61-11ea-9692-104b1efaff52.png)

This is due to glyph substitutions not done as per TTF file.
Below is link to typography specs:
https://docs.microsoft.com/en-us/typography/opentype/spec/gsub

Below is code for creating simple PDF using TTF font  :


`
import com.lowagie.text.*;
import com.lowagie.text.pdf.PdfWriter;

import java.io.FileOutputStream;
import java.io.IOException;

/**
 * Created by gajendra.jatav on 11/20/2019.
 */
public class HelloWorld {

    public static void main(String[] args) {

        System.out.println("नमस्ते");

        FontFactory.register("C:\\Windows\\Fonts\\NIRMALA.TTF");
        // step 1: creation of a document-object
        Document document = new Document();
        try {
            // step 2:
            // we create a writer that listens to the document
            // and directs a PDF-stream to a file
            PdfWriter.getInstance(document,
                    new FileOutputStream("D:\\workspace\\TMP\\out\\HelloWorld.pdf"));

            // step 3: we open the document
            document.open();
            // step 4: we add a paragraph to the document
            document.add(new Chunk(
                    "नमस्ते",
                    FontFactory.getFont("nirmala ui", "Identity-H",false,10,0,null)));
        } catch (DocumentException de) {
            System.err.println(de.getMessage());
        } catch (IOException ioe) {
            System.err.println(ioe.getMessage());
        }

        // step 5: we close the document
        document.close();
    }
}

`

**Comment by mkl-public** [comment]
Just like in iText 5, OpenPDF only has a limited support for advanced typography.

**Comment by codecracker2014** [comment]
itext2 was used in more then 150 open source libraries, now these libraries can use OpenPDF. But all of them having this limitation. Itext was rewritten just add advanced typography, which is no longer compatible with other open source libraries. I'm working on improving OpenPDF to support advanced typography and got it working. I'll share pull request shortly.
