### ISSUE TITLE
Please help on how to parse

### ISSUE THREAD

**Issue by msdobrescu** [LibrePDF/OpenPDF#299]
Hello,

I'd need to parse a PDF. For security reasons I can't provide it.
Is there a way to get a collection of styles, paragraphs, cells, in order to decide which contained text section to take? I've seen LibreOffice does this as export to .fodg, but would be good to avoid that.
What are the classes and functions to look for? Is there some mock-up code that would be a start for this?

Thank you in advance.

**Comment by mkl-public** [comment]
**If your PDF is not tagged**, please be aware that there are no explicit styles, paragraphs, or cells in your PDF, there merely are streams of instructions (like _select-font-and-font-size_, _select-fill-color_, _draw-text-chunk_, _select-stroke-color_ _move-to_, _line-to_, _draw-path_, etc.).

By parsing these instructions you can try to collect text chunks and arrange them to text lines and paragraphs, line paths to arrange them to cell borders, and fonts and colors and more at the time text is drawn to bundle them as styles. Be aware, though, those paragraphs, cells, and styles are not actual objects in the PDF but instead an interpretation of collections of instructions or states.

If you nonetheless are interested in walking this road, you may be interested in reading https://github.com/LibrePDF/OpenPDF/issues/336 where this is explained in more detail.

**If your document is properly tagged**, the situation may differ. In that case you can walk the structure tree objects in the document catalog and will probably find structures like paragraphs, table cells, and styles.

Thus, what kind of PDF do you have? Is it (properly!!) tagged? (If it's tagged but not properly so, you cannot trust the information retrieved from the tags, so you're essentially in the situation of an untagged PDF.)

**Comment by asturio** [comment]
HI @msdobrescu , have you solved this issue?

**Comment by msdobrescu** [comment]
No. I have not enough knowledge on PDF to do it.
I have used gs+ps2ascii.ps (in command line) to extract the text, then parsed that.
