### ISSUE TITLE
codewords padding for Macro PDF417-macro barcodes 

### ISSUE THREAD

**Issue by sprengstuff** [LibrePDF/OpenPDF#300]
PDF-417 macro barcodes are not generated correctly 
Look at the bug in itext
https://github.com/itext/itextpdf/commit/adb9b5e86a53d4c95b7fe1bf8fe3fe3be88f6179#diff-4e078bbe8890325866c39d8ca563f49f

**Comment by sprengstuff** [comment]
[macroBarcode.zip](https://github.com/LibrePDF/OpenPDF/files/3890449/macroBarcode.zip)

**Comment by asturio** [comment]
This is also a nice one for new contributor. There is a fix in itext. The fix MAY NOT be copied from iText due license issues, but the code is a great starting point for an independent implementation in OpenPDF.

A UnitTest for this could also be nice.

Pull requests are welcome.
