### ISSUE TITLE
PNG type TYPE_BYTE_BINARY incorrectly printed

### ISSUE THREAD

**Issue by josephe-kv** [LibrePDF/OpenPDF#301]
The 2, or 4 bit image (PNG) type of TYPE_BYTE_BINARY is not correctly printed.

example of the image:
![wn_screen](https://user-images.githubusercontent.com/58358982/69899007-e6e86700-1360-11ea-8827-0c513ee91efd.png)
 
incorrect ouput:
<img width="334" alt="obrazek" src="https://user-images.githubusercontent.com/58358982/69899074-a5a48700-1361-11ea-9b08-74dea09ebded.png">

The problem could be solved in Image#getInstance(java.awt.Image image, java.awt.Color color,
            boolean forceBW)

as follow:
===
        if(image instanceof BufferedImage){
            BufferedImage bi = (BufferedImage) image;
            if(bi.getType()==BufferedImage.TYPE_BYTE_BINARY && bi.getColorModel().getNumColorComponents() <= 2) {
                forceBW=true;
            }
        }
===

**Comment by josephe-kv** [comment]
Problem solved in 
https://github.com/josephe-kv/OpenPDF/commit/85e4e2231d1cb5518dc65ca77496c5f52a678edc

**Comment by andreasrosdal** [comment]
This has been fixed in OpenPDF 1.3.12. Please test that version, and report if this issue is fixed there.
