### ISSUE TITLE
Bold fonts not working for Calibri 

### ISSUE THREAD

**Issue by codecracker2014** [LibrePDF/OpenPDF#312]
getFont method of FontFactoryImpl expects fontname, size, style. But doesn't consider style argument in case different bold font exists for provided font name, as per below code. 
   
![image](https://user-images.githubusercontent.com/6597998/70886308-2ff71700-2001-11ea-8544-03ffbe0b487e.png)

So with above condition if i use below code it will output normal style :
`            Paragraph p1 = new Paragraph(new Chunk(
                    "This is my first paragraph. ",
                    FontFactory.getFont("Calibri", 10,Font.BOLD)));
`

getFont method takes both fontName and style as arguments and changes fontName  according to updated style but following gets incorrect with updated fontName.
`        String lowerCaseFontname = fontname.toLowerCase(Locale.ROOT);`

Above was initialized in starting of method getFont, lowerCaseFontname  should be updated with new fontName.

**Comment by codecracker2014** [comment]
Raised pull request for this issue against #316

**Comment by andreasrosdal** [comment]
This has been fixed in OpenPDF 1.3.12. Please test that version, and report if this issue is fixed there.
