### ISSUE TITLE
Problem with simulating bold font by drawing text

### ISSUE THREAD

**Issue by V-F** [LibrePDF/OpenPDF#314]
There is a problem with simulating bold font by drawing text with the logical font if text cosists from the symbols from the different physical fonts (logical fonts always has suffix ".bold" for the bold style and ".bolditalic" for the bold & italic style).  Bugfix is proposed in the [PR 307](https://github.com/LibrePDF/OpenPDF/pull/307).
The following code example may reproduce this problem:

    import java.awt.Color;
    import java.awt.FontMetrics;
    import java.awt.Graphics2D;
    import java.io.FileOutputStream;
    import java.io.IOException;
    import java.util.HashMap;

    import com.lowagie.text.Document;
    import com.lowagie.text.DocumentException;
    import com.lowagie.text.Font;
    import com.lowagie.text.pdf.BaseFont;
    import com.lowagie.text.pdf.DefaultFontMapper;
    import com.lowagie.text.pdf.DefaultFontMapper.BaseFontParameters;
    import com.lowagie.text.pdf.PdfContentByte;
    import com.lowagie.text.pdf.PdfTemplate;
    import com.lowagie.text.pdf.PdfWriter;

    public class Test {

    	private static final float 	PAGE_A4_WIDTH_PX		= 793.7007f;
    	private static final float 	PAGE_A4_HEIGHT_PX		= 1122.5196f;
    	private static final float	TEMPLATE_WIDTH_HEIGHT	= 400;
    	private static final String	TESTED_TEXT				= "加粗字體 Bold text";
	
    	public static void main(String[] args) {
    		try (Document document = new Document()) {
    			PdfWriter writer = PdfWriter.getInstance(document, new FileOutputStream("test_pdf.pdf"));
    			document.open();

    			PdfContentByte pdfContentByte = writer.getDirectContent();
    			document.setPageSize(new Rectangle(0, 0, PAGE_A4_WIDTH_PX, PAGE_A4_HEIGHT_PX));
    			document.newPage();

    			PdfTemplate pdfTemplate = pdfContentByte.createTemplate(PAGE_A4_WIDTH_PX, PAGE_A4_HEIGHT_PX);

    			Graphics2D g2D = pdfTemplate.createGraphics(TEMPLATE_WIDTH_HEIGHT, TEMPLATE_WIDTH_HEIGHT, createTestFontMapper());
    			g2D.setColor(Color.black);
    			try {
    				java.awt.Font logicalFont = new java.awt.Font("Dialog", Font.BOLD, 12);
    				java.awt.Font phisicalFont = new java.awt.Font("SimSun", Font.BOLD, 12);
				
    				int xOff = 15;
    				int yOff = 20;
    				yOff = drawString(g2D, null, "Both followed string should be bold:", xOff, yOff);
    				yOff = drawString(g2D, logicalFont, TESTED_TEXT, xOff, yOff);
    				yOff = drawString(g2D, phisicalFont, TESTED_TEXT, xOff, yOff);
    			} finally {
    				g2D.dispose();
    			}
    			pdfContentByte.addTemplate(pdfTemplate, 0, PAGE_A4_HEIGHT_PX - TEMPLATE_WIDTH_HEIGHT);
    		} catch (DocumentException | IOException de) {
    			System.err.println(de.getMessage());
    		}
    	}
	
    	private static DefaultFontMapper createTestFontMapper() {
    		DefaultFontMapper mapper = new DefaultFontMapper();
		    
    mapper.insertDirectory(sun.font.SunFontManager.getInstance().getPlatformFontPath(true));
    		HashMap<String, BaseFontParameters> mapping = mapper.getMapper();
    		/*
    		* Change encoding to the IDENTITY_H for the found fonts from the given platform font paht since
    		* the default implementation of the insertDirectory method use CP1252 encoding. But we
    		* need to display some chinese symbols. Dont know if there is besser way to do this.
    		*/
    		for (BaseFontParameters parameters : mapping.values()) {
    			parameters.encoding = BaseFont.IDENTITY_H;
    		}
    		return mapper;
    	}
	
    	private static int drawString(Graphics2D g2D, java.awt.Font font, String text, int x, int y) {
    		if (font != null) {
    			g2D.setFont(font);
    		}
    		g2D.drawString(text, x, y);
    		int spaceBetweenTextLinesPx = 10;
    		y += getFontMetricsHeight(g2D, g2D.getFont()) + spaceBetweenTextLinesPx;
    		return y;
    	}

    	private static int getFontMetricsHeight(Graphics2D g2D, java.awt.Font font) {
    		FontMetrics metrics = g2D.getFontMetrics(font);
    		return metrics.getHeight();
    	}
    }

**Comment by andreasrosdal** [comment]
This has been fixed in OpenPDF 1.3.12. Please test that version, and report if this issue is fixed there.

**Comment by V-F** [comment]
Tested. This issue was fixed in 1.3.12.
