### ISSUE TITLE
Problem with displaying strings with composite fonts 

### ISSUE THREAD

**Issue by V-F** [LibrePDF/OpenPDF#315]
There is a problem by drawing a string that contains various Unicode characters when using logical fonts for displaying. The reason is that it is not enough to check the availability of the glyph in the physical font, but it is necessary to check the presence of the character in the BaseFont used for drawing, since it doesn't know how the FontMapper is implemented.
Bugfix is proposed in the [PR 308](https://github.com/LibrePDF/OpenPDF/pull/308).
The following code example may reproduce this problem (it should be displayed four symbols):

    import java.awt.Color;
    import java.awt.FontMetrics;
    import java.awt.Graphics2D;
    import java.io.FileOutputStream;
    import java.io.IOException;
    import java.util.HashMap;

    import com.lowagie.text.Document;
    import com.lowagie.text.DocumentException;
    import com.lowagie.text.Font;
    import com.lowagie.text.pdf.BaseFont;
    import com.lowagie.text.pdf.DefaultFontMapper;
    import com.lowagie.text.pdf.DefaultFontMapper.BaseFontParameters;
    import com.lowagie.text.pdf.PdfContentByte;
    import com.lowagie.text.pdf.PdfTemplate;
    import com.lowagie.text.pdf.PdfWriter;

    public class Test2 {

    	private static final float 	PAGE_A4_WIDTH_PX		= 793.7007f;
    	private static final float 	PAGE_A4_HEIGHT_PX		= 1122.5196f;
    	private static final float	TEMPLATE_WIDTH_HEIGHT	= 400;
    	private static final String	TESTED_TEXT				= "\uff46\u2080\u0192\u2081";
	
    	public static void main(String[] args) {
    		try (Document document = new Document()) {
       			PdfWriter writer = PdfWriter.getInstance(document, new FileOutputStream("test_pdf.pdf"));
    			document.open();

    			PdfContentByte pdfContentByte = writer.getDirectContent();
    			document.setPageSize(new Rectangle(0, 0, PAGE_A4_WIDTH_PX, PAGE_A4_HEIGHT_PX));
    			document.newPage();

    			PdfTemplate pdfTemplate = pdfContentByte.createTemplate(PAGE_A4_WIDTH_PX, PAGE_A4_HEIGHT_PX);

    			Graphics2D g2D = pdfTemplate.createGraphics(TEMPLATE_WIDTH_HEIGHT, TEMPLATE_WIDTH_HEIGHT, createTestFontMapper());
    			g2D.setColor(Color.black);
    			try {
    				java.awt.Font logicalFont = new java.awt.Font("Dialog", Font.NORMAL, 12);
    				g2D.setFont(logicalFont);
    				g2D.drawString(TESTED_TEXT, 15, 20);
    			} finally {
    				g2D.dispose();
    			}
    			pdfContentByte.addTemplate(pdfTemplate, 0, PAGE_A4_HEIGHT_PX - TEMPLATE_WIDTH_HEIGHT);
    		} catch (DocumentException | IOException de) {
    			System.err.println(de.getMessage());
    		}
    	}
	
    	private static DefaultFontMapper createTestFontMapper() {
    		DefaultFontMapper mapper = new DefaultFontMapper();
    	mapper.insertDirectory(sun.font.SunFontManager.getInstance().getPlatformFontPath(true));
    		HashMap<String, BaseFontParameters> mapping = mapper.getMapper();
    		/*
    		* Change encoding to the IDENTITY_H for the found fonts from the given platform font paht since
    		* the default implementation of the insertDirectory method use CP1252 encoding. But we
    		* need to display some unicode symbols. Dont know if there is a besser way to do this.
    		*/
    		for (BaseFontParameters parameters : mapping.values()) {
    			parameters.encoding = BaseFont.IDENTITY_H;
    		}
    		return mapper;
    	}
    }

**Comment by andreasrosdal** [comment]
This has been fixed in OpenPDF 1.3.12. Please test that version, and report if this issue is fixed there.

**Comment by V-F** [comment]
Tested. This issue was fixed in 1.3.12.
