### ISSUE TITLE
Lines get lost on page break

### ISSUE THREAD

**Issue by rammetzger** [LibrePDF/OpenPDF#317]
3 months ago we asked for bug fix because we had a problem with rows, that were printed twice when a page break occurred inside a table cell. [https://github.com/LibrePDF/OpenPDF/issues/258]

However, we have now discovered that this bugfix causes another problem: Sometimes a row is lost if a page break occurred in a table cell with long text.

Please revert the changes from this issue.

**Comment by sixdouglas** [comment]
Is it possible to provide a sample code to reproduce easily this bug?

**Comment by rammetzger** [comment]
I cannot provide an example because the code for generating the report is very large. it would be too much work for me. I made some screenshots, I hope they help you. See: input_text.png and printed_text.png.

I tested with version 1.3.13 and found another issue. Opacity no longer works as expected. See: draft_old.png and draft_new.png.

Viele Grüße / Best regards
Michael

Von: SIX Douglas <notifications@github.com>
Gesendet: Donnerstag, 23. Januar 2020 12:27
An: LibrePDF/OpenPDF <OpenPDF@noreply.github.com>
Cc: Michael Metzger | RA Consulting <M.Metzger@rac.de>; Author <author@noreply.github.com>
Betreff: Re: [LibrePDF/OpenPDF] Lines get lost on page break (#317)


Is it possible to provide a sample code to reproduce easily this bug?

**Comment by asturio** [comment]
Probably the same Problem as #345

**Comment by whexy** [comment]
Hi, I've looked into this issue for a while. It seems that PR #260 introduced a bug. Please find the solution in PR #524.

**Comment by bk1991** [comment]
@asturio - I am facing this issue with 1.3.26 release for multiple cases. This gets fixed by the changes mentioned by @whexy in 
#524 
But these changes are not there in the latest release 1.3.27, can you get a release/patch with this change ?

**Comment by asturio** [comment]
@bk1991 @whexy @sixdouglas @rammetzger 
I think this was fixed in 1.3.29. Can you check that?

**Comment by bk1991** [comment]
@asturio verified on 1.3.29, the issue seems resolved

**Comment by rammetzger** [comment]
I am glad to see that the problem is fixed in 1.3.29.
