### ISSUE TITLE
I need append more watermaker ,do tile effect.

### ISSUE THREAD

**Issue by legiorange** [LibrePDF/OpenPDF#319]
I' m so sorry!

I try what I can do , but still can't set more watermaker on one line.

I really need Tile effect ....

**Comment by asturio** [comment]
Have you found a solution for this issue, @legiorange ?

**Comment by legiorange** [comment]
I do.
First time I used java. awt.(and It work but it hard to write that effect)
And next, I try canvas.
I really doubt about my life when I f**ed up.
Finally, I use itext.
I'll try find some solution on this, just because I like it .

**Comment by asturio** [comment]
Closing this. But pull request are always welcome!
