### ISSUE TITLE
Illegal reflective access warning at Java 13

### ISSUE THREAD

**Issue by alanwhite** [LibrePDF/OpenPDF#331]
Similar to issue #101. 

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.lowagie.text.pdf.PdfGraphics2D$CompositeFontDrawer (file:[snip]openpdf-1.3.12.jar) to method sun.font.FontUtilities.getFont2D(java.awt.Font)
WARNING: Please consider reporting this to the maintainers of com.lowagie.text.pdf.PdfGraphics2D$CompositeFontDrawer
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

**Comment by andreasrosdal** [comment]
Thanks for reporting. Pull requests welcome.
