### ISSUE TITLE
What happened to module 'pdf-rtf' ?

### ISSUE THREAD

**Issue by cursor42** [LibrePDF/OpenPDF#334]
In older releases of OpenPDF (e.g. 1.1.0) there was a module called `pdf-rtf` (still hosted on Maven Central as `com.github.librepdf / pdf-rtf / 1.1.0`) which seemed to be a fork of `itext-rtf`.

We used `itext` and `itext-rtf` version 2.1.7 for a long time. `OpenPDF`should be a good replacement for `itext` but I cannot find a replacement for `itext-rtf`.

Could you please tell me, if it is possible to replace `itext-rtf` with `OpenPDF`, too? Why did you remove the module `pdf-rtf` ?

**Comment by andreasrosdal** [comment]
pdf-rtf can now be found as OpenRTF here:  https://github.com/LibrePDF/openrtf

pdf-rtf was removed from OpenPDF, and can now be found in the repository above. Contributors to that project is welcome!
