### ISSUE TITLE
Trying to add fillColor operation with PdfSpotColor, but references to GraphicState and ColorState don't exists in final PDF

### ISSUE THREAD

**Issue by timbaas** [LibrePDF/OpenPDF#338]
I'm trying to merge multiple PDFs that represent layers into a single new PDF. This works, but another thing I need to do is replace a regular `fillColor` operation with a `fillColor` & `SpotColor` combination. 

Currently I read the `byte[]` of each layers' PDF by using `getPageContent()` into a variable. I use the `PRTokenizer` to iterate through the tokens and when I come across the `"rg"` operation I inject the operations for color filling with a spotcolor.

I have a `List<Byte>` in which I will store all existing bytes from `getPageContent()` while iterating it.

The Injection is currently done as follows:
- construct a new `PdfContentByte` instance (using a PdfWriter that has the layers' PDF imported on its contentByte) 
- create the SpotColor with a specific name and RGB values copied from the `"rg"` operation
- call the `setColorFill()` on the new PdfContentByte instance.
- convert the PdfContentByte to `byte[]` by using `toPdf()` (again using the PdfWriter mentioned).
- iterate the `byte[]` and add every entry to the `List<Byte>`.

When the injection is done the main iteration of the layer will continue and all other existing bytes will be added. 

When a layer is completely iterated I convert the `List<Byte>` back to `byte[]` and use that for calling `setPageContent()` to update the layer with the SpotColor operation injected.

Finally I add the layer to the final PDF and when all layers are done I `close()` the document.

This all gives no compiler and/or runtime issues and exports a PDF with the layers. The PDF is even visible in MacOS preview.

Sadly, when opening the PDF in Acrobat it gives an error and no layers are displayed.
I validated the PDF and it gives the following errors:
- Missing ColorSpace (3 matches, 1 page)
- Missing Extended Graphic State (3 matches, 1 page)

The 3 matches are because there are 3 layers in which I try to add the SpotColor.
I'm not sure what to do about the missing references and/or why they aren't added/copied to the final PDF. Hope it's just a simple step that I'm missing?

I added the full code to this gist:
https://gist.github.com/timbaas/61425b081c0723664368e4c176d8375a

**Comment by asturio** [comment]
@timbaas , did you find a solution for this problem?

**Comment by timbaas** [comment]
@asturio 
I got it to work in the end, but I can't remember exactly how and don't have the code near me currently.
I remember converting each layer to a new PDF first and merge the new PDF's to one instead off writing them to a new PDF directly while converting.

The replacement of the rg operation was pretty hard, since bytes needed to be shifted to make room in the stream and this wasn't as straight forward as you would think. Could've been me though, had never worked with List<Byte> this way before..

**Comment by asturio** [comment]
Thanks. If you have some improvement for OpenPDF feel free to create a pull request.
