### ISSUE TITLE
2 x IntelliJ Licenses for active Contributors

### ISSUE THREAD

**Issue by asturio** [LibrePDF/OpenPDF#341]
Hi everyone,
I have 2 licenses for IntelliJ Ultimate to give away for active contributors. If you think, you are an active contributor, please let me know in a comment here, and I'll check that.
You may also name a contributor.
On 2020-03-07 I'll distribute them.

**Comment by codecracker2014** [comment]
May I have one.

**Comment by andreasrosdal** [comment]
I would discourage people from using closed-source software as their main IDE.
