### ISSUE TITLE
jlink complains about openpdf being an automatic module

### ISSUE THREAD

**Issue by arnthom** [LibrePDF/OpenPDF#344]
When I try to deploy my pdf project with OpenJava and use jlink to pack the files together, jlink complains 
Error: automatic module cannot be used with jlink: com.github.librepdf.openpdf from file:///path-to-lib/openpdf-1.3.13.jar
Error: automatic module cannot be used with jlink: itext.hyph.xml from file:///path-to-lib/itext-hyph-xml.jar
Is it possible to provide an OpenPdf module to modular Java projects?

**Comment by andreasrosdal** [comment]
Thanks for reporting this. Pull requests welcome.
