### ISSUE TITLE
PdfPTable is sometime missing a line when using setSplitLate

### ISSUE THREAD

**Issue by PsYkO54** [LibrePDF/OpenPDF#345]
Table is sometime missing a text line when using setSplitLate

It works as expected with version 1.3.10, but is not with version 1.3.11+

```java
public static void writePDF(File file) throws FileNotFoundException {
    Document document = new Document(PageSize.A4);
    PdfWriter.getInstance(document, new FileOutputStream(file));

    document.open();
    IntStream.range(0, 30)
        .mapToObj(idx -> new Paragraph("Fill line"))
        .forEach(document::add);

    PdfPTable table = new PdfPTable(1);
    table.setSplitLate(false);

    IntStream.range(0, 3)
        .mapToObj(idx -> new Paragraph("Row " + idx + " Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi eu cursus purus, id efficitur arcu. " +
                "Pellentesque eu arcu elit. Phasellus in mattis diam. Donec in augue eget ligula consectetur pretium. Maecenas scelerisque non massa ut faucibus. " +
                "Nam sit amet malesuada nisl. Duis varius vitae leo venenatis ullamcorper. Morbi at vestibulum tortor, vel blandit erat."))
        .forEach(table::addCell);

    table.addCell("Line 1\nLine 2\nThis line is not in the PDF\nLine 4");
    document.add(table);
    document.close();
}
```

I get the following:
![image](https://user-images.githubusercontent.com/50425425/76317772-fc184e80-62dc-11ea-9b83-368774285a44.png)

**Comment by albfernandez** [comment]
Seems to be cause of the fix for the issue https://github.com/LibrePDF/OpenPDF/issues/258 on the pull request https://github.com/LibrePDF/OpenPDF/pull/260

The https://github.com/LibrePDF/OpenPDF/issues/317 is the same of this, but without sample code

**Comment by asturio** [comment]
Trying to organize this:
Related Issues: #345

- Issue #317
- Issue #258, PR #260 (Cause)

**Comment by asturio** [comment]
Pull request welcome :-)

**Comment by whexy** [comment]
Hi, I've looked into this issue for a while. It seems that PR #260 introduced a bug. Please find the solution in PR #524.
