### ISSUE TITLE
How to make title page with different header/footer?

### ISSUE THREAD

**Issue by RangerMak** [LibrePDF/OpenPDF#347]
I'm try to create multipage PDF with title page.
Header and footer are sets to all document.
How to make different header/footer for title (first) page?

**Comment by vic0075** [comment]
Well, you could always create 2 pdfs, 1 for `title page` and 2nd for the rest. And then merge them.

**Comment by arnthom** [comment]
I use a PdfEvent class and set header and footer as is needed for each page. I use several conditions in onStartPage to set the text and elements.
```
public class PdfEvent extends PdfPageEventHelper {
...
	/** {@inheritDoc} */
	public void onStartPage(PdfWriter writer, Document document) {
        ...
        if ( ... ) {
		final PdfPTable header = new PdfPTable(1);
		header.addCell(cell);
		header.writeSelectedRows(0, -1, document.leftMargin(), 740, writer.getDirectContent());
        }
}
```

**Comment by asturio** [comment]
Seems to be solved.
