### ISSUE TITLE
Missing embedded HTML Support with using openPDF with JBoss-Seam-PDF

### ISSUE THREAD

**Issue by stolp** [LibrePDF/OpenPDF#351]
In my project we are using jboss-seam-pdf (https://github.com/albfernandez/jboss-seam) for report generation which is using IText2 as a PDF renderer.

JBoss-Seam-PDF allows to embed HTML into the PDF document (<p:html>, see: https://docs.jboss.org/seam/2.3.1.Final/reference/html/itext.html). This is working fine with itext, but once I replace it with openPDF all HTML output is suddenly missing. Everything else seems to be working fine.

I am unsure if this is due to an incompatibility or if I was missing something obvious.

I am using OpenPDF 1.3.14.

Any hint on where to look is highly welcome.

**Comment by albfernandez** [comment]
Hi
You must also install [openrtf](https://github.com/LibrePDF/openrtf)
With openpdf and openrtf installed your webapp will start but, depending on your code, it will work or fail (there are some breaking changes in OpenPDF 1.3).
I've created an issue albfernandez/jboss-seam#39 to upgrade to OpenPDF.
You can close this issue and discuss the issue there.

**Comment by stolp** [comment]
Thanks @albfernandez , will do!
