### ISSUE TITLE
How to number pages in the footer (with total page number)

### ISSUE THREAD

**Issue by otoman** [LibrePDF/OpenPDF#355]
Hi, sorry for my stupid question.
I try to get for example _Page 1 of 3_ in the footer.
I found `new HeaderFooter(new Phrase("This is page: ", new Font(bf_courier)), true);` but can´t find how to add total number page. What is the best way?

Thank you :)

**Comment by otoman** [comment]
Ok, I found a way.
First I normally generate PDF with numbered footer aligned to the left side. But with no total page number. Close the document. Then open it again with PdfReader and add total page number and align it to the right. 
            P```
dfReader reader = new PdfReader("OpenPDFExample.pdf");
            PdfStamper stamper = new PdfStamper(reader, new FileOutputStream("File.pdf"));
            stamper.setRotateContents(false);
            Phrase t = new Phrase("Total pages " + reader.getNumberOfPages(), new Font(Font.HELVETICA, 14));
            for (int i = 1; i <= reader.getNumberOfPages(); i++) {
                float xt = reader.getPageSize(i).getWidth()-50;
                float yt = reader.getPageSize(i).getBottom(5);
                ColumnText.showTextAligned(
                        stamper.getOverContent(i), Element.ALIGN_RIGHT,
                        t, xt, yt, 0);
            }
            stamper.close();
            reader.close();
```
Probably not the best way but it works...

**Comment by ModdyLP** [comment]
there is an example how it works without reopening the document. Not all of the example is needed for this but you can cut out the parts you Need. https://github.com/LibrePDF/OpenPDF/blob/master/pdf-toolbox/src/test/java/com/lowagie/examples/directcontent/pageevents/PageNumbersWatermark.java

**Comment by otoman** [comment]
thank you... that´s better solution :)
