### ISSUE TITLE
Anchor with a URL containing a fragment doesn't work

### ISSUE THREAD

**Issue by egaillardon** [LibrePDF/OpenPDF#356]
Hello,
I'm trying to create a document with an anchor that must reference a URL containing a fragment.
But the hash mark is always url encoded : **http://www.ehcache.org/apidocs/3.8.1/org/ehcache/Cache.html%23clear**.
So the browser indicates that the page is not found.
Below a simple code to reproduce the issue I'm facing.
```
package pdf;

import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import com.lowagie.text.Anchor;
import com.lowagie.text.Document;
import com.lowagie.text.DocumentException;
import com.lowagie.text.PageSize;
import com.lowagie.text.Paragraph;
import com.lowagie.text.pdf.PdfWriter;

public class Pdf {

  public static void main(String[] args) throws DocumentException, FileNotFoundException {
    Document document = new Document(PageSize.A4.rotate());
    PdfWriter.getInstance(document, new FileOutputStream("/tmp/FirstPdf.pdf"));
    document.open();
    Paragraph paragraph = new Paragraph("toto");
    document.add(paragraph);
    Anchor anchor = new Anchor("ffffff");
    anchor.setReference("http://www.ehcache.org/apidocs/3.8.1/org/ehcache/Cache.html#clear");
    document.add(anchor);
    document.close();
  }
}
```
Did I forget something ?

Thank you.

Emmanuel

**Comment by vic0075** [comment]
There seems to be some misunderstanding. I have used your code as it is and it is working for me.

![image](https://user-images.githubusercontent.com/6236263/79945071-b11c5a00-848a-11ea-9856-780aaada8959.png)

**Comment by egaillardon** [comment]
Hello
Thank you for the reply.
It turns out that, using Acrobat Reader instead of the Apple viewer, it works fine.
Sorry for the inconvenience.
Regards
Emmanuel
