### ISSUE TITLE
Language glyphs and diacritics

### ISSUE THREAD

**Issue by wickstargazer** [LibrePDF/OpenPDF#36]
Hi, 

have you been able to figure out the language diacritics not rendering properly in openpdf ? :)

**Comment by andreasrosdal** [comment]
No, I haven't. Please describe this problem in more detail. Which language diacritics are not rendered?
 Perhaps you can submit a pull-request to fix it yourself?

**Comment by asturio** [comment]
As with the unicode issue, it seems that the fonts provided are not so symbol rich as you need it, Please try loading a font which has the symbols you need, and see if it works. 

Take a look at this "test": https://github.com/LibrePDF/OpenPDF/blob/master/openpdf/src/test/java/com/lowagie/text/pdf/UnicodePdfTest.java

**Comment by asturio** [comment]
@wickstargazer , you mean the combination of 2 symbols like "a" + "´" = "á", and be hanled like 2 symbols, instead of 1?

**Comment by venkattarigopula** [comment]
Hi all,
The same issue I am getting with Telugu ( India ) language like pointed by @asturio of two characters not mixing to have proper diacritic. The solutions suggested by @rntrp is not solving. As @asturio said about using the right font, I think that is not the issue in my case. Please let me explain.

If the combined string of the two characters ( \u0C2D \u0C4B ) are displaying properly in the sysout.
But not in the PDF. 

In PDF it is displaying as 
![image](https://user-images.githubusercontent.com/30365377/56806355-55a09780-6849-11e9-9dd2-eafcab5a7500.png)

and in console it is displaying as 
![image](https://user-images.githubusercontent.com/30365377/56806394-6bae5800-6849-11e9-9872-ad4c3a2ce370.png)

The code i have written basically is ..

`static String FONT = "c:\\windows\\fonts\\lohit-telugu.ttf";`
`BaseFont bfComic = BaseFont.createFont(FONT, BaseFont.IDENTITY_H, BaseFont.EMBEDDED);`
`Font font = new Font(bfComic, 12);`
`String text3 = "Some Telugu \u0305cha\u0C46racter\u0300s: భోజనం తర్వాత తదుపరి పైన ముందు \u0C2D\u0C4B   ";`
` doc.add(new Paragraph(text3, font));`

**Comment by codecracker2014** [comment]
With #329 this issue has been fixed, please check with latest OpenPDF, make sure to include FOP dependency as well. @asturio we can close this issue.
