### ISSUE TITLE
Hey ! Im Newbie , 

### ISSUE THREAD

**Issue by sophiniashi** [LibrePDF/OpenPDF#360]
Hey ! Im Newbie ,  Have u tutorials how to use this library 
i want to build openPDf to openPdf.jar 

thanks in advance

**Comment by andreasrosdal** [comment]
1. install Apache Maven.
2. check out OpenPDF from git.
3. run this command in the OpenPDF directory: 
mvn install
4. openpdf.jar can be found in the target directory.
