### ISSUE TITLE
PdfAnnotation font

### ISSUE THREAD

**Issue by wise-coders** [LibrePDF/OpenPDF#363]
I am creating PdfAnnotations with Cyrilic or Asian text. For correct display I need to use an unicode font. How may I change an PdfAnnotation font ?

```
final PdfAnnotation annotation = PdfAnnotation.createStamp(writer, new Rectangle( rx, ry, rw, rh), text, "#Comment" );
annotation.setAppearance(PdfName.N, getAnnotationTemplate());
writer.addAnnotation( annotation );
```
Here a sample output:

![image](https://user-images.githubusercontent.com/60284259/80180165-6c1b3380-8602-11ea-9c5a-4cbf4df6f7e2.png)

**Comment by asturio** [comment]
Hi @wise-coders , did you find a solution for this issue?
Pull requests welcome.

**Comment by dprutean** [comment]
Yes, thank you, I have included an unicode font in the document.
