### ISSUE TITLE
Size of the created pdf files

### ISSUE THREAD

**Issue by gabrielecriscuolo** [LibrePDF/OpenPDF#364]
Hello,

I'm bringing a project from itext4.2.1 to OpenPdf. I noticed that the size of the pdf files created are about 30% larger. I attempted to parse the code and found, in my case, that the saveColorFill statement in the setRGBColorFill method of the PdfContentByte class is responsible for this increment. Commenting on this instruction, which is not present in itext4.2.1, the dimensions decrease drastically. Any suggestions or explanations?

Thank you very much

**Comment by andreasrosdal** [comment]
Pull requests welcome.
