### ISSUE TITLE
Minor spelling issue found in javadocs (</CIDE> -> </CODE> i.e. in-balance HTML tag)

### ISSUE THREAD

**Issue by asdf913** [LibrePDF/OpenPDF#365]
https://github.com/LibrePDF/OpenPDF/blob/master/openpdf/src/main/java/com/lowagie/text/Element.java

![image](https://user-images.githubusercontent.com/2301325/80706997-d577d680-8b1b-11ea-8d0d-e9de3357189e.png)

`    /** This is a possible type of <CODE>Element </CIDE>. */
    int AUTHOR = 4;

    /** This is a possible type of <CODE>Element </CIDE>. */
    int PRODUCER = 5;

    /** This is a possible type of <CODE>Element </CIDE>. */
    int CREATIONDATE = 6;

    /** This is a possible type of <CODE>Element </CIDE>. */`

Are the end tag should be **</CODE>**?

**Comment by andreasrosdal** [comment]
Pull requests welcome. Thanks for reporting.

**Comment by andreasrosdal** [comment]
Thanks for improving the JavaDoc. I know more can be done to improve the JavaDoc. There are some JavaDoc warnings during maven install. You are welcome to improve this also!
