### ISSUE TITLE
Improve JavaDoc!

### ISSUE THREAD

**Issue by andreasrosdal** [LibrePDF/OpenPDF#367]
Let's improve the JavaDoc in OpenPDF! This will make it easier to learn how to use the library. Please help add good descriptions to the source code in a consistent way. Pull requests welcome!

The most recent JavaDoc can be found here: https://librepdf.github.io/OpenPDF/docs-1-3-17/

**Comment by vic0075** [comment]
> Let's improve the JavaDoc in OpenPDF! This will make it easier to learn how to use the library. Please help add good descriptions to the source code in a consistent way. Pull requests welcome!

This seems like a giant task
I mean, last I check there were ~66 errors and ~4k warnings.

Fixing errors is relatively easy, warnings also, to some extent, but then there are ~90% cases where parameter's description is missing. for the sake of removing warning, I suppose, we can provide a decent description, but not always.

I am willing to take it up as long but apt description, I'm afraid, will not be possible (unless one knows ins and outs of the class/method).

What's your opinion?

**Comment by andreasrosdal** [comment]
I suggest starting with the most important things. Fixing the errors. Then making sure the most important classes are well documented.

**Comment by andreasrosdal** [comment]
https://github.com/LibrePDF/OpenPDF/pull/368

**Comment by andreasrosdal** [comment]
The most recent JavaDoc can be found here: https://librepdf.github.io/OpenPDF/docs-1-3-17/

**Comment by laurerunser** [comment]
Hi ! Do you still need help with that ? I'd love to contribute !

**Comment by asturio** [comment]
> Hi ! Do you still need help with that ? I'd love to contribute !

Yes, please. Pull requests welcome!

**Comment by asturio** [comment]
Should this be closed now? JavaDoc can always be improved and corrected.

**Comment by laurerunser** [comment]
Maybe keep it open some more. I might be able to work on all those errors by the end of the week !
