### ISSUE TITLE
openpdf-xml 1.2/1.3 pull in slf4j-api 1.8beta breaking logging functionality

### ISSUE THREAD

**Issue by Xnyle** [LibrePDF/OpenPDF#369]
openpdf-xml (tested 1.2) pulls in org.slf4j:slf4j-api:1.8.0-beta2 via com.github.spotbugs:spotbugs:3.1.12

This is bad as slf4j-api:1.8.0-beta2 breaks code that is build for 1.7 (StaticLoggerBindings in my case)

Non beta versions should never pull in experimental or beta stuff not even through transitive dependencies.

**Comment by andreasrosdal** [comment]
Pull requests welcome. Thanks for reporting.

**Comment by andreasrosdal** [comment]
This has been fixed in OpenPDF 1.3.17. Please give that version a try, and report back.

https://github.com/LibrePDF/OpenPDF/releases/tag/1.3.17

**Comment by andreasrosdal** [comment]
Spotbugs is an optional dependency.
