### ISSUE TITLE
Provide CSS resolver

### ISSUE THREAD

**Issue by DanielYWoo** [LibrePDF/OpenPDF#37]
If you have an HTML contains <style> tags in the head, the HTMLWorker cannot parse them, instead, it generates the style tags into the PDF file. Can we support inline styles like iText5+?

```

        OutputStream outputStream = new FileOutputStream(optionalPath);        
        Document document = new Document(PageSize.A4, 30, 30, 30, 30);
        PdfWriter w = PdfWriter.getInstance(document, outputStream);
        HTMLWorker worker = new HTMLWorker(document);
        document.open();
        worker.parse(new StringReader(HTMLUtil.getLongContent()));

        worker.close();
        document.close();
        w.close();
```

**Comment by asturio** [comment]
Have you tried flying saucer? It works really nice for HTML and CSS (in the Header).

**Comment by tlxtellef** [comment]
[https://github.com/flyingsaucerproject/flyingsaucer](https://github.com/flyingsaucerproject/flyingsaucer)

**Comment by DanielYWoo** [comment]
Yes, I have given up and switched to flying saucer

**Comment by tlxtellef** [comment]
Support may appear in the future but for now a bigger job of cleaning up is should be done before any new features are added.
