### ISSUE TITLE
java.lang.Class<com.lowagie.text.pdf.PdfPrinterGraphics2D>: java.lang.NoClassDefFoundError: Failed resolution of: Ljava/awt/print/PrinterGraphics

### ISSUE THREAD

**Issue by kennywin2000** [LibrePDF/OpenPDF#371]
find this issue on Android

openpdf\src\main\java\com\lowagie\text\pdf\PdfPrinterGraphics2D.java
import java.awt.print.PrinterGraphics;
import java.awt.print.PrinterJob;

No PrinterGraphics and PrinterJob class on Android

**Comment by andreasrosdal** [comment]
Thanks for reporting this.

Have you seen this page: https://github.com/LibrePDF/OpenPDF/wiki/Android-support

If so, then please report this bug to 
https://github.com/andob/android-awt

**Comment by andreasrosdal** [comment]
https://github.com/andob/android-awt/issues/4

**Comment by asturio** [comment]
Can't be fixed in OpenPDF, so closing it.
