### ISSUE TITLE
(Question) Migrate to Gradle

### ISSUE THREAD

**Issue by noavarice** [LibrePDF/OpenPDF#372]
Are there any concerns against using of Gradle build framework?
I'm not very experienced Gradle user (though using way longer than Maven), but definitely Gradle is more flexible instrument. Maybe someone have already thought about this, thus providing some help to accomplish the task, especially regarding CI and release deployment

**Comment by andreasrosdal** [comment]
I would prefer that OpenPDF continued to use Maven.
