### ISSUE TITLE
Table in footer get wrong y value

### ISSUE THREAD

**Issue by KasperHelsted** [LibrePDF/OpenPDF#373]
When i try and add a table to the footer of a page, I would expect the table to be within the marked lines at the bottom of the page, however this is not the result.

The table is located at the top of the page, and not at the desired position, this is the same if the table is added to the header, the table is placed just after the margin.

I have created a test scenario to show what i mean:
```
public class TestClass {
    public static void main(String[] args) {
        try {
            Document document = new Document(PageSize.A4);

            PdfWriter writer = PdfWriter.getInstance(document, new FileOutputStream("fail.pdf"));

            PdfPTable table = new PdfPTable(2);
            table.setWidthPercentage(100);
            table.addCell(new PdfPCell(new Paragraph("CONTENT")));
            table.addCell(new PdfPCell(new Paragraph("CONTENT")));

            Paragraph footerParagraph = new Paragraph();
            footerParagraph.add(table);
            HeaderFooter footer = new HeaderFooter(footerParagraph, false);
            footer.setAlignment(Element.ALIGN_CENTER);

            document.setFooter(footer);

            document.open();

            document.add(new Paragraph("Hello World"));
            document.close();
        } catch (Exception ex) {
            System.out.println(ex);
        }
    }
}
```

I have tried to diagnose the problem, but all I was able to find was that when the ["writeSelectedRows"](https://github.com/LibrePDF/OpenPDF/blob/master/openpdf/src/main/java/com/lowagie/text/pdf/PdfPTable.java#L719) method was called, the y position was 806, which was at the top of the page.

**Comment by KasperHelsted** [comment]
After further digging, I can see it's the same for Image and SimpleTable

**Comment by nikolavojicic** [comment]
Is there any workaround for this?

**Comment by cesiabulnes** [comment]
I'll be introducing a PR for this this week. Thanks

**Comment by ObsisMc** [comment]
It seems that the PR above isn't accepted, I will try this issue.

**Comment by bcersows** [comment]
The closing issue https://github.com/LibrePDF/OpenPDF/pull/697 only seems to handle images, or am I missing something? The initial report about tables is still not working. Can someone chime in and try it out to ensure it's not a problem on my end?

Otherwise I'll give it a try next week.

**Comment by ObsisMc** [comment]
> The closing issue #697 only seems to handle images, or am I missing something? The initial report about tables is still not working. Can someone chime in and try it out to ensure it's not a problem on my end?
> 
> Otherwise I'll give it a try next week.

It indeed only handles images.
