### ISSUE TITLE
Parsing img-Tag in two nested span-Tags leads to EmptyStackException

### ISSUE THREAD

**Issue by HerrDietz** [LibrePDF/OpenPDF#376]
While trying to convert some xhtml into a pdf I ran into an issue with a specific combination of html-tags.

I created a minimal testcase:

https://github.com/HerrDietz/OpenPDF/blob/4ee422b5c5ad19f11cc1e3b174d7919b68e17c92/openpdf/src/test/java/com/lowagie/text/html/HtmlParserTest.java#L42

the html 
```html
<span>
  <span>
    <img src="https://any.domain/image.png"/>
  </span>
</span>
```

produces an `EmptyStackException` while being parsed

**Comment by andreasrosdal** [comment]
Pull requests welcome

**Comment by HerrDietz** [comment]
I created a pull request. It is my very first github pull request. Improvements are welcome :)
#377
