### ISSUE TITLE
POM dependency is incorrect

### ISSUE THREAD

**Issue by DanielYWoo** [LibrePDF/OpenPDF#38]
cannot use pdf-xml 1.0.3

**Comment by DanielYWoo** [comment]
Daniels-MacBook-Pro:benchmarkPDF danielwu$ mvn clean package
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building test 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[WARNING] The POM for com.github.librepdf.openpdf:openpdf:jar:1.0.3 is missing, no dependency information available
[WARNING] The POM for com.github.librepdf.openpdf:pdf-rtf:jar:1.0.3 is missing, no dependency information available
[WARNING] The POM for com.github.librepdf.openpdf:pdf-xml:jar:1.0.3 is missing, no dependency information available
Downloading: https://repo.maven.apache.org/maven2/com/github/librepdf/openpdf/pdf-rtf/1.0.3/pdf-rtf-1.0.3.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.985 s
[INFO] Finished at: 2017-09-15T11:36:51+08:00
[INFO] Final Memory: 10M/188M
[INFO] ------------------------------------------------------------------------

**Comment by asturio** [comment]
The correct path should be
https://repo.maven.apache.org/maven2/com/github/librepdf/pdf-rtf/1.0.3/pdf-rtf-1.0.3.jar (without openpdf).

Check the group ID.
It should be
             <groupId>com.github.librepdf</groupId>
And not
             <groupId>com.github.librepdf**.openpdf**</groupId>

You should use
       <dependency>
             <groupId>com.github.librepdf</groupId>
             <artifactId>pdf-xml</artifactId>
             <version>${project.version}</version>
      </dependency>

**Comment by DanielYWoo** [comment]
This is my config

`    <dependency>
      <groupId>com.github.librepdf</groupId>
      <artifactId>openpdf</artifactId>
      <version>1.0.3</version>
      </dependency>
    <dependency>
      <groupId>com.github.librepdf</groupId>
      <artifactId>pdf-html</artifactId>
      <version>1.0.3</version>
    </dependency>

**Comment by asturio** [comment]
Have you found a solution for your problem?

**Comment by asturio** [comment]
Hi @DanielYWoo, do you still have this problem?

**Comment by DanielYWoo** [comment]
No, but I switched to other solutions. Thanks anyway
