### ISSUE TITLE
Big signatures broken since 1.2.18

### ISSUE THREAD

**Issue by lapo-luchini** [LibrePDF/OpenPDF#383]
This apparently harmless change in eb875bc24b688ced9b7ea57e021b1c48cec32ea9 broke (some) digital signatures due to rounding:
```diff
      bf.append('[');
-     for (int i : range) bf.append(i).append(' ');
+     for (long i : range) bf.append(i).append(' ');
      bf.append(']');
```
…because `ByteBuffer.append(int)` exists, while `ByteBuffer.append(long)` does not and thus implicitly uses `ByteBuffer.append(float)`, where the value doesn't fit exactly.

Final effect is a signature where this happens:
```diff
-/Filter/Adobe.PPKLite/Type/Sig/ByteRange [0 178 3704 225636843 ]
+/Filter/Adobe.PPKLite/Type/Sig/ByteRange [0 178 3704 225636848 ]
```
Notice that the fourth number gets rounded up to the next multiple of 16, this breaks the range calculation by actually going after the end of file, but in other instances it is rounded down and we get a signature "not covering the full document" and also broken in any case, as during the signature the range used was right, so the hash is different.

Smallest diff solution is using an explicit cast to double to avoid implicit cast to float:
```diff
      bf.append('[');
-     for (long i : range) bf.append(i).append(' ');
+     for (long i : range) bf.append((double) i).append(' ');
      bf.append(']');
```
…but I think that using `double`s to print `int`s and `long`s is really ugly, and probably re-writing both those methods to print an integral number directly is cleaner.

**Comment by lapo-luchini** [comment]
[According to StackOverflow](https://stackoverflow.com/a/3793950/166524) the first integer that can't fit in a float is 2^24+1 = 16_777_217, which is the max file size that can be safely signed by OpenPDF 1.2.18-1.3.19.

**Comment by lapo-luchini** [comment]
BTW I'd never have understood this if I didn't notice that the IntelliJ debugger was translating code thus:
![image](https://user-images.githubusercontent.com/420454/85418302-e9b2df80-b570-11ea-8dec-02a0da0ee0da.png)

**Comment by andreasrosdal** [comment]
Thanks for reporting. Pull requests welcome.

**Comment by andreasrosdal** [comment]
Could you please create an unit test for this?
That way, we are sure that signatures are correct and that it will not happen again.

**Comment by lapo-luchini** [comment]
@andreasrosdal I did in #386, but I fear that test is fairly specific to this bug, doesn't ensure signatures will always be good.
To do that, I'd say we should use a real signature scheme which actually checks the hash (and that'd be more complex to test).

**Comment by andreasrosdal** [comment]
> should use a real signature scheme which actually checks the hash (and that'd be more complex to test)

Yes, this would be great to have!
