### ISSUE TITLE
Nordic letters "ÅÄÖ" are removed when settings field to text

### ISSUE THREAD

**Issue by fakekowa** [LibrePDF/OpenPDF#385]
Been using this in android trying to stamp text into an acrofield form.setField("myfield", "PÅL") sets the field text to "PL" removing the Å letter.

Best regards
fakekowa

**Comment by asturio** [comment]
Are you using an UTF-8 Font?

**Comment by doobo** [comment]
Can you provide examples of IVS fonts?
[example](https://github.com/LibrePDF/OpenPDF/wiki/Multi-byte-character-language-support-with-TTF-fonts),It is not valid for IVS!

**Comment by codecracker2014** [comment]
@doobo what output you are getting?

**Comment by doobo** [comment]
> @doobo what output you are getting?
[Ming_MSCS_Full.ttf](http://m.ipav.vip/Ming_MSCS_Full.ttf),[output](http://m.ipav.vip/HelloWorld.pdf).
It should output [hello.pdf](http://m.ipav.vip/hello.pdf)!

**Comment by fakekowa** [comment]
@asturio you are correct, i wasn't using a correct font, i'm closing this ticket as resolved, many thanks!
