### ISSUE TITLE
license issue

### ISSUE THREAD

**Issue by lauragarbati** [LibrePDF/OpenPDF#391]
Checking openPDF's license file it seems to be a case of dual license under MPL 2.0 and _LGPL 2.1,_ while in the readme file it is reported that openODF is released under the MPL 2.0 and the _LGPL v3_ licenses. Which is the right one? Furthermore, is your dual licensing designed to let the licensee free to choose between the two ones, or the two licenses must be both accomplished? Thanks in advance

**Comment by Lonzak** [comment]
Parts of your question is answered here. iText=openPDF in this case.
Regarding LGPL 2.1 and 3.0 this should be corrected.
