### ISSUE TITLE
FontSelector.Process should NOT skip characters

### ISSUE THREAD

**Issue by CanyonJ** [LibrePDF/OpenPDF#392]
Currently, if none of the fonts in the font selector list returs true for charExists, the character is skipped. The code should instead choose the first font in the list and use that because generally font fallback will find a viable font on the system to use. Its better than loosing the character entirely. I can reproduce this currently by using Helvetica font, and the string "Greek - Χαίρετε". when I use a FontSelector with just one font, HELVETICA, I lose all the greek characters. If I do NOT use the FontSelector, and just set the paragraph using a HELVETICA font, then I see the text.

**Comment by asturio** [comment]
It is a bit old. Pull request are welcome.

Do you have any sample code for reproducing this?

**Comment by macromogic** [comment]
Hi. I have reproduced this bug:

``` java
import com.lowagie.text.Document;
import com.lowagie.text.Font;
import com.lowagie.text.PageSize;
import com.lowagie.text.pdf.FontSelector;
import com.lowagie.text.pdf.PdfWriter;

import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.OutputStream;

public class MyTest {
    public static void main(String[] args) throws FileNotFoundException {
        String file = "test.pdf";
        OutputStream out = new FileOutputStream(file);

        Document document = new Document(PageSize.A4);
        PdfWriter.getInstance(document, out);
        document.open();

        FontSelector selector = new FontSelector();
        selector.addFont(new Font(Font.HELVETICA));
        document.add(selector.process("Greek - Χαίρετε"));

        document.close();
    }
}
```

As stated by the author, the greek characters will be lost because _Helvetica_ does not contain the characters, and there is no font fallback.

Now I am working on this issue.

**Comment by Wugengxian** [comment]
It is cause by that Font.HELVETICA don't decode Χαίρετε. A good idea is to add `selector.addFont(new Font(Font.SYMBOL));` after selector.addFont(new Font(Font.SYMBOL)), when Font.HELVETICA don't decode and it will use Font.SYMBOL.

**Comment by macromogic** [comment]
@Wugengxian Yes. But you should not assume the users have full knowledge of the fonts being used. Chances are that some of the characters fail to be rendered by any of the fonts specified in the selector. A font fallback with a warning message can at least make sure that all contents are shown in the document, and remind the user to specify other fonts if necessary.

**Comment by CanyonJ** [comment]
In our primary use case we don’t know the language entered. We rely on font fallback to work if our preferred font won’t support the characters passed in. 

On Saturday, April 24, 2021, 9:48 PM, Weijie Huang ***@***.***> wrote:




@Wugengxian Yes. But you should not assume the users have full knowledge of the fonts being used. Chances are that some of the characters fail to be rendered by any of the fonts specified in the selector. A font fallback with a warning message can at least make sure that all contents are shown in the document, and remind the user to specify other fonts if necessary.

**Comment by Wugengxian** [comment]
@macromogic what you said is very reasonable. I think the better pull request is to add default font in fonts of `fontselector`, everytime we call add method that we will call fonts.add(len-1). The least change makes better.

**Comment by macromogic** [comment]
@Wugengxian Have you noticed the info message when a font fallback happens? I prefer keeping this message to notify the user that the default font is adopted.
Although I have not read other parts of this project, I don't think it is a good idea to add the default font _here_. Also,  I believe adding an element at index `len-1` is slower than just appending the element.
