### ISSUE TITLE
how to compress images from camera and gallery ,PDF size by adding one picture is more than 1mb 

### ISSUE THREAD

**Issue by phoneix1221** [LibrePDF/OpenPDF#393]
need a way to decrease PDF file size by compressing image  and processing time of creating PDF with images with a minimal loss of image quality in android . please help

**Comment by asturio** [comment]
You probably need some kind of library to reduce the size (scaling) of the image you want to embed first. Have you tried something like this?

Make something like https://stackoverflow.com/questions/3629601/image-manipulation-using-java ?
`image.getScaledInstance()` may help.
