### ISSUE TITLE
which LGPL?

### ISSUE THREAD

**Issue by lauragarbati** [LibrePDF/OpenPDF#396]
Dear all, with a previous issue I’ve asked some clarification about the right license actually applied to OpenPDF (LGPL 2 or 3.0) and you kindly and promptly sent a feedback also about this point, saying that it was something to be corrected. I’m sorry to bother again, but I’d like to re-use your product and I’d like to set the Third Party Notice correctly, so while you fix the point can you kindly clarify which license we have to declare? (i suppose LGPL 3.0 but just to be sure..) Thanks in advance.

**Comment by andreasrosdal** [comment]
It's great that you want to use OpenPDF in your project.

What are the practical differences between version 2 and 3 of the LGPL?

You are free to choose between using version 2 and 3. Note this text in the source code license:

"This library is free software; you can redistribute it and/or modify it
 * under the terms of the MPL as stated above or under the terms of the GNU
 * Library General Public License as published by the Free Software Foundation;
 * either version 2 of the License, or any later version."
