### ISSUE TITLE
How to add Chunk with chinese?

### ISSUE THREAD

**Issue by RobinChien** [LibrePDF/OpenPDF#397]
I try to write Chinese into pdf file.
I have read this post [How to add watermarker use chinese?](https://github.com/LibrePDF/OpenPDF/issues/293)

So I add the NotoSansTC and NotoSansSC in to fonts folder
![image](https://user-images.githubusercontent.com/22998999/90007060-9e918f00-dccc-11ea-8dac-b54613ac1c12.png)

And create them by `BaseFont.createFont()`
![image](https://user-images.githubusercontent.com/22998999/90007153-cc76d380-dccc-11ea-8dc1-0c06ac160263.png)

Then write the paragraph with the custom font like this
![image](https://user-images.githubusercontent.com/22998999/90020215-2209ab00-dce2-11ea-8add-6fd990595d4b.png)

But the result of pdf content didn't present the Chinese `中文`.
![image](https://user-images.githubusercontent.com/22998999/90020589-a3613d80-dce2-11ea-8bd1-8d115620ed06.png)

Did I make any mistake? I really need help. Thanks.

**Comment by DarthCoder117** [comment]
Same question here, but I need to display Japanese.

**Comment by asturio** [comment]
The code seems correct, and I would expect, that glyphs should be rendered right.

**Comment by asturio** [comment]
PR are welcome!

**Comment by asturio** [comment]
I just managed to create a document using this Font:
https://github.com/adobe-fonts/source-han-serif/blob/release/OTF/SimplifiedChinese/SourceHanSerifSC-Regular.otf

And using this code:
```java
package com.lowagie.examples.fonts.getting;

import java.io.FileOutputStream;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;

import com.lowagie.text.Chunk;
import com.lowagie.text.Document;
import com.lowagie.text.Font;
import com.lowagie.text.pdf.BaseFont;
import com.lowagie.text.pdf.PdfWriter;

public class Chinese {

    public static void main(String[] args) throws IOException {
        // step 1: creation of a document-object
        Document document = new Document();
        // step 2: creation of the writer
        final Path target = Paths.get( "target", Chinese.class.getSimpleName() + ".pdf");
        Files.createDirectories(target.getParent());
        PdfWriter.getInstance(document, new FileOutputStream(target.toFile()));
        // step 3: we open the document
        document.open();
        // step 4: we add content to the document
        final String fontFile = "SourceHanSerifSC-Regular.otf";
        BaseFont cnFont = BaseFont.createFont(fontFile, BaseFont.IDENTITY_H, BaseFont.NOT_EMBEDDED);
        Chunk chunk = new Chunk("Chinese: 中文", new Font(cnFont, 12, Font.NORMAL));
        document.add(chunk);
        // step 5: we close the document
        document.close();
    }
}

```
Maybe is the font you are using not really working.

Can you try this code?

**Comment by asturio** [comment]
The PR #469 is an example how this can be done.
