### ISSUE TITLE
Remove dependency to juniversalchardet or make it an optional dependency

### ISSUE THREAD

**Issue by mwgmnn** [LibrePDF/OpenPDF#400]
Dear all,

is it possible to remove the dependency to this extra library? I see that it is used only in one place, to get the encoding of an xml-document from the bom header, see com.lowagie.text.xml.simpleparser.SimpleXMLParser.parse(...)
The logic in UniversalDetector.detectCharsetFromBOM(...) is not so special and complex and is not prone to be changed in the future. I know that reusing sourcecode is good practice. But in this situation copying the code is acceptable in my opinion because of the advantages of fewer dependencies and lesser efforts in maintaining an extra library and so on.

See also this merge-request: https://github.com/LibrePDF/OpenPDF/pull/124 where @andreasrosdal asked in the same direction...

Cheers,
Michael

**Comment by asturio** [comment]
This should be fixed now.
