### ISSUE TITLE
1.3.21 release

### ISSUE THREAD

**Issue by andreasrosdal** [LibrePDF/OpenPDF#404]
The OpenPDF 1.3.21 release. 

@asturio can you do it?

**Comment by asturio** [comment]
Status: I'm having some problems with my public gpg-key. Just uploaded it to keyserver.ubuntu.com. I think I need to wait some time, till the key is "known", c64beb3e97c774f7

**Comment by asturio** [comment]
Ok, everything is done, I hope.
