### ISSUE TITLE
Add Text extraction tutorial example to Wiki

### ISSUE THREAD

**Issue by andreasrosdal** [LibrePDF/OpenPDF#407]
OpenPDF supports text extraction from PDF files.

Add Text extraction tutorial example to the wiki:
https://github.com/LibrePDF/OpenPDF/wiki/Text-Extraction

This seems to be something people want which would be useful to document. 
So please help improve the documentation of OpenPDF in the Wiki. https://github.com/LibrePDF/OpenPDF/wiki

**Comment by jabhatfield** [comment]
I've added a text extraction example to my fork. GitHub doesn't support pull requests for wikis so it would have to be merged in (or just copy the markup): https://github.com/jabhatfield/OpenPDF/wiki/Text-Extraction

If it looks ok I can also add the example to pdf-toolbox and create a PR for it.
