### ISSUE TITLE
ConcurrentModificationException in FontFactory

### ISSUE THREAD

**Issue by giangnvt** [LibrePDF/OpenPDF#408]
I have ConcurrentModificationException when call FontFactory.getFont() function. Below is stacktrace.
Very rare to happen, but it exists.
Version: 1.3.16

`java.util.ConcurrentModificationException: null 	at java.base/java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1042) 	at java.base/java.util.ArrayList$Itr.next(ArrayList.java:996) 	at com.lowagie.text.FontFactoryImp.getFont(FontFactoryImp.java:181) 	at com.lowagie.text.FontFactoryImp.getFont(FontFactoryImp.java:154) 	at com.lowagie.text.FontFactory.getFont(FontFactory.java:140) 	at
`

P/S: It same to origin from the based iText version, as described here:
https://github.com/opensagres/xdocreport/issues/59

**Comment by exuvo** [comment]
If you load all your fonts first in a single threaded context it should then be safe to use multithreaded later.

**Comment by asturio** [comment]
Do you have some sample code, that provoke this issue?

**Comment by asturio** [comment]
Is the error present in the latest Version?
