### ISSUE TITLE
Build fails on JDK 15 due to maven bundle plugin error

### ISSUE THREAD

**Issue by prashantbhat** [LibrePDF/OpenPDF#413]
Using JDK 15, the project build command `mvn clean install` fails with the following error:

```
[INFO] --- maven-bundle-plugin:4.2.0:manifest (bundle-manifest) @ openpdf ---
[ERROR] An internal error occurred
java.util.ConcurrentModificationException
    at java.util.TreeMap.callMappingFunctionWithCheck (TreeMap.java:742)
    at java.util.TreeMap.computeIfAbsent (TreeMap.java:596)
    at aQute.bnd.osgi.Jar.putResource (Jar.java:288)
    at aQute.bnd.osgi.Jar$1.visitFile (Jar.java:202)
    at aQute.bnd.osgi.Jar$1.visitFile (Jar.java:177)
```

Updating `maven-bundle-plugin` to it's latest release `5.1.1` is solving this issue as I tested locally.

And I notice that there are few other maven plugins that can be updated. Enabling [Dependabot](https://github.blog/2020-06-01-keep-all-your-packages-up-to-date-with-dependabot/) for this project would automatically create PRs to update external dependencies such as maven plugins, libraries.

**Comment by andreasrosdal** [comment]
pull requests welcome ☺️

**Comment by prashantbhat** [comment]
@andreasrosdal I've created PR #415 to fix this issue along with other dependency updates, please review.
