### ISSUE TITLE
since 1.3.22 setColor(java.awt.Color.SOMECOLOR) does not work anymore in jpms program

### ISSUE THREAD

**Issue by chrismaster** [LibrePDF/OpenPDF#439]
in 1.3.20
fontCell.setColor(Color.BLACK) works
in 1.3.21 and 1.3.22 I get
error: cannot access Color
                    fontCell.setColor(BLACK);       
                            ^
  class file for java.awt.Color not found

in module-info.java is
requires java.desktop; 

without module-info.java it compiles....

**Comment by chrismaster** [comment]
fontCell.setColor(0,0,0);
compiles too

**Comment by chrismaster** [comment]
Color BLACK = Color.BLACK;
compiles too, so java.awt.Color is accessible
but if i add
fontCell.setColor(BLACK); 
it gives 
error: cannot access Color
                    fontCell.setColor(BLACK);       
                            ^
  class file for java.awt.Color not found

**Comment by asturio** [comment]
Thanks. Pull Requests welcome!

**Comment by chrismaster** [comment]
Sorry, got no real java skills. And my git skills are 0.
I cloned openpdf and added to 
modules-info.java
requires java.desktop;

with this new openpdf-1.3.23-SNAPSHOT.jar
fontCell.setColor(java.awt.Color.SOMECOLOR) gives no error

in the module java.desktop is java.awt.Color.*
requires static java.desktop; would also do the job.....

**Comment by chrismaster** [comment]
#440

**Comment by asturio** [comment]
Ok, I'll make a fix for it.
