### ISSUE TITLE
Accented Letters composed of Unicode base letter and combining accent are rendered incorrectly. 

### ISSUE THREAD

**Issue by vk-github18** [LibrePDF/OpenPDF#442]
**Describe the bug**

The position of the accents is incorrect for most of the character sequences 
defined in the following specification:

DIN SPEC 91379: Characters in Unicode for the electronic processing of names 
and data exchange in Europe; with digital attachment
https://www.xoev.de/downloads-2316#StringLatin
https://www.din.de/de/wdc-beuth:din21:301228458

E.g. with 0041 030B LATIN CAPITAL LETTER A WITH COMBINING DOUBLE ACUTE ACCENT 
the accent appears at the right hand side of the letter A, not above the 
letter A.

**To Reproduce**
The output of LibrePdf/OpenPdf 1.3.22 is appended in [din-spec-91379-openpdf.pdf](https://github.com/LibrePDF/OpenPDF/files/5453965/din-spec-91379-openpdf.pdf), 
which is created by running [OpenPdfTest.java](https://github.com/LibrePDF/OpenPDF/files/5453964/OpenPdfTest.java.txt) using [pdf-form.pdf](https://github.com/LibrePDF/OpenPDF/files/5453962/pdf-form.pdf).

**Expected behavior**
The correct rendering should look like the output of Harfbuzz hb-view 2.6.8 
for [din-spec-91379-hb-view-2.6.8.txt](https://github.com/LibrePDF/OpenPDF/files/5453967/din-spec-91379-hb-view-2.6.8.txt), see [din-spec-91379-hb-view-2.6.8.pdf](https://github.com/LibrePDF/OpenPDF/files/5453968/din-spec-91379-hb-view-2.6.8.pdf). 
Harfbuzz uses the info in the OpenType GPOS table for positioning.

**Screenshots**
none

**System (please complete the following information):**
 - OS:  Windows 10
 - Used Font: NotoSans, NotoSansMath, see https://github.com/googlefonts/noto-fonts/tree/master/hinted/ttf

**Additional context**
See also
https://issues.apache.org/jira/browse/PDFBOX-4951
https://issues.apache.org/jira/browse/FOP-2969
https://github.com/googlefonts/noto-fonts/issues/1882

**Comment by asturio** [comment]
Pull Request are welcome :-) !
