### ISSUE TITLE
Compilation error on Java 7

### ISSUE THREAD

**Issue by andreasrosdal** [LibrePDF/OpenPDF#45]
The master branch of OpenPDF doesn't compile with Java 7. If Java 8 now is a requirement, then it would be nice if the README could be updated to show that OpenPDF now requires Java 8.

This is the compilation error I get with Java 7:

[ ERROR] /C:/OpenPDF-master/pdf-html/src/test/java/com/lowagie/text/html/simpleparser/FactoryPropertiesTest.java:[24,19] cannot access java.util.stream.Stream
  class file for java.util.stream.Stream not found
[INFO] 1 error
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] OpenPDF - Free and Open PDF ........................ SUCCESS [  1.030 s]
[INFO] openpdf ............................................ SUCCESS [ 31.981 s]
[INFO] pdf-xml ............................................ SUCCESS [  2.155 s]
[INFO] pdf-rtf ............................................ SUCCESS [  7.805 s]
[INFO] pdf-html ........................................... FAILURE [  0.687 s]
[INFO] pdf-swing .......................................... SKIPPED
[INFO] pdf-toolbox ........................................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 45.628 s
[INFO] Finished at: 2017-10-24T12:38:45+02:00
[INFO] Final Memory: 41M/613M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.2:testCompile (default-testCompile) on project pdf-html: Compilation failure
[ERROR] /C:/OpenPDF-master/pdf-html/src/test/java/com/lowagie/text/html/simpleparser/FactoryPropertiesTest.java:[24,19] cannot access java.util.stream.Stream
[ERROR]   class file for java.util.stream.Stream not found

**Comment by andreasrosdal** [comment]
This can also be seen here: https://jitpack.io/com/github/librepdf/openpdf/1.0.3/build.log

**Comment by asturio** [comment]
@LibrePDF/openpdf:
Should we try to support Java 7 too? Java 7 is byte code compatible with Java 6, but Java 8 not anymore.
Any votes? The code is really old, no generics, so if we stick with Java 7 is a nice improvement :-). What do you think?

**Comment by kulatamicuda** [comment]
Yes, we should as Oracle offers extended support for java 7  till Jul 2022. Of course it should not limit future updates, but as you have allready written, codebase is pretty old. So avoid lambda in new code and everything should be ok.

**Comment by tlxtellef** [comment]
I suspect the culprit is `org.assertj:assertj-core` as version `3.X.X` is Java 8 and version `2.X.X` is Java 7.

**Comment by tlxtellef** [comment]
We should probably change the JDK Travis uses to Java 7 to make sure this project is in fact Java 7 compatible.

**Comment by andreasrosdal** [comment]
Thanks.
