### ISSUE TITLE
Tab character is not visible in the PDF generated as glyph substitution not working

### ISSUE THREAD

**Issue by PallaviSaini** [LibrePDF/OpenPDF#454]
**Bug**
Tab character is not visible in the PDF generated.
This is due to glyph substitutions are not done for tab character as per the TTF file.
Below is link to typography specs:
https://docs.microsoft.com/en-us/typography/opentype/spec/gsub

**Below is code to Reproduce**
package test;

import java.io.BufferedOutputStream;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.net.URL;

import org.apache.poi.util.IOUtils;
import org.apache.poi.xwpf.converter.pdf.PdfConverter;
import org.apache.poi.xwpf.converter.pdf.PdfOptions;
import org.apache.poi.xwpf.usermodel.XWPFDocument;

import fr.opensagres.xdocreport.core.XDocReportException;
import fr.opensagres.xdocreport.document.IXDocReport;
import fr.opensagres.xdocreport.document.registry.XDocReportRegistry;
import fr.opensagres.xdocreport.template.IContext;
import fr.opensagres.xdocreport.template.TemplateEngineKind;
import fr.opensagres.xdocreport.template.formatter.FieldsMetadata;
/**	
 * 
 * @author pallavi.saini 
 *
 */
public class OpenPdf {

	public static void main(String[] args) throws XDocReportException, IOException {
		PdfOptions options = PdfOptions.create();
		String templatePath = "D:\\Workspace\\ThankYouNote_Template.docx";
		URL url = new File(templatePath).toURI().toURL();
		InputStream inputStream = url.openStream();
		IXDocReport xdocReport = XDocReportRegistry.getRegistry().loadReport(inputStream, null,
                TemplateEngineKind.Freemarker, false);
		FieldsMetadata metadata = xdocReport.createFieldsMetadata();
	    metadata.setTemplateEngineKind("Freemarker");
	    xdocReport.setFieldsMetadata(metadata);
		IContext context = xdocReport.createContext();
		context.put("name", "RAJ\tVIHAR");
		ByteArrayOutputStream outputStream = new ByteArrayOutputStream();
		xdocReport.process(context, outputStream);

		XWPFDocument document = new XWPFDocument(new ByteArrayInputStream(outputStream.toByteArray()));
		ByteArrayOutputStream out = new ByteArrayOutputStream();
		PdfConverter.getInstance().convert(document, out, options);
		writeToPdfFile(out.toByteArray(), "D:\\Workspace\\ThankYouNote_Template.pdf");

	}

	private static void writeToPdfFile(byte[] fileContent, String path) {

		BufferedOutputStream bs = null;
		FileOutputStream fs = null;
		try {

			fs = new FileOutputStream(new File(path));
			bs = new BufferedOutputStream(fs);
			bs.write(fileContent);
			bs.close();
			bs = null;
		} catch (Exception e) {
			e.printStackTrace();
		} finally {
			IOUtils.closeQuietly(fs);
		}

	}

}

**Expected behavior**
The text should be visible as "Raj   Vihar" instead of "RajVihar". The rendered text in PDF should have a tab character in it.

**Screenshot of current behaviour**

![image](https://user-images.githubusercontent.com/22634418/98930666-f1b0f300-2502-11eb-9bc8-20bed453ef8a.png)

**System:**
 - OS: Windows
 - Used Font: Times New Roman

**Comment by Wugengxian** [comment]
@asturio @PallaviSaini I have fix it [solution](https://github.com/LibrePDF/OpenPDF/pull/519). In the futher, I will study how to let other fonts to encode \t and give a better solution.

**Comment by asturio** [comment]
Thanks for the contribution!
