### ISSUE TITLE
Discussion: detatch OpenPdf from the fork network

### ISSUE THREAD

**Issue by asturio** [LibrePDF/OpenPDF#459]
Hi there,

I'd like to have OpenPDF as a parent project in GitHub, so we can promote it better. Although it is a fork of other projects, like @rtfarte / OpenPDF, @kulatamicuda /iText-4.2.0 and @daviddurand / iText-4.2.0.

The main advantage would be, that the project will receive a "community" entry in insights. I have started little issue in the GitHub Support community, and this is the suggested solution.

https://github.community/t/insights-community-is-not-present/138582

As this is not "my" project, here the question if this is good or bad idea.

I think we could get more contributors if this step is taken.

Please contribute to this discussion.

Probably other people interested in this question: @bengolder

**Comment by rtfarte** [comment]
As I'm sure everyone knows, I haven't been very active at all in quite some time. I'm all for getting additional contributors to the project and watching it grow, though. Whatever I can do to help with that, I'm all for it. Please let me know what I need to do to get this to happen.

**Comment by andreasrosdal** [comment]
Detatching OpenPDF allows using https://lgtm.com , which hasn't been possible yet because this is a fork.

**Comment by asturio** [comment]
Nice, didn't knew that. It seems a good idea then. Ok, I'll see to continue on this one.

**Comment by noavarice** [comment]
I think OpenPDF can be considered separate project, meaning not a fork in terms of Github projects. However, having documentation links to the projects from which OpenPDF originates would be great - at least for history

**Comment by asturio** [comment]
OpenPDF ist now a parent project. The ancestor projects are referenced in the README.md.
