### ISSUE TITLE
Migrate from travis-ci.org to GitHub actions.

### ISSUE THREAD

**Issue by andreasrosdal** [LibrePDF/OpenPDF#461]
It looks like travis-ci.org is going away. From
https://docs.travis-ci.com/user/migrate/open-source-repository-migration/#frequently-asked-questions
Q. What will happen to travis-ci.org after December 31st, 2020?
A. Travis-ci.org will be switched to a read-only platform, allowing you to
see your jobs build history from all repositories previously connected to
travis-ci.org.

Suggestion:  Migrate the CI job to GitHub actions.

**Comment by asturio** [comment]
I just added GitHub CI to the project. I'll still have to do some tuning, before closing this issue.

**Comment by asturio** [comment]
We are now using the GitHub Actions: https://github.com/LibrePDF/OpenPDF/actions
