### ISSUE TITLE
Missing text from pdf file when calling PDFReader getPageContent

### ISSUE THREAD

**Issue by chjtrifork** [LibrePDF/OpenPDF#463]
[testGetEmptyDDCard.pdf](https://github.com/LibrePDF/OpenPDF/files/5672355/testGetEmptyDDCard.pdf)
**Describe the bug**
Parts of the text is missing when PDFReader opens a pdf file generated with OpenPDF, using the method getPageContent(). The file contains the expected contents when opening it in Acrobat Reader. The same happens when using PDFTextExtractor.getTextFromPage(). 

**To Reproduce**
(see attached testfile)
The text "Ingen dosisdispenserings-data fundet" is neither returned from the PDFReader.getPageContent(1) nor pdfTextExtractor.getTextFromPage(1).
        
```
   PdfReader reader = new PdfReader("testGetEmptyDDCard.pdf");
   int pages = reader.getNumberOfPages();
   PdfTextExtractor pdfTextExtractor = new PdfTextExtractor(reader);
   StringBuilder text = new StringBuilder();
   for (int page = 1; page <= pages; page++) {
      text.append(new String(pdfTextExtractor.getTextFromPage(page)));
    }
    
   assertTrue(text.toString().contains("Ingen dosisdispenserings-data fundet"));   // This assertion fails

```
**Expected behavior**
I would have expected, that all text are returned, including "Ingen dosisdispenserings-data fundet" from getTextFromPage so the assertion does no longer fail.

**System (please complete the following information):**
 - OS: Windows 10 + Linux, JDK8
 - Used Font: BaseFont.createFont(BaseFont.HELVETICA, "ISO-8859-1", BaseFont.NOT_EMBEDDED)
 - OpenPDF 1.3.23 is used.

**Comment by mkl-public** [comment]
The missing text is drawn using a composite font with **Identity-H** encoding while the other text is drawn using simple fonts. Quite likely, therefore, this problem is related to https://github.com/LibrePDF/OpenPDF/issues/330

**Comment by chjtrifork** [comment]
> The missing text is drawn using a composite font with **Identity-H** encoding while the other text is drawn using simple fonts. Quite likely, therefore, this problem is related to #330

Thank you very much for the reply! I created the specific text with the same font as the other texts in the pdf, and now the text is returned from the reader as expected.

(I am a bit unsure about the workflow regarding the issue, should I close it or would you like to keep it open?)

**Comment by mkl-public** [comment]
> (I am a bit unsure about the workflow regarding the issue, should I close it or would you like to keep it open?)

As the underlying issue is still there (you only found a work-around for your use case, not a fix for the actual issue), probably not closing as fixed. Maybe closing as duplicate of #330 would make sense.

**Comment by chjtrifork** [comment]
Duplicate of #330
