### ISSUE TITLE
Tamil Font Display

### ISSUE THREAD

**Issue by bk-oasys** [LibrePDF/OpenPDF#495]
We are the library for export to pdf, not displaying tamil text in the odf

**Comment by asturio** [comment]
Can you elaborate the problem a bit more? Are you embeding the font?

**Comment by bk-oasys** [comment]
We are having the text in database andbare embedding , but in the final pdf it is empty

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by asturio** [comment]
Do you have some sample code for that?

**Comment by asturio** [comment]
Please note that the encoding of the text should match the encoding of the font. What are the encodings you are using?

**Comment by codecracker2014** [comment]
@bk-oasys please try to run example documented at below link with Tamil text and Tamil Font.
https://github.com/LibrePDF/OpenPDF/wiki/Multi-byte-character-language-support-with-TTF-fonts

**Comment by bk-oasys** [comment]
Thanks, will try this and revert RegardsBhaskar+91 7401439799Skype : bhaskar1970Sent from Mail for Windows 10 From: Gajendra kumarSent: 28 February 2021 17:10To: LibrePDF/OpenPDFCc: bk-oasys; MentionSubject: Re: [LibrePDF/OpenPDF] Tamil Font Display (#495) @bk-oasys please try to run example documented at below link with Tamil text and Tamil Font.https://github.com/LibrePDF/OpenPDF/wiki/Multi-byte-character-language-support-with-TTF-fonts—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by asturio** [comment]
Hi @bk-oasys , do you have any success feedback on this? Can we close this issue?

**Comment by bk-oasys** [comment]
Yes Sir, over the weekend we have manged to sort out, much appreciated RegardsBhaskar+91 7401439799Skype : bhaskar1970Sent from Mail for Windows 10 From: asturioSent: 06 March 2021 17:21To: LibrePDF/OpenPDFCc: bk-oasys; MentionSubject: Re: [LibrePDF/OpenPDF] Tamil Font Display (#495) Hi @bk-oasys , do you have any success feedback on this? Can we close this issue?—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
