### ISSUE TITLE
FontAwesome icons bundled in openpdf

### ISSUE THREAD

**Issue by santeriv** [LibrePDF/OpenPDF#5]
Hi I got this idea from Vaadin:

Could FontAwesome icons be also added similar way to openpdf?

https://github.com/vaadin/framework/blob/7.7/scripts/generateFontAwesomeEnum.sh
https://github.com/vaadin/framework/blob/7.7/server/src/main/java/com/vaadin/server/FontAwesome.java
https://github.com/vaadin/framework/blob/7.7/server/src/main/java/com/vaadin/server/FontAwesome.java#L773
https://github.com/vaadin/framework/blob/7.7/server/src/main/java/com/vaadin/server/GenericFontIcon.java#L94

So if openpdf supports html evaluation this should be doable?

I've used some years ago commercial one (iText) with xhtml,css pipelines but don't know how exactly html is converted to pdf with openpdf if it is possible?

ref: http://fontawesome.io/

**Comment by andreasrosdal** [comment]
This is a good idea. Perhaps you could submit a pull request?

**Comment by santeriv** [comment]
Thanks for quick response. I'd like to do it unless you are already holding your breath. Might take a week or so to find a gap. :)

**Comment by bengolder** [comment]
@santeriv did you ever take a shot at this? Should we keep this issue open for further discussion?

**Comment by santeriv** [comment]
@bengolder good that you asked. I overestimated my available time. I did test the .sh script it seems to be a good base yet I felt a bit unsure whether this was doable at all. Thus, this issue can remain Open.
