### ISSUE TITLE
NullPointerException using PdfCopyFields (broken since v1.1.0)

### ISSUE THREAD

**Issue by StefanOltmann** [LibrePDF/OpenPDF#500]
**Describe the bug**

Here is a sample document with a table of contents on the first page: [openpdf_bug_test.pdf](https://github.com/LibrePDF/OpenPDF/files/6100746/openpdf_bug_test.pdf)

I want to copy only the first page into a new file using code like this...

```
            InputStream stream = Main.class.getResourceAsStream("openpdf_bug_test.pdf");

            PdfReader reader = new PdfReader(stream);

            byte[] bytes;

            try (ByteArrayOutputStream baos = new ByteArrayOutputStream()) {

                PdfCopyFields pdfCopyFields = new PdfCopyFields(baos);

                pdfCopyFields.addDocument(reader, "1"); // <-- just the table of contents

                pdfCopyFields.close(); // <-- bang

                baos.flush();

                bytes = baos.toByteArray();
            }

            try (OutputStream os = new FileOutputStream(new File("output.pdf"))) {
                os.write(bytes);
            }
```

... and get this exception:

```
java.lang.NullPointerException
	at com.lowagie.text.pdf.PdfWriter$PdfBody.add(PdfWriter.java:394)
	at com.lowagie.text.pdf.PdfWriter$PdfBody.add(PdfWriter.java:390)
	at com.lowagie.text.pdf.PdfWriter.addToBody(PdfWriter.java:829)
	at com.lowagie.text.pdf.PdfCopyFieldsImp.closeIt(PdfCopyFieldsImp.java:408)
	at com.lowagie.text.pdf.PdfCopyFieldsImp.close(PdfCopyFieldsImp.java:368)
	at com.lowagie.text.pdf.PdfCopyFields.close(PdfCopyFields.java:162)
	at Main.main(Main.java:30)
```

Since OpenPDF v1.1.0 it only works if I specify "1-2" as a range because otherwise a NullPointerException occurs due to the missing page refs in the table of contents.

Up to v1.0.5 it was possible to just copy range "1" and the missing page refs will be ignored.

**To Reproduce**

Full reproducer project:
[OpenPdfBugReproducer.zip](https://github.com/LibrePDF/OpenPDF/files/6100688/OpenPdfBugReproducer.zip)

**Expected behavior**

If a page has a reference to another page that's not part of the exported range this reference should just be ignored or stripped out. This seems to be what happens in version 1.0.5 and the old iText library.

Maybe you won't want to allow this per default, but then there should be a way better exception than a NullPointerException. But I would still need an option to force that copy even if page references get lost.

**System (please complete the following information):**
 - OS: Windows
 - Used Font: Not relevant

**Comment by asturio** [comment]
Pull requests are welcome!

**Comment by Wugengxian** [comment]
> Pull requests are welcome!
I have fixed it [solution](https://github.com/LibrePDF/OpenPDF/pull/515)

**Comment by Wugengxian** [comment]
@StefanOltmann I have fixed it, you can find the [pull request](https://github.com/LibrePDF/OpenPDF/pull/515)

**Comment by StefanOltmann** [comment]
> @StefanOltmann I have fixed it, you can find the [pull request](https://github.com/LibrePDF/OpenPDF/pull/515)

Thank you! 😀

**Comment by StefanOltmann** [comment]
@asturio Nice. 

When will the next release to maven central happen?

**Comment by asturio** [comment]
Let's see if I can go through some PR this weekend, so I can release in the next week. :-). It's great to have so much contribution.
