### ISSUE TITLE
Wiki page for Correct positioning of accents, DIN SPEC 91379, non-latin scripts

### ISSUE THREAD

**Issue by vk-github18** [LibrePDF/OpenPDF#501]
I would like to contribute to the wiki.

You find the proposed changes in https://github.com/vk-github18/OpenPDF/wiki
I added one page "Accents,-DIN-SPEC-91379,-non-latin-scripts.md"
and changed "Tutorial.md".

I found no way to change the wiki directly or create a pull request for the wiki

**Comment by asturio** [comment]
Hi @vk-github18 , I changed access to the Wiki to public, so OpenPDF users and contributors can share their knowledge easier.

I hope we don't get spammed. Can you check if you can write now?

**Comment by vk-github18** [comment]
Hi @asturio , thanks, I could add the new page.

**Comment by vk-github18** [comment]
New page added and included a link in "Tutorial.md"
