### ISSUE TITLE
NPE when exporting JasperPrint to PDF/A document

### ISSUE THREAD

**Issue by VedranSlankovic** [LibrePDF/OpenPDF#502]
Hello,

I'm using JasperReports with OpenPDF and I can not export JasperPrint to PDF/A document.

I'm using jasperreports exportReport() method from JRPdfExporter which calls method  com.lowagie.text.pdf.PdfWriter.getInstance(Document document, OutputStream os) in which object com.lowagie.text.pdf.PdfDocument is constructed with constructor :

```
    public PdfDocument() {
        super();
    }
```
Problem is that NPE occurs when XMPMeta object is created and populated with properties that consists of XML namespaces, names and values. Two of these properties names are CreateDate and ModifiedDate and their values are read from PdfDictionary com.lowagie.text.pdf.PdfWriter.getInfo() object. These values don't exist in PdfDictionary.

Constructor of net.sf.jasperreports.engine.export.XmpWriter class:

```
    XmpWriter(PdfWriter pdfWriter)
    {
        this.pdfWriter = pdfWriter;
        this.info = pdfWriter.getInfo();
    }
```

NPE occurs at these lines of code:
```
xmp.setProperty(XMPConst.NS_XMP, XMP_CREATE_DATE, ((PdfDate) info.get(PdfName.CREATIONDATE)).getW3CDate());
xmp.setProperty(XMPConst.NS_XMP, XMP_MODIFY_DATE, ((PdfDate) info.get(PdfName.MODDATE)).getW3CDate());
```

Can you change constructor to (like in iText versions 2.7.1 and 4.2.1) : 
```
    public PdfDocument() {
        super();
        addProducer();
        addCreationDate();
    }
```

I can create Pull-request if needed.

**Comment by andreasrosdal** [comment]
Thanks, pull requests welcome!
