### ISSUE TITLE
Font Color on PdfPCell increases the PDF file size more than 2x times

### ISSUE THREAD

**Issue by ambrish24** [LibrePDF/OpenPDF#503]
I have created a Font in this way.

`Font tableHeaderFont = new Font(Font.HELVETICA, 8, Font.NORMAL, Color.WHITE);`

and then using it inside PdfPCell with Phrase.

`PdfPCell hcell = new PdfPCell(new Phrase("Column A", tableHeaderFont));`

I am showing table header on every page.

Now if I drop the Font Color, it generates the PDF file of size 10 MB but **when Color is provided it generates PDF file of size 24 MB**. There are **around 1400** page in PDF document.

Is there any better way to specify Font Color on PdfPCell level?

**Comment by ambrish24** [comment]
In addition to this, when I try to merge these pdf documents using `PdfSmartCopy` it takes around 4 GB memory usage.

**Comment by asturio** [comment]
Thank you for reporting.
Maybe this is only consequence that the colors are added in every page. This need some investigation.

Pull requests are welcome!

**Comment by ambrish24** [comment]
The same goes for Margins and Background Color. When I left the margins at top, bottom, left and right of PDF document, the size of PDF file increases exponentially.

@asturio If you need any further information on this, feel free to reach me.

**Comment by aakashgarg19** [comment]
Facing same issue, any updates on this?

**Comment by ambrish24** [comment]
@asturio 

With iText 5+, When I use the `BaseColor` class then I am getting the same size of pdf file with or without Font Color.

`Font tableHeaderFont = new Font(Font.HELVETICA, 8, Font.NORMAL, BaseColor.WHITE);`

Do we have any alternative of `iText's BaseColor `class in OpenPDF or iText4?

**Comment by aakashgarg19** [comment]
@asturio can you add BaseColor support?

**Comment by mkl-public** [comment]
It's not a matter of whether it's `BaseColor` or `Color`, it's a matter of how the color values internally are used. So just like @asturio said, _This need some investigation_ and then some optimization.

**Comment by aakashgarg19** [comment]
Any idea by when we can hear around this?

**Comment by ambrish24** [comment]
> It's not a matter of whether it's `BaseColor` or `Color`, it's a matter of how the color values internally are used. So just like @asturio said, _This need some investigation_ and then some optimization.

Completely agree. It's a matter of how **iText** processing and applying the color on PDF.

**Comment by Wugengxian** [comment]
@ambrish24 can you give some test cases? I want to fix this issue.

**Comment by aakashgarg19** [comment]
@Wugengxian create a pdfptable add a header in it, it should be more than 10000 pages, have wide margins, have custom font, have background color added only to header row. have different font size for header and normal rows. And you should be able to reproduce the scenario. You will see huge gap just with removing/adding font and background colors. Margin also increases it a lot.

**Comment by Wugengxian** [comment]
@aakashgarg19 I have tried to reproduce the scenario, but I don't see huge gap. this is my code.

`public static void main(String[] args) throws FileNotFoundException {
        Document document = new Document(PageSize.A4.rotate(), 10, 10, 10, 10);
        Document.compress = false;
        try {
            PdfWriter.getInstance(document,
                    new FileOutputStream("AddBigTable.pdf"));
            document.open();
            String[] bogusData = {"M0065920"};
            int NumColumns = 1;

            PdfPTable datatable = new PdfPTable(NumColumns);
            datatable.getDefaultCell().setPadding(3);
            datatable.getDefaultCell().setBorderWidth(2);
            datatable.getDefaultCell().setHorizontalAlignment(
                    Element.ALIGN_CENTER);
            Font tableHeaderFont = new Font(Font.HELVETICA, 20, Font.NORMAL, Color.WHITE);
            PdfPCell header = new PdfPCell(new Phrase("Clock #", tableHeaderFont));
            //header.setBackgroundColor(Color.BLACK);
            header.setPadding(3);
            header.setBorderWidth(2);
            header.setHorizontalAlignment(Element.ALIGN_CENTER);
            datatable.addCell(header);

            datatable.setHeaderRows(1); // this is the end of the table header

            datatable.getDefaultCell().setBorderWidth(1);
            for (int i = 1; i < 75000; i++) {
                if (i % 2 == 1) {
                    datatable.getDefaultCell().setGrayFill(0.9f);
                }
                for (int x = 0; x < NumColumns; x++) {
                    datatable.addCell(bogusData[x]);
                }
                if (i % 2 == 1) {
                    datatable.getDefaultCell().setGrayFill(1);
                }
            }
            document.add(datatable);
        } catch (Exception de) {
            de.printStackTrace();
        }
        document.close();
    }`

**Comment by ambrish24** [comment]
@Wugengxian Thanks for the quick response. 

Could you please try this use case?

We have java class `CustomerGenerator` that will give you dummy data for PDF. I have used both OpenPDF and iText 5.5 with version mentioned below:

**iText 5.5:**

```
<dependency>
    <groupId>com.itextpdf</groupId>
    <artifactId>itextpdf</artifactId>
    <version>5.5.13</version>
</dependency>
```

**OpenPDF 1.3.20**

```
<dependency>
    <groupId>com.github.librepdf</groupId>
    <artifactId>openpdf</artifactId>
    <version>1.3.20</version>
</dependency>
```

Next, we have two implementation for PDF generation `PDFGenerator.java` & `PDFGeneratorIText.java`. When I use PDFGenerator.java (OpenPDF impl) , size of resulting PDF is somewhere around `6.8 MB` but with `PDFGeneratorIText.java` size is `3.5 MB`.


[PDFGeneration.zip](https://github.com/LibrePDF/OpenPDF/files/6341136/PDFGeneration.zip)

**Comment by ambrish24** [comment]
@Wugengxian I have tried your use case(code) as well and able to reproduce the issue.

**OpenPDF Impl: PDF File Size is around 15 MB** 

```
import com.lowagie.text.*;
import com.lowagie.text.Font;
import com.lowagie.text.pdf.PdfPCell;
import com.lowagie.text.pdf.PdfPTable;
import com.lowagie.text.pdf.PdfWriter;

import java.awt.*;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;

public class TestOpenPDF {

    public static void main(String[] args) throws FileNotFoundException {
        Document document = new Document(PageSize.A4.rotate(), 10, 10, 10, 10);
        Document.compress = false;
        try {
            PdfWriter.getInstance(document,
                    new FileOutputStream("AddBigTable_OpenPDF.pdf"));
            document.open();
            String[] bogusData = {"M0065920"};
            int NumColumns = 1;

            PdfPTable datatable = new PdfPTable(NumColumns);
            datatable.getDefaultCell().setPadding(3);
            datatable.getDefaultCell().setBorderWidth(2);
            datatable.getDefaultCell().setHorizontalAlignment(
                    Element.ALIGN_CENTER);
            Font tableHeaderFont = new Font(Font.HELVETICA, 20, Font.NORMAL, Color.WHITE);
            PdfPCell header = new PdfPCell(new Phrase("Clock #", tableHeaderFont));
            header.setBackgroundColor(Color.GRAY);
            header.setPadding(3);
            header.setBorderWidth(2);
            header.setHorizontalAlignment(Element.ALIGN_CENTER);
            datatable.addCell(header);

            datatable.setHeaderRows(1); // this is the end of the table header

            datatable.getDefaultCell().setBorderWidth(1);
            for (int i = 1; i < 75000; i++) {
                if (i % 2 == 1) {
                    datatable.getDefaultCell().setGrayFill(0.9f);
                }
                for (int x = 0; x < NumColumns; x++) {
                    datatable.addCell(bogusData[x]);
                }
                if (i % 2 == 1) {
                    datatable.getDefaultCell().setGrayFill(1);
                }
            }
            document.add(datatable);
        } catch (Exception de) {
            de.printStackTrace();
        }
        document.close();
    }
}
```


**iText Impl: PDF File Size is around 8.5 MB**

```
import com.itextpdf.text.*;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;

import java.io.FileNotFoundException;
import java.io.FileOutputStream;

public class TestIText {

    public static void main(String[] args) throws FileNotFoundException {
        Document document = new Document(PageSize.A4.rotate(), 10, 10, 10, 10);
        Document.compress = false;
        try {
            PdfWriter.getInstance(document,
                    new FileOutputStream("AddBigTable_iText.pdf"));
            document.open();
            String[] bogusData = {"M0065920"};
            int NumColumns = 1;

            PdfPTable datatable = new PdfPTable(NumColumns);
            datatable.getDefaultCell().setPadding(3);
            datatable.getDefaultCell().setBorderWidth(2);
            datatable.getDefaultCell().setHorizontalAlignment(
                    Element.ALIGN_CENTER);

            Font tableHeaderFont = FontFactory.getFont(FontFactory.HELVETICA, 20, Font.NORMAL, BaseColor.WHITE);
            PdfPCell header = new PdfPCell(new Phrase("Clock #", tableHeaderFont));
            header.setBackgroundColor(BaseColor.GRAY);
            header.setPadding(3);
            header.setBorderWidth(2);
            header.setHorizontalAlignment(Element.ALIGN_CENTER);
            datatable.addCell(header);

            datatable.setHeaderRows(1); // this is the end of the table header

            datatable.getDefaultCell().setBorderWidth(1);
            for (int i = 1; i < 75000; i++) {
                if (i % 2 == 1) {
                    datatable.getDefaultCell().setGrayFill(0.9f);
                }
                for (int x = 0; x < NumColumns; x++) {
                    datatable.addCell(bogusData[x]);
                }
                if (i % 2 == 1) {
                    datatable.getDefaultCell().setGrayFill(1);
                }
            }
            document.add(datatable);
        } catch (Exception de) {
            de.printStackTrace();
        }
        document.close();
    }
}
```

**Comment by Wugengxian** [comment]
@ambrish24 you can update the version of OpenPdf to 1.3.25, and this issue has been fixed.

**Comment by ambrish24** [comment]
@Wugengxian My Bad. I didn't check the latest version. With latest version the issue has been fixed. Thanks for pointing out this.
