### ISSUE TITLE
Wrong OSGI import for javax.annotation

### ISSUE THREAD

**Issue by jherkel** [LibrePDF/OpenPDF#512]
I tried to use openpdf with karaf 4.3.1 (OSGI server) but I found out that there is a wrong import :
missing requirement [com.github.librepdf.openpdf/1.3.25] osgi.wiring.package; filter:="(&(osgi.wiring.package=javax.annotation)(version>=3.0.0)(!(version>=4.0.0)))"]]

But there isn't any bundle that provides javax.annotation >= 3.0.0.The latest javax.annotation package has this osgi releated manifest entry:
Export-Package: javax.annotation.security;version="1.3.5",javax.annotation.sql;version="1.3.5",javax.annotation;version="1.3.5"

Probably this dependency comes from findbugs 3.0.2 that contains invalid bundle import  (see discussion https://stackoverflow.com/questions/64568455/why-does-findbugs-jsr305-break-osgi-package-export-of-javax-annotations-in-redha)

**Comment by andreasrosdal** [comment]
Pull requests welcome

**Comment by jherkel** [comment]
I will prepare PR. Temporary I solved this with wrap and rewriting version
of import.

Jakub

**Comment by p4535992** [comment]
It's seem the error persist on version 1.3.26:

`osgi:install -s mvn:com.github.librepdf/openpdf/1.3.26`

here the error i get on my project:

```sh
Error executing command: Error executing command on bundles:
        Error starting bundle 515: Uses constraint violation. Unable to resolve resource XXX [XXX [515](R 515.0)] because it is exposed to package 'javax.annotation' from resources org.apache.felix.framework [org.apache.felix.framework [0](R 0)] and org.jsr-305 [org.jsr-305 [443](R 443.0)] via two dependency chains.

Chain 1:
  XXX [XXX [515](R 515.0)]
    import: (&(osgi.wiring.package=javax.annotation)(version>=1.3.0)(!(version>=2.0.0)))
     |
    export: osgi.wiring.package: javax.annotation
  org.apache.felix.framework [org.apache.felix.framework [0](R 0)]

Chain 2:
  XXX [XXX [515](R 515.0)]
    import: (&(osgi.wiring.package=com.lowagie.text.pdf)(version>=1.3.0)(!(version>=2.0.0)))
     |
    export: osgi.wiring.package=com.lowagie.text.pdf; uses:=javax.annotation
  com.github.librepdf.openpdf [com.github.librepdf.openpdf [500](R 500.0)]
    import: (&(osgi.wiring.package=javax.annotation)(version>=1.0.0)(!(version>=4.0.0)))
     |
    export: osgi.wiring.package: javax.annotation
  org.jsr-305 [org.jsr-305 [443](R 443.0)] Unresolved requirements: [[XXX [515](R 515.0)] osgi.wiring.package; (&(osgi.wiring.package=com.lowagie.text.pdf)(version>=1.3.0)(!(version>=2.0.0)))]


```
Here the important part:
```sh
export: osgi.wiring.package=com.lowagie.text.pdf; uses:=javax.annotation
  com.github.librepdf.openpdf [com.github.librepdf.openpdf [500](R 500.0)]
    import: (&(osgi.wiring.package=javax.annotation)(version>=1.0.0)(!(version>=4.0.0)))
```

**Comment by p4535992** [comment]
never mind it's seem some strange error with my projects i solved by changhing these:
```
com.lowagie.text.pdf,
com.lowagie.text.*,
```
to this:
```
com.lowagie.*;version="${osgi.openpdf.version}"
```
where "osgi.openpdf.version" is 1.2.7
