### ISSUE TITLE
Help wanted: How to attach file with unicode name

### ISSUE THREAD

**Issue by RangerMak** [LibrePDF/OpenPDF#513]
I'm trying to attach file using `writer.addFileAttachment()`.
Name of file contains cyrillic symbols which not shown in resulted PDF.

How to attach file with unicode name?

**Comment by RangerMak** [comment]
Solved:
```
PdfFileSpecification fs = PdfFileSpecification.fileEmbedded(writer, null, fileName, binary, PdfStream.BEST_COMPRESSION);
fs.setUnicodeFileName(fileName, true);
writer.addFileAttachment(null, fs);
```

It will be better to add unicode checking to `public static PdfFileSpecification fileEmbedded(PdfWriter writer, String filePath, String fileDisplay, byte[] fileStore, String mimeType, PdfDictionary fileParameter, int compressionLevel)`?
For example like this:
```
fs.setUnicodeFileName(fileDisplay, !PdfEncodings.isPdfDocEncoding(fileDisplay));
```

**Comment by asturio** [comment]
You mean if the file name contains non-ASCII character (or at least non-Latin symbols) the file name won't be shown?

Pull request welcome.
