### ISSUE TITLE
docs?

### ISSUE THREAD

**Issue by kdekooter** [LibrePDF/OpenPDF#53]

**Comment by asturio** [comment]
Hi there,

OpenPDF is (still) compatible with itext 2.1.7, so any documentation for itext 2.1.7 should fit OpenPDF. And what about the JavaDoc generated by the project?

**Comment by kdekooter** [comment]
I am afraid all documentation for itext 2.1.7 (and lower) has been wiped off the internet. As the API is quite verbose it would be great to have some kind of cookbook / tutorial documentation to get started.

**Comment by tlxtellef** [comment]
Seems like we have to start working on documentation then. For now there are some example code in some of the test source folders, like [pdf-toolbox/src/test/java/com/lowagie/examples](https://github.com/LibrePDF/OpenPDF/tree/master/pdf-toolbox/src/test/java/com/lowagie/examples)

**Comment by kdekooter** [comment]
Would be highly appreciated. We really need an open source PDF solution for Java!

**Comment by andreasrosdal** [comment]
http://www.avajava.com/tutorials/lessons/how-do-i-write-to-a-pdf-file-using-itext.html
http://www.adobepress.com/articles/article.asp?p=420686&seqNum=3
