### ISSUE TITLE
document.add(paragraph) does not add paragraph object to document

### ISSUE THREAD

**Issue by nicodmt** [LibrePDF/OpenPDF#532]
**Describe the bug**
When using the Document class add() the added objects does no add to Document object.

**To Reproduce**
Code to reproduce the issue
1. My Sample Code
My Controller method:

```java
	@GetMapping("/export/pdf")
	public void exportToPDF(HttpServletResponse response) {
		response.setContentType("application/pdf");
		DateFormat dateFormatter = new SimpleDateFormat("yyyy-MM-dd_HH:mm:ss");
		String currentDateTime = dateFormatter.format(new Date());
		String headerKey = "Content-Disposition";
		String headerValue = "attachment; filename=Budget-Plan_" + currentDateTime + ".pdf";
		response.setHeader(headerKey, headerValue);
		List<BudgetPlan> listBudgetPlan = service.listAll();
		BudgetPDFExporter exporter = new BudgetPDFExporter(listBudgetPlan);
		exporter.export(response);
	}
```

My export() in BudgetPDFExporter:
```java
	public void export(HttpServletResponse response) {
		try {
			Document document = new Document(PageSize.A4);
			PdfWriter.getInstance(document, response.getOutputStream());
			document.open();
			Font font = FontFactory.getFont(FontFactory.HELVETICA_BOLD);
			font.setFamily("Helvetica");
			font.setStyle("bold");
			font.setSize(18);
			font.setColor(Color.BLACK);
			Paragraph paragraph = new Paragraph("Budgetplan", font);
			paragraph.setAlignment(Paragraph.ALIGN_CENTER);
			document.add(paragraph);
			PdfPTable table = new PdfPTable(4);
			table.setWidthPercentage(100f);
    		        table.setWidths(new float[] { 1.5f, 3.5f, 3.0f, 3.0f });
			table.setSpacingBefore(10);
			//writeTableHeader(table);
			//writeTableData(table);
			document.add(table);
			document.close();

		} catch (DocumentException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}
```

**Expected behavior**
I expect to have the text "Budgetplan" written on my generated PDF but so is not the case.
It seems that:
```java
			Paragraph paragraph = new Paragraph("Budgetplan", font);
			paragraph.setAlignment(Paragraph.ALIGN_CENTER);
			document.add(paragraph);
```
paragraph never is added to document object. While debugging I can see both objects but they are not added together somehow.

**Screenshots**
Screenshot of my debugger. Highlightet object paragraph with it's value. This is after document.add(paragraph), we are now at document.close();
![image](https://user-images.githubusercontent.com/54702205/116516479-f0675d00-a8cd-11eb-9946-7ee205c33974.png)

**System (please complete the following information):**
 - OS: Windows10 and Ubuntu

**Comment by Wugengxian** [comment]
@nicodmt I try to reproduce it, but I can not reproduce it. I think your issue may caused by  `response.getOutputStream()`

**Comment by nicodmt** [comment]
> @nicodmt I try to reproduce it, but I can not reproduce it. I think your issue may caused by `response.getOutputStream()`

Thank you for your answer! 
After creating this post I found the issue to be cause by the method you also are thinking about.
By changing the OutputStream from the HttpServletRespons object to a new FileOutputStream like so 
`PdfWriter.getInstance(document, new FileOutputStream(Paths.get(System.getProperty("user.home"), "Downloads") + "\\Budget-Plan-" + currentDateTime + ".pdf"));`
I am receiving my PDF file in my downloads folder populated with the data I want to have but this happens without the fancy "Save as" in the browser as the response objects returns.

In all the tutorials here it works just fine with the response.getOutputStream() - but why doesn't it for me?

**Comment by Wugengxian** [comment]
Because `HttpServletResponse` is a interface, the implement of `getOutputStream` is depend on what entity class it is. Maybe `getOutputStream` returns null, and it is ok for OpenPDF to work.

**Comment by nicodmt** [comment]
> > > @nicodmt I try to reproduce it, but I can not reproduce it. I think your issue may caused by `response.getOutputStream()`
> > 
> > 
> > Thank you for your answer!
> > After creating this post I found the issue to be cause by the method you also are thinking about.
> > By changing the OutputStream from the HttpServletRespons object to a new FileOutputStream like so
> > `PdfWriter.getInstance(document, new FileOutputStream(Paths.get(System.getProperty("user.home"), "Downloads") + "\\Budget-Plan-" + currentDateTime + ".pdf"));`
> > I am receiving my PDF file in my downloads folder populated with the data I want to have but this happens without the fancy "Save as" in the browser as the response objects returns.
> > In all the tutorials here it works just fine with the response.getOutputStream() - but why doesn't it for me?
> 
> Because `HttpServletResponse` is a interface, the implement of `getOutputStream` is depend on what entity class it is. Maybe `getOutputStream` returns null, and it is ok for OpenPDF to work.

I'm truely gratefull for your answers but could you explain how the implementation om .getOutputStrem() depends on the entity class? I don't understand that part. I might be to Junior for that.

**Comment by nicodmt** [comment]
Update.

By adding "produces = MediaType.APPLICATION_PDF_VALUE" in my @GetMapping the issue is no more. Closing this now.
