### ISSUE TITLE
PDF Metadata producer is always "OpenPDF 1.0.0-SNAPSHOT"

### ISSUE THREAD

**Issue by vmichaud** [LibrePDF/OpenPDF#54]
I have found this code in class "com.lowagie.text.Document" :
```
private static final String OPENPDF = "OpenPDF";
private static final String RELEASE = "1.0.0-SNAPSHOT";
private static final String OPENPDF_VERSION = OPENPDF + " " + RELEASE;
```
This will be great if the version was read from a property file, automatically updated at Maven build phase with resource filtering.

**Comment by tlxtellef** [comment]
#55 Will solve this issue.
