### ISSUE TITLE
Manually positioning text on the pdf

### ISSUE THREAD

**Issue by Doragon-S** [LibrePDF/OpenPDF#556]
I'd like to manually control the position of text on a pdf page.

I thought it would be convenient to have a function that adds text to the pdf starting at a specified position

someone suggested making a table, setting it to a specific point, and adding the text into there. But I haven't figured out how to do that, and I found no tutorials online.

This is the way pdfBox adds text, and since I know nothing about how to build a programming library, I'm assuming that the document.add() function ends up boiling down to something similar. If so, would it be easy to set it up as a separate accessible function?

**Comment by Doragon-S** [comment]
I guess a simple way to rewrite the question is this: Is there a way to access the basic actions of editing a pdf? (adding a page, adding a word to a specific place on the pdf, etc.)

**Comment by mkl-public** [comment]
OpenPdf offers lower-level APIs, too.
In these cases you address a `PdfContentByte` instance (e.g. from `PdfWriter.getDirectContent()`/ `PdfWriter.getDirectContentUnder()` or from `PdfStamper.getOverContent()`/`PdfStamper.getUnderContent()`) with similar methods as you see in PDFBox.
There are some intermediary level methods, e.g. `PdfContentByte.showTextAligned()` and use of the `ColumnText` class.

**Comment by Doragon-S** [comment]
Thank you so much! 
I got an error of "document has no pages", and document.addPage() doesn't exist. is that also a PdfWriter function?

**Comment by Doragon-S** [comment]
Thank you so much!
Could I also ask you how to make a page? I keep getting the "document has no pages" error. I couldn't find anything about adding pages except pdfPage, and that one said it needed a rectangle, hashmap and a dictionary. And I could only find what a rectangle was.

**Comment by mkl-public** [comment]
CAn you show your code so we can tell you what to change?

**Comment by Doragon-S** [comment]
`    val wr = PdfWriter.getInstance(document, FileOutputStream("filepath.pdf"))
val r = Rectangle(50f,50f,100f,100f)
wr.setBoxSize("LETTER", r)
wr.directContent.setFontAndSize(font.baseFont, font.size)
wr.directContent.showTextBasic(text)`

**Comment by mkl-public** [comment]
Please be aware that you are working with a low-level API here. Thus, you have to enclose text objects with `beginText()` and `endText()` calls. Furthermore, you don't use a `moveText` variant, so your text might appear at a location you don't expect.

Also you do `wr.setBoxSize("LETTER", r)` according to the JavaDocs: `Allowed names are: "crop", "trim", "art" and "bleed".` Thus, your LETTER box might not do what you want.

**Comment by mluppi** [comment]
@Doragon-S 
I have answered your question on StackOverflow: https://stackoverflow.com/a/68419550/5024726
Additionally, I'm adding a new example to the [existing collection](https://github.com/LibrePDF/OpenPDF/tree/master/pdf-toolbox/src/test/java/com/lowagie/examples) in PR #578 which extends on the above mentioned answer.

**Comment by Doragon-S** [comment]
thank you
