### ISSUE TITLE
VirusTotal flags the 1.3.26 Source Code.

### ISSUE THREAD

**Issue by Noobgamer0111** [LibrePDF/OpenPDF#561]
Hey guys!

I've got this small issue. I decided to chuck the source code for v1.3.26 into VirusTotal. I know you guys have no intent to put a virus into your work and I'm believing it as a false flag.

Results: https://www.virustotal.com/gui/file/82a85ecdd0813171504014a49c783196e1d5f6c179953b67bc4ed7478f08ee31/detection

![image](https://user-images.githubusercontent.com/60173797/121652358-e9438980-cade-11eb-9bf7-a2fe4fbecfe1.png)

Regards,

Noobgamer0111

**Comment by Noobgamer0111** [comment]
Image was edited to remove identifying personal information.

**Comment by asturio** [comment]
Jep, very strange. The ZIP file is generated by GitHub when a Release is published, and all the code is in Git (anybody can check it). The SHA256-Sum is also correct, and the same as here in GitHub. I'll try to scan all the sources with G Data.

**Comment by asturio** [comment]
Hi @Noobgamer0111 , 
I made some research on this. What G Data finds is the siwa.pdf file in the source code in the tests in:
https://github.com/LibrePDF/OpenPDF/blob/master/openpdf/src/test/resources/siwa.pdf
As you can see, this is a PDF in the tests, exactly to check for the bug:
#158 signature wrapping attack
Here you can see the commit #159 

So this is just a false positive finding of G Data

**Comment by asturio** [comment]
I reported the issue to G Data.
