### ISSUE TITLE
Bolding/Italics/different font for words, in middle of Column Text

### ISSUE THREAD

**Issue by Doragon-S** [LibrePDF/OpenPDF#571]
**Is your feature request related to a problem? Please describe.**

I want to be able to have certain words bolded or italicized or in a different font in the text I'm putting to the pdf.
I guess this is more of a question of how to do it if it possible, and if not - could this be made to be possible.

**Describe the solution you'd like**

I know this might sound stupid, but I have no idea how to code libraries, so I can only work with the process I imagined columnText gets added, which is that it adds one character to the page at a time and transverse the page by the character size or space size (SpaceCharRatio) until it runs out of either space or text.
Assuming that, I'd think that it would be possible to feed it an array of Strings and an array of fonts, and have it run through the first string with the first font, second with second, etc. 

**Describe alternatives you've considered**

I haven't thought of any alternatives, since I couldn't think of how to look this up in the JavaCode, and I have no clue how to actually make a programing library to think of anything that might be helpful. (Sorry)

**Additional context**

**Comment by Doragon-S** [comment]
I figured out that I could do something similar by passing an array of Strings and Fonts to columnText, and having it print the first string with the first font, second with second, etc.

It doesn't really fix the issue though, since the second string gets printed onto a new line. It would not help if you wanted to have certain words bolded in the middle of the same line. 

Is this possible somehow? Or is it already possible and I'm just missing something?

**Comment by mluppi** [comment]
@Doragon-S
To format the elements, you first need to define a new `Font` with the desired font family, size and style. For example:
```java
Font timesNormal = new Font(Font.TIMES_ROMAN, Font.DEFAULTSIZE, Font.NORMAL);
Font customFont = new Font(Font.COURIER, 12, Font.BOLD, Color.BLUE);
```

Then, you can use smaller text elements and define a different font as the parent element. By default, the font is inherited from the parent. So you can for example add a "formatted" `Chunk` (the smallest part of text) to a `Phrase` or `Paragraph`. Or you can add a "formatted" `Phrase` (series of *Chunks*) to a `Paragraph`.
```java
Paragraph p = new Paragraph("Default font defined with 'timesNormal' ", timesNormal);
p.add(new Chunk("and this Chunk is printed with 'customFont'", customFont));
p.add(" ."); // inherits 'timesNormal' from paragraph
```

This works whether the paragraph (or other text element) is added to the document directly or nested in a `ColumnText`.

*Here is a complete example with some more styles:*
```java
final Font timesNormal = new Font(Font.TIMES_ROMAN, Font.DEFAULTSIZE, Font.NORMAL);
final Font timesBold = new Font(Font.TIMES_ROMAN, Font.DEFAULTSIZE, Font.BOLD);
final Font timesItalic = new Font(Font.TIMES_ROMAN, Font.DEFAULTSIZE, Font.ITALIC);
final Font courierNormal = new Font(Font.COURIER, Font.DEFAULTSIZE, Font.NORMAL);

final Document document = new Document();
final PdfWriter writer = PdfWriter.getInstance(document, new FileOutputStream("output.pdf"));
document.open();

// define a paragraph with different font styles
Paragraph p = new Paragraph("Let's add ", timesNormal);
p.add(new Chunk("bold text", timesBold));
p.add(" followed by ");
p.add(new Chunk("italic text", timesItalic));
p.add(" and text using the ");
p.add(new Chunk("Courier", courierNormal));
p.add(" font.");

// define ColumnText and write paragraph
PdfContentByte canvas = writer.getDirectContent();
ColumnText ct = new ColumnText(canvas);
ct.setSimpleColumn(100, 500, 200, 750);
ct.addElement(p); // add the paragraph as element
ct.go();

// add paragraph to document directly for demonstration
document.add(p);

document.close();
```

*The result looks like this:*
<img width="882" alt="Screenshot 2021-07-19 at 11 27 55" src="https://user-images.githubusercontent.com/53262016/126137651-3cbb159c-c6d1-47f8-a643-f1f539a3dbd2.png">

**Comment by Doragon-S** [comment]
YAY!!! Thank you! I didn't know that you can do this. Thank you so much.

**Comment by Doragon-S** [comment]
I found that when trying to do this with Hebrew text (and I'm assuming all RTL languages) it prints the characters LTR. Is there a way this can be fixed?

**Comment by asturio** [comment]
Pull requests welcome!

**Comment by cesiabulnes** [comment]
@asturio Hi I'm a first time contributor working on this for University, is it ok if I work on the bolding of different words etc? I will also try to do the RTL fix if I have the time!
