### ISSUE TITLE
This does not work when my PDF starts with "%PDF-1.4". "%PDF-" should be checked

### ISSUE THREAD

**Issue by msincuba** [LibrePDF/OpenPDF#60]
https://github.com/LibrePDF/OpenPDF/blob/251761c5406339783eea858dc1dfde1e7bf13679/openpdf/src/main/java/com/lowagie/text/pdf/PRTokeniser.java#L212

**Comment by tlxtellef** [comment]
> The first line of an FDF file is a header, originally intended to identify the version of the PDF specification to which the file conforms. However, for historical rea- sons, this version number is now frozen and must read
`%FDF-1.2`

[Page 712 of PDF 1.7](https://www.adobe.com/content/dam/acom/en/devnet/acrobat/pdfs/pdf_reference_1-7.pdf)

**Comment by GitMensch** [comment]
To create a back-reference: https://github.com/rtfarte/OpenPDF/pull/22 (it seems the PR never contained any change to the tokenizer, just pull the changes from this repo).

To extend what @tlxtellef said: the manual goes on with saying that if a newer version than 1.2 is used an entry in the FDF *catalog* (not header) should be made (page 714):

>  KEY: `Version`, TYPE: name, VALUE:   *(Optional; since PDF 1.4)* The version of the PDF specification to which this FDF file conforms (for example, `1.4`) if later than the version specified in the file's header.
