### ISSUE TITLE
Incorrect license in pom.xml

### ISSUE THREAD

**Issue by Earless** [LibrePDF/OpenPDF#609]
According to the following files OpenPDF is licensed with MPL 2.0 and LGPL 2.1.
- License.md
- LGPL-2.1.md
- Readme.md.

However, according to your pom.xml, OpenPDF is licensed with MPL 2.0 and LGPL 3.0.

Am I correct to assume that there is a mistake in your pom.xml, and that OpenPDF is indeed licensed with MPL 2.0 and LGPL 2.1? If so, please update the pom.xml.

**Comment by asturio** [comment]
Just fixed it
