### ISSUE TITLE
Remove ITXT or replace it with a new Name

### ISSUE THREAD

**Issue by asturio** [LibrePDF/OpenPDF#610]
Hi all, I'm thinking about the ITXT topic again as mentioned in:

- #261
- #303

Bruno Lowagie also mentioned it in this video (https://youtu.be/bZudGJw3Ck0?t=1819 , from about 30:32 till 35:30), so I think it is a good idea, if this issue is addressed soon.

So the idea is to either remove the usage of ITXT and similar at all, or:

- replace it with something new and not registered. Just some random name.
- replace it with a new registered name for OpenPDF (I have not idea how to register it, and I'm not willing to register it to myself. And LibrePDF is no physical organization... so...)
- replace it with a known generic name for producer (if something of the kind exists)

So here this "issue" for some discussions.

May be of interest to:  @V-F , @mkl-public, @sixdouglas ,  @Lonzak , @andreasrosdal , @justinasbardauskas

**Comment by sixdouglas** [comment]
Like @justinasbardauskas I'm not expert enough to bring new arguments, for or against keeping or removing this tag.
But in the light of what has been said, removing it seems the right option here.

**Comment by asturio** [comment]
Very constructive arguments. It seems the best to remove the code related to the ITXT prefix.

**Comment by andreasrosdal** [comment]
https://youtu.be/bZudGJw3Ck0?t=1819

Can we use this video to improve OpenPDF?
-Implement PDF/U 
-What else?
