### ISSUE TITLE
Paragraph leading ist ignored, when keepTogether is set

### ISSUE THREAD

**Issue by gradlifier** [LibrePDF/OpenPDF#620]
The fix of #271 and commit 1d3c049 brought a new issue for our application. The leading is ignored in paragraphs with keepTogether set to true. 

Code to reproduce:
`public class TestBad211 {

	public static void main(String[] args) throws IOException {
		final Path createdPdfFile = Files.createTempFile("TestBad211", ".pdf");

		Document document = new Document();
		try {
			PdfWriter.getInstance(document, new FileOutputStream(createdPdfFile.toFile()));
			document.open();

			Paragraph par1 = new Paragraph("Zeile1", FontFactory.getFont(BaseFont.COURIER, 10));
			Paragraph par2 = new Paragraph("Zeile2", FontFactory.getFont(BaseFont.COURIER, 10));
			par2.setLeading(24);
			par2.setKeepTogether(true);
			Paragraph par3 = new Paragraph("Zeile3", FontFactory.getFont(BaseFont.COURIER, 10));
			par3.setLeading(12);

			document.add(par1);
			document.add(par2);
			document.add(par3);
		}
		catch (DocumentException | IOException de) {
			System.err.println(de.getMessage());
		}
		document.close();

		System.out.println("Datei " + createdPdfFile.toString() + " geschrieben");
	}
}`

Result is (since version 1.3.12):
![grafik](https://user-images.githubusercontent.com/32893697/140914659-42275a83-6bf0-4553-affa-ad29668a4049.png)

Expected (up to version 1.3.11):
![grafik](https://user-images.githubusercontent.com/32893697/140914807-7867cf63-b1c0-4364-8e73-1d4537d619fe.png)

**Comment by haha989** [comment]
Hello @gradlifier  , our group are interested in this issue, and we will try to fix it.
---- SE_SUSTech, group: Lanrand

**Comment by ObsisMc** [comment]
@haha989 is you working on this issue? I want to try it.
