### ISSUE TITLE
Java 11 Support and Software Site

### ISSUE THREAD

**Issue by jmenzies12** [LibrePDF/OpenPDF#624]
Hey there,

We are currently using openpdf 1.1.0 and are about to upgrade to java 11. Is it possible to run and build in java 11 with this version or will we have to update to get compatibility?

Also, by any chance do you have a software site we can use to download the release from?
Sorry if this is the wrong place to post this, I couldn't find a forum link or contact details anywhere.

Cheers
Jonathan

**Comment by arnthom** [comment]
Hi Jonathan, you can find the Download at
https://search.maven.org/search?q=g:com.github.librepdf%20AND%20a:openpdf&core=gav

**Comment by jmenzies12** [comment]
Thanks for that! 

Could you tell me if version 1.1.0 is compatible to be built on Java 11 ?

**Comment by codylerum** [comment]
Looks like the CI builds are running on 8,11 and 16.

I'm running it on 17 without issue.

**Comment by jmenzies12** [comment]
Hey sorry just wanted to clarify, you are running openpdf 1.1.0 on Java 17 ?

I couldn't see what version the CI builds are running on so I presume they are running on a recent version

**Comment by codylerum** [comment]
Running `1.3.26` on JDK 17. `1.1.0` is a 3 year old release so you may want to get that updated first.

You can see versions https://github.com/LibrePDF/OpenPDF/blob/master/.github/workflows/maven.yml#L16

Or from recent builds in actions https://github.com/LibrePDF/OpenPDF/actions/runs/1514668628

**Comment by mluppi** [comment]
@jmenzies12 Is there a specific reason preventing you from upgrading to the most recent version?
I suggest that you try with Java 11 and then verify if everything works as expected. I was able to compile and run some basic tests with the tag `1.0.1`. However, I recommend that you upgrade if possible.

**Comment by andreasrosdal** [comment]
OpenPDF now requires Java 11.
