### ISSUE TITLE
Wrong License in maven.org distributed file

### ISSUE THREAD

**Issue by martcre** [LibrePDF/OpenPDF#631]
**Describe the bug**
At least in Version 1.3.26 of openpdf distributed via repo1.maven.org contains different license files than present in the github-repo, and especially there is GPL License Text in the file lgpl.txt.

OpenPDF is wrongly identified by Sonatype IQ Server to be GPL, although licensed under LGPL and MPL

**To Reproduce**
1. Download https://repo1.maven.org/maven2/com/github/librepdf/openpdf/1.3.26/openpdf-1.3.26.jar or https://repo1.maven.org/maven2/com/github/librepdf/openpdf/1.3.26/openpdf-1.3.26-sources.jar
2. Review the contained license files

**Expected behavior**
It is expected that the distributed openpdf artifact is only containing licenses for LGPL and MPL.

**Screenshots**
Content of https://repo1.maven.org/maven2/com/github/librepdf/openpdf/1.3.26/openpdf-1.3.26-sources.jar:
```
META-INF
MPL-1.1.txt
apache_license.txt
com
font-fallback
lgpl.txt
misc_licenses.txt
```

Content of https://github.com/LibrePDF/OpenPDF/archive/refs/tags/1.3.26.zip:
```
CODE_OF_CONDUCT.md
LGPL-2.1.md
License.md
MPL-2.0.txt
README.md
checkstyle-inactive.xml
checkstyle.xml
intellij-java-openpdf-style.xml
manifest.mf
openpdf
openpdf-fonts-extra
pdf-swing
pdf-toolbox
pom.xml
```

**System (please complete the following information):**
N/A

**Additional context**
My assumption is that there is some issue with the build of the artifact and that different license files as expected are inlcuded.

**Comment by andreasrosdal** [comment]
Are you sure the license file contains the GPL license text? Can you please post a screenshot of this?

**Comment by asturio** [comment]
There are different copies of license-files scattered  through the project. The openpdf.jar has the old copies. And also an Apache-License inside, which I don't know what code is covered by it.

**Comment by asturio** [comment]
Some code is licensed under the ASF 2.0. I think that license should also be included in the jar-Bundle
