### ISSUE TITLE
wirting a single table in the ColumnText in simulation mode is not taken in consideration and skiped

### ISSUE THREAD

**Issue by alesky78** [LibrePDF/OpenPDF#633]
**Bug description**
in the version 1.3.26 of the lib
when you use the ColumnText in simulation mode and you add just a single table, in case the first rows of the table has not enought space to be introduced in the simulated pdf, the table is excluded from the ColumnText calculation.

a simple code example
```
result = ct.go(true);
 boolean hasText = ColumnText.hasMoreText(result); // this return false!

```
**To Reproduce**
[BUGColumnTextWihtOnlyTable.txt](https://github.com/LibrePDF/OpenPDF/files/7693213/BUGColumnTextWihtOnlyTable.txt)

Code in attachment of this ticket

**Expected behavior**
the table cannot be excluded from the calculation in the ColumnText and the method  ColumnText.hasMoreText(result); must return false

**Additional context**
The issue is anidated in the class com.lowagie.text.pdf.ColumnText  exactly at the line 1422:
```
else if (!table.isSplitRows() && k == listIdx && firstPass) {   
    compositeElements.removeFirst();   
    splittedRow = false;
    continue;
}
```

same comments of this code:
**if (!table.isSplitRows() && k == listIdx && firstPass)**
this condition identify the first row of the table didn't enter in the pdf and this table if the first element analized in the ColumnText context
**compositeElements.removeFirst();** 
the table is removed from the context (also if this is a table of 100 rows!) of th ColumnText, then in case in the context there are no more elements,  later the method result = ct.go(true); will return that there are no more elements and all is wrote correctly in the pdf when this is not true! the table is skiped

the correct code should be:
```
else if (!table.isSplitRows() && k == listIdx && firstPass) {   
             return NO_MORE_COLUMN;
}
```

we have another example of correct implementation in the line 1427
```
                    else if (k == listIdx && !firstPass && (!table.isSplitRows() || table.isSplitLate()) && (table.getFooterRows() == 0 || table.isComplete()))
                        return NO_MORE_COLUMN;
```
[BUGColumnTextWihtOnlyTable.txt](https://github.com/LibrePDF/OpenPDF/files/7693215/BUGColumnTextWihtOnlyTable.txt)

**Comment by alesky78** [comment]
I case is required, I can do a fix by myself,  and then  make a pull request,
please let me know how i can help to fix this issue and speed up the publish of the fix

**Comment by asturio** [comment]
Please feel free in creating a fix for this, and creating a pull request.
