### ISSUE TITLE
Bouncy Castle is not optional

### ISSUE THREAD

**Issue by rivron** [LibrePDF/OpenPDF#65]
A simple test which only instantiate a PdfReader on a empty PDF requires Bouncy Castle in the classpath. The pom declare it optional in the manifest.
This problem does not happen with the iText version at [ymasory/iText-4.2.0](https://github.com/ymasory/iText-4.2.0).

**Comment by rik86** [comment]
could you share your test, so I can replicate it? Thanks

**Comment by rivron** [comment]
My test and the result :
```java
import com.lowagie.text.pdf.PdfReader;

public class Test {
	public static void main(String[] args) throws Exception {
		PdfReader reader = new PdfReader(args[0]);
		reader.close();
	}
}
```
`$ javac -cp openpdf-1.0.6-SNAPSHOT.jar Test.java`
`$ java -cp openpdf-1.0.6-SNAPSHOT.jar:. Test `[`blank.pdf`](https://github.com/LibrePDF/OpenPDF/files/1670118/blank.pdf)


```
Exception in thread "main" java.lang.NoClassDefFoundError: org/bouncycastle/cms/Recipient
	at Test.main(Test.java:5)
Caused by: java.lang.ClassNotFoundException: org.bouncycastle.cms.Recipient
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 1 more
```

**Comment by rik86** [comment]
Hello, I haven't found any exception, I set up a project in Maven with `openpdf-1.0.6-SANPSHOT` as a dependency and run the following test

```
	@Test
	public void testPdfReader() {
		try {
			ByteArrayOutputStream os = new ByteArrayOutputStream();
			Document document = new Document();
			PdfWriter writer = PdfWriter.getInstance(document, os);
			document.open();
			document.add(new Paragraph("Hello World!"));
			document.close();
			writer.close();
			PdfReader reader = new PdfReader(os.toByteArray());
			reader.close();
		} catch (Exception e) {
			fail(e.toString());
		}
	}
```
This test passes. It could be something relevant to the PDF you are passing as an argument. 
Although coming back to your first point "Bouncy Castle is not optional", I'd say no, it isn't as the README.md states it is Required.

**Comment by asturio** [comment]
Hi @rik86, I just checked the pom.xml. I think there is than an error here:

            <plugin>
                <groupId>org.apache.felix</groupId>
                <artifactId>maven-bundle-plugin</artifactId>
                <configuration>
                    
                    <unpackBundle>true</unpackBundle>
                    <instructions>
                        
                        <Export-Package>com.lowagie.text.*;version="${project.version}"</Export-Package>
                        
                        <Import-Package>org.bouncycastle.*;resolution:=**optional**,!com.lowagie.*,*</Import-Package>
                    </instructions>
                </configuration>
            </plugin>

**Comment by asturio** [comment]
I don't know the reason for this. Any clue?

**Comment by rik86** [comment]
I think this maven plug in is well old, from a quick read it seems to be for maven 2. I'd say to remove it and make bouncy castle a normal dependency. In maven 3 clashing dependencies can be excluded anyway... also the repository mentioned in the first comment: ymasory/iText-4.2.0 it's an ant build, so it's different

**Comment by rivron** [comment]
BouncyCastle is optional in iText at execution time until there is an attempt to read or write encrypted PDF, which is far to be the most frequent use case. So this line in the manifest was correct. Also, BC is now declared optional in the iText 5 [pom.xml](https://github.com/itext/itextpdf/blob/50390a036ff68dc0fb2c9f96723d0a7aa7d2b2f5/itext/pom.xml#L79).
This constraint prevents us to migrate from iText to OpenPDF.

**Comment by asturio** [comment]
@rivron, so you mean OpenPDF should keep the optional plugin setup? So the generated jar has this optional flag set?

**Comment by asturio** [comment]
@rivron, @rik86
There is a PR #68. Could this fix this issue?

**Comment by rivron** [comment]
The problem is independent from the pom or the manifest. It can only be reproduced with a custom classpath which does not include bouncy castle, i.e outside maven.
I have attached a [zip](https://github.com/LibrePDF/OpenPDF/files/1711484/bcTest.zip) which runs the test from @rik86 with 3 different jars:
 - itext-4.2.0.jar from maven repository
 - openpdf-1.0.5.jar from maven repository
 - a custom openpdf jar with line 861 of PdfReader commented.

The test passes with the first and last jar.

This line (and the commented part // OJO...) is one of the difference with iText 4.2.0 and the use of bc1.58.
I do not understand why this forces the use of bc, especially when the execution do not reached this line... the method readDecryptedDocObj stops way before because the pdf is not encrypted.

One solution might be to isolate readDecryptedDocObj in a specific class.

**Comment by asturio** [comment]
Hi @rivron, @rik86, @rtfarte,

I just made some changes in the PdfReader, now your test code is working. Take a look at #68

**Comment by rivron** [comment]
I have tested it. Thanks a lot @asturio !

**Comment by asturio** [comment]
If there is no objection, I'll be merging it till the WE.

**Comment by keesvandieren** [comment]
Bouncy Castle may give problems on some Application Servers, a release would be great :-)

**Comment by gexclaude** [comment]
I would appreciate a release too :)

**Comment by roschdal** [comment]
This seems to ve fixed now? Please reopen if you still have this problem.

**Comment by roschdal** [comment]
Please try OpenPDF 1.1.0 and report if this has been fixed: https://github.com/LibrePDF/OpenPDF/releases/tag/1.1.0

**Comment by gexclaude** [comment]
In our case we can now generate the PDFs without bouncycastle - therefore I consider this issue fixed.
