### ISSUE TITLE
remove javax.annotation dependency

### ISSUE THREAD

**Issue by Nutstree** [LibrePDF/OpenPDF#651]
**Describe the bug**
Unnecessary dependency on javax.annotation. 
In the OpenPDF pom there is an OSGI dependency declared in the maven-bundle-plugin configuration. As far as I can tell there is no dependency on this by maven.

We are working on making our software java17 compatible and therefor are migrating all dependencies on javax.* to jakarta.* and noticed this OSGi dependency.

**To Reproduce**
not applicable

**Expected behavior**
No javax.annotation dependency

**Additional context**
javax.annotation is replaced by jakarta.annotation. javax.annotation is no longer maintained.

**Comment by andreasrosdal** [comment]
This can be closed.

**Comment by asturio** [comment]
Fixed in #662
