### ISSUE TITLE
support AES-256 encryption

### ISSUE THREAD

**Issue by fredmafu** [LibrePDF/OpenPDF#655]
New const of encryption type like PdfWriter.ENCRYPTION_AES_256.

Thank you.

**Comment by andreasrosdal** [comment]
Pull requests welcome!

**Comment by andreasrosdal** [comment]
https://github.com/LibrePDF/OpenPDF5/commit/7bcd438aacf224c45d07a86cd259b51dca3c380d

**Comment by Lonzak** [comment]
We can not take AGPL code and put it into this LGPL/MPL licensed code.
There is an development in this area however and an independent implementation of this.
Something is soon to come :-)

**Comment by Lonzak** [comment]
@bsanchezb Yes the update is that it has been implemented :-)

**Comment by bsanchezb** [comment]
@Lonzak , thank you for the notification ;) and big thanks to @mkl-public for the PR
