### ISSUE TITLE
Header and Footer definition is ignored

### ISSUE THREAD

**Issue by jhippolyte** [LibrePDF/OpenPDF#669]
##  Description
When I try to define a Header and a Footer for a Document, it is not taken into account.

## To Reproduce
Code to reproduce the issue
```java
Document document = new Document();
document.setMargins(15f, 15f, 10f, 10f);
PdfWriter.getInstance(document, output);
document.open();
HeaderFooter header = new HeaderFooter(new Phrase("This is a header."), false);
HeaderFooter footer = new HeaderFooter(new Phrase("This is a footer "), new Phrase("."));
document.setHeader(header);
document.setFooter(footer);
document.add(new Paragraph("Hello World"));
document.close();
```

## Expected behavior
The Header and Footer should have been added to the document.

## Screenshots
![image](https://user-images.githubusercontent.com/28600737/155214022-51a2c332-98b0-41ba-987a-5cf933b447da.png)

## System 
 - OS: Windows 10
 
Thanks for your help.

**Comment by mluppi** [comment]
Header and footer definitions need to be set _before_ opening the document. Here in an example:

```java
Document document = new Document();
document.setPageSize(PageSize.A7.rotate()); // just to make output smaller
document.setMargins(15f, 15f, 24f, 20f);
HeaderFooter header = new HeaderFooter(new Phrase("This is a header."), false);
HeaderFooter footer = new HeaderFooter(new Phrase("This is a footer on page "), new Phrase("."));
document.setHeader(header);
document.setFooter(footer);
document.open(); // only open the document after header/footer have been set
document.add(new Paragraph("Hello World"));
document.add(Chunk.NEXTPAGE);
document.add(new Paragraph("Hello new page."));
```

*Output:*
![Screenshot](https://user-images.githubusercontent.com/53262016/155885616-feafda20-8521-4af3-816c-fc86576cf23f.png)

**Comment by arnthom** [comment]
Good point ...
In Document.class you can read after all the imports:
` * Remark:
 * <OL>
 *     <LI>Once a document is created you can add some meta information.
 *     <LI>You can also set the headers/footers.
 *     <LI>You have to open the document before you can write content.
`

Maybe one could add to the second listitem "before opening the document."

And should this be mentioned within the setHeader and setFooter javadoc comments?

**Comment by mluppi** [comment]
@arnthom On of your proposed remarks is already addressed just 2 items below:
https://github.com/LibrePDF/OpenPDF/blob/bff6520a368fe0a35b443740a36cba108f4ed1a4/openpdf/src/main/java/com/lowagie/text/Document.java#L78-L79

I updated my comment to reflect the general case. Additionally, I improved the Javadoc of the methods used to set header/footer. Here is the PR: #675

**Comment by jhippolyte** [comment]
@mluppi thanks for your helpful answer !
