### ISSUE TITLE
Digital Signature invalidated after encrypt a pdf by PdfStamper#setEncryption(...)

### ISSUE THREAD

**Issue by fredmafu** [LibrePDF/OpenPDF#672]
I try to protect a signed pdf by

```
PdfStamper stamper = new PdfStamper(...);
...
stamper.setEncryption("psw".getBytes(), ..., PdfWriter.ENCRYPTION_AES_128);
...
stamper.close();
```

After open the protected pdf with "psw" in Adobe Reader, the digital signature becomes invalidated.  May I know is it expected? Any fixing / workaround? Thank you.

**Comment by mkl-public** [comment]
A digital signature of a PDF contains a fingerprint (hash value) of the document bytes. By encrypting the PDF you change the document bytes. Thus, you invalidate the signature.

If you want a PDF to be both signed and encrypted, you have to encrypt the original PDF before or as part of the signing process.

In particular this is no _bug_ but _expected behavior_.
