### ISSUE TITLE
RTL support 

### ISSUE THREAD

**Issue by Jaspreet96** [LibrePDF/OpenPDF#674]
I am using Apache POI with OpenPdf to convert docx(with arabic text) to a pdf. However, in the pdf being generated the characters are printed in the direction left to right instead of Right to Left.
Refer the below two images:
![doc](https://user-images.githubusercontent.com/42904853/155765606-ac4813e1-3d0c-4a49-b5af-9d5fd124bca3.PNG)
![pdf](https://user-images.githubusercontent.com/42904853/155765616-e9b26396-0fad-4f03-adbb-d297f5b51d72.PNG)

**Comment by andreasrosdal** [comment]
emoclew stseuqer lluP

**Comment by andreasrosdal** [comment]
Pull requests welcome

**Comment by asturio** [comment]
@Jaspreet96 
Can you write the correct Arabic text here, so I can play around with it. Just a little snippet will do.

**Comment by asturio** [comment]
There is an example of using arabic text here: [com.lowagie.examples.directcontent.graphics2d.ArabicText](https://github.com/LibrePDF/OpenPDF/blob/master/pdf-toolbox/src/test/java/com/lowagie/examples/directcontent/graphics2d/ArabicText.java)

Does this example solve your question?

**Comment by Jaspreet96** [comment]
Hey @asturio I am using Apache Poi with OpenPdf (xdocreport) to convert docx to pdf. I think the issue might lie with how they are converting docx to pdf. Haven't reached any conclusion yet.

**Comment by Jaspreet96** [comment]
As mentioned in the above comment, the problem lies with how XDocReport is using OpenPdf to convert DOCX to PDF.
