### ISSUE TITLE
Adding Paragraphs with different run directions to same ColumnText object

### ISSUE THREAD

**Issue by Jaspreet96** [LibrePDF/OpenPDF#691]
XDocReport while converting DOCX to PDF is using Apache POI with OpenPdf. They create a layout table with a single row, cell and add their objects into that cell.
The problem arises when a document contains BiDirectional Content. For example, refer the below lone line paragraphs:
     اختبار اللغة العربية 
I am trying to use XDocReport to convert DOCX into PDF. It’s going well as of now. Want to run a couple more tests. 

The above two paragraphs are part of the same DOCX . As you know when object added to ColumnText is a Paragraph the composite column created assumes the direction of the parent ColumnText object. 
Is there a specific reason as to not give a runDirection variable in Paragraph object as well, so that one may add multiple paragraphs with different runDirections in the same ColumnText object .

**Comment by andreasrosdal** [comment]
Thank you for reporting. Pull requests welcome.
