### ISSUE TITLE
Develop version - SNAPSHOT?

### ISSUE THREAD

**Issue by nwinkler** [LibrePDF/OpenPDF#7]
I noticed that all of the code in the `master` branch has `1.0` as a version number in the `pom.xml` files.

Shouldn't we follow the Maven standard of using `SNAPSHOT` versions, and use the full version number only for the released version? That would mean changing the `1.0` in the pom files to `1.1-SNAPSHOT` or `1.0.1-SNAPSHOT`.

Since I'm preparing a couple of pull requests for this project, I'd like to understand how this is handled in OpenPDF. Happy to also create a PR for adjusting the version numbers - just let me know.

**Comment by andreasrosdal** [comment]
Yes, this is a good idea. Feel free to submit a PR for this. It's great that you show interest in contributing to this project!

**Comment by nwinkler** [comment]
Created a PR in #8
