### ISSUE TITLE
HtmlParser: maybe there should be a new line between title and body

### ISSUE THREAD

**Issue by ObsisMc** [LibrePDF/OpenPDF#706]
My html has title and after parsing, the title is in the first line of body. I think at least it should change a line.

**To Reproduce**
The code is the same as sample [ParseHelloHtml.java](https://github.com/LibrePDF/OpenPDF/blob/master/pdf-toolbox/src/test/java/com/lowagie/examples/html/ParseHelloHtml.java).
```java
public static void main(String[] args) {
        System.out.println("Parse Hello World");

        // step 1: creation of a document-object
        try (Document document = new Document()) {
            PdfWriter.getInstance(document, new FileOutputStream("test.pdf"));
            // step 2: we open the document
            document.open();
            // step 3: parsing the HTML document to convert it in PDF
            HtmlParser.parse(document, ParseHelloHtml.class.getClassLoader().getResourceAsStream("com/lowagie/examples/html/test.html"));
        } catch (DocumentException | IOException de) {
            System.err.println(de.getMessage());
        }
    }
```
Html is following.
```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8"/>
    <title>Title</title>
</head>
<body>
<p>This is a test.</p>
</body>
</html>
```
**Current behavior**
![图片](https://user-images.githubusercontent.com/71996633/163668969-667b2acb-9bbb-48ee-a866-f0f0e3b4d451.png)

**Expected behavior**
I think it should change line at least.
![图片](https://user-images.githubusercontent.com/71996633/163669066-82a3f8f2-6b1e-46e1-80b3-2d62ca6dcffa.png)

**Comment by Elizalll** [comment]
Hello👋 @ObsisMc, may I work on this issue? Thank you.

**Comment by chappyer** [comment]
Good issue! I'll fix this and submit a Pull Request soon.
