### ISSUE TITLE
Broken retro-compatibility

### ISSUE THREAD

**Issue by lapo-luchini** [LibrePDF/OpenPDF#72]
Commit ae40ae2497a2d6ef86cf273f70e6fe2b0dbe4107 changed the signature of `PdfSignatureAppearance.setCrypto` removing some arrays.
Unfortunately the diff can't be seen on GitHub because the file was dropped and re-added, but here's a part of the diff:

```diff
--- PdfSignatureAppearance-fdb76b2.java 2018-03-29 18:15:23.827579000 +0200
+++ PdfSignatureAppearance-ae40ae2.java 2018-03-29 18:15:30.675425000 +0200
@@ -247,36 +271,65 @@
     
     /**
      * Sets the cryptographic parameters.
-     * @param privKey the private key
+   * 
-     * @param certChain the certificate chain
+   * @param privKey
+   *          the private key
+   * @param certificate
+   *          the certificate
+   * @param crl
-     * @param crlList the certificate revocation list. It may be <CODE>null</CODE>
+   *          the certificate revocation list. It may be <CODE>null</CODE>
-     * @param filter the crytographic filter type. It can be SELF_SIGNED, VERISIGN_SIGNED or WINCER_SIGNED
+   * @param filter
+   *          the cryptographic filter type. It can be SELF_SIGNED,
+   *          VERISIGN_SIGNED or WINCER_SIGNED
      */    
-    public void setCrypto(PrivateKey privKey, Certificate[] certChain, CRL[] crlList, PdfName filter) {
+  public void setCrypto(PrivateKey privKey, X509Certificate certificate,
+      CRL crl, PdfName filter) {
         this.privKey = privKey;
-        this.certChain = certChain;
+    this.certificate = certificate;
-        this.crlList = crlList;
+    this.crl = crl;
         this.filter = filter;
     }
```

As far as the change goes I guess it's fine, because the array was never used for anything more than `[0]` but it breaks binary compatibility with itext-4.2.0 for no real reason.
I would suggest adding a method such as:

```Java
  /**
   * Sets the cryptographic parameters.
   * @deprecated use {@link #setCrypto(PrivateKey, X509Certificate, CRL, PdfName)}
   */
  public void setCrypto(PrivateKey privKey, Certificate[] certChain, CRL[] crlList, PdfName filter) {
    setCrypto(privKey, (X509Certificate) certChain[0], crlList != null ? crlList[0] : null, filter);
  }
```

Tell me if you'd like a PR for that.

**Comment by asturio** [comment]
Hi @lapo-luchini ,

I think a PR would be great. Can you create one? I'll check it, when it's there. For compatibility with itext, I think such "deprecated" methods are nice.

**Comment by andreasrosdal** [comment]
@lapo-luchini Could you please share some information about how you are using OpenPDF and PdfSignatureAppearance.setCrypto to sign PDF files? This could be of interest to others also. Thanks!

**Comment by lapo-luchini** [comment]
@andreasrosdal unfortunately I use that only in a work scenario and don't have a working example only using opensource code.
I found [a C# example using iText 4](https://blog.banko.cloud/blog/2013/10/24/use-itext-4-1-6-to-signing-a-pdf-file-with-c/) that, while not being updated to latest PAdES, should be a pretty decent starting point.
