### ISSUE TITLE
Add multiple PDFs and merge them into one PDF

### ISSUE THREAD

**Issue by linux936294871** [LibrePDF/OpenPDF#737]
In daily life, we often need to combine multiple PDFs of the same type into a single PDF, so I highly recommend adding this feature to facilitate many subsequent uses.

**Comment by youyumeimei** [comment]
Hello @linux936294871 , our group are interested in this issue, and we will try to fix it.
---- SE_SUSTech, group: Lanrand

**Comment by andreasrosdal** [comment]
Please don't add a dependency on Pdfbox and Lombok

**Comment by asturio** [comment]
Please note: OpenPDF is a PDF manipulation library like iText or PDFBox. There is no point using iText or PDFBox inside OpenPDF to add new features to the library. If this feature is really needed (Merging existing PDF files into a single PDF file), then please accomplish this using only code in and from OpenPDF.
