### ISSUE TITLE
Use PdfStamper.getPdfLayers() causes java.lang.NullPointerException.

### ISSUE THREAD

**Issue by guguguteam** [LibrePDF/OpenPDF#744]
**Describe the bug**
When use  PdfStamper.getPdfLayers() causes java.lang.NullPointerException.

**To Reproduce**
Code to reproduce the issue
pdfstamper = new PdfStamper(reader, new FileOutputStream("myTest2.pdf"));
System.out.println(pdfstamper.getPdfLayers());
pdfstamper.close();

myTest2.pdf is a pdf file which use the pro to generate.

**Expected behavior**
no causes PdfStamper.getPdfLayers().

**Screenshots**
![image](https://user-images.githubusercontent.com/66819851/170820339-d2b1892d-c958-4952-9be9-9bffffaf8edf.png)

**System (please complete the following information):**
 - OS: win10
 -  - Used Font:

**Additional context**

**Comment by guguguteam** [comment]
Hello, can I work on this issue?

**Comment by ThreeHmeng** [comment]
Hello, can I work on this issue? I'll try to fix it

**Comment by guguguteam** [comment]
Of cause! Thanku!

**Comment by asturio** [comment]
I think this issue was solved with #728

**Comment by asturio** [comment]
May be the same problem as in #727 .
