### ISSUE TITLE
Open discussion about the motivation of this project.

### ISSUE THREAD

**Issue by asturio** [LibrePDF/OpenPDF#756]
There is a need to move the classes of OpenPDF (and sibling projects) from the com.lowagie-namespace to a OpenPDF/LibrePDF-namespace.

Also I wanted to checkout how these "projects" in GitHub work :-)

My suggestion is:

- Move all classes from com.lowagie.* to org.librepdf.*
- This change should be a major release (e.g. 2.0.0)
- This should be well documented in the Wiki, and in gh-pages.

This is a Discussion-Issue

**Comment by andreasrosdal** [comment]
The namespace com.lowagie.* is used in accordance with the LGPL and MPL license, so there is no urgent need to change the package names. Using this package name makes migration to OpenPDF easy and quick.

**Comment by Andrew-Russell-fingo** [comment]
> The namespace com.lowagie.* is used in accordance with the LGPL and MPL license, so there is no urgent need to change the package names. Using this package name makes migration to OpenPDF easy and quick.

Exactly, I agree.
This package is a drop in replacement for the 'com.lowagie:itext:2.1.7' jar.
But with support and security fixes.
Andrew
