### ISSUE TITLE
Calls to String.toLowerCase(), and friends should be checked for proper use of locales

### ISSUE THREAD

**Issue by daviddurand** [LibrePDF/OpenPDF#77]
Case-folding is used for various pieces of data and metadata used in PDF syntax (perhaps also in user content). Those transformations are based on Adobe's general assumption of the use of US_ASCII/ISO-Latin-1 encoding. As noted in the comment on pull request https://github.com/LibrePDF/OpenPDF/pull/76 This fails for (at least) Turkish locales, where Capital I can fold to a non-Latin-1 lowercase dotless `i` (`ı`).

Where PDF syntax is being processed the ROOT (no-language) locale should be used. Each case has to be examined, at least superficially, to determine if:

1. the System locale should be use (_e.g._ for filenames)
2. The ROOT local should be used, as discussed.
3. A locale defined in the PDF itself needs to be used, as transformations are being performed on the content streams. (I do _not_ know for sure that there are any such cases at this point).

**Comment by asturio** [comment]
by now there are 70 usages of
```java
.toLowerCase()
```
and  43 usages of 
```
.toLowerCase(Locale.ROOT)
```
in production code.

Is this still relevant?

**Comment by asturio** [comment]
Closing this one.

1. it has a valid point, but
2. is a little bit old
3. if there are any real bugs with this, then people should open a new issue, describing the problem, so it can be explicitly fixed
