### ISSUE TITLE
Header and Footer phrase is no longer being rendered

### ISSUE THREAD

**Issue by vstokesjr** [LibrePDF/OpenPDF#781]
**Describe the bug**
The document _header_ and _footer_ are no longer being rendered in version 1.3.29 when solely set with _Phrase()_. However, if you change the "_numbered_" option to _TRUE_ then the _header_ and _footer_ are rendered but only with the page number. The supplied _Phrase()_ is not being rendered.

**To Reproduce**
Document document = new Document( PageSize.Letter );
PdfWriter.getInstance( document, new FileOutputStream( "/tmp/output.pdf" ) );

/* Set document properties */
document.addAuthor( "Author" );
document.addCreator( this.getClass().getSimpleName() );
document.addCreationDate();
document.addKeywords( "some,key,words" );
document.addSubject( "Subject" );
document.addTitle( "Title" );
document.setDocumentLanguage( "ENG" );

/* Header */
Font headerFont = FontFactory.getFont( FontFactory.COURIER );
headerFont.setSize( 16.0f );
headerFont.setStyle( Font.BOLD );
HeaderFooter header = new HeaderFooter(new Phrase( "This is a header.", headerFont ), false );
header.setAlignment( Element.ALIGN_CENTER );
header.setBorder( Rectangle.NO_BORDER );
document.setHeader( header );

/* Footer */
Font footerFont = FontFactory.getFont( FontFactory.COURIER );
footerFont.setSize( 8.0f );
HeaderFooter footer = new HeaderFooter( new Phrase( "This is a footer.", footerFont ), false ); // does not render anything
// HeaderFooter footer = new HeaderFooter( new Phrase( "This is a footer.", footerFont ), true ); // only page# rendered
footer.setAlignment( Element.ALIGN_CENTER );
footer.setBorder( Rectangle.NO_BORDER );
document.setFooter( footer );

document.open();

/* Body */
Font bodyFont = FontFactory.getFont( FontFactory.COURIER );
bodyFont.setSize( 12.0f );

document.add( new Paragraph( "Hello World", bodyFont ) );
document.add( Chunk.NEXTPAGE );
document.add( new Paragraph("Hello new page.", bodyFont ) );

/* Close */
document.close();

**Expected behavior**
Header and footer _phrase_ should also render.

**Screenshots**

**System (please complete the following information):**
 - OS: Linux Ubuntu 20.04.4 LTS
 - Used Font: COURIER (and also tried HELVETICA)
 - OpenPDF Version: 1.3.29 (via Maven)
 - Java Version: openjdk 17.0.3 2022-04-19 (amd64)
 - IDE: IntelliJ IDEA 2022.1.3 Ultimate

**Additional context**

**Comment by vstokesjr** [comment]
I forgot to mention that if I revert back to OpenPDF Version: 1.3.25 (via Maven) then the header/footer work properly.

**Comment by gnahraf** [comment]
can confirm same behavior on macOS (12.1) with openjdk 17.0.1; also works here w/ version 1.3.28

**Comment by renoth** [comment]
this is most likely due to this commit https://github.com/LibrePDF/OpenPDF/commit/ea9e5c600f8ede086135a933a250b1ecd534d09e
it removes the only content from header and footer

**Comment by renoth** [comment]
Workaround: wrap the Phrase of the Header/Footer in a Paragraph
![image](https://user-images.githubusercontent.com/4069007/189354857-a541019d-794f-454f-bd1a-e267f3d91f02.png)

**Comment by renoth** [comment]
The reason seems to be that this was tested with a Paragraph as header content, when adding a paragraph to the header a newline Chunk is created that needs to be removed afterwards.
This code will not work with a naked Phrase though, although the API does suggest otherwise.
![image](https://user-images.githubusercontent.com/4069007/189355843-dcc9a2a1-9e29-4f53-bcf8-5e9479d5446e.png)

**Comment by asturio** [comment]
Pull requests are welcome.
