### ISSUE TITLE
填充PDF表单，无法加粗字体

### ISSUE THREAD

**Issue by zhangbp** [LibrePDF/OpenPDF#799]
openpdf  version: 1.3.29

`
package com.lowagie.examples.general.copystamp;

import com.lowagie.text.Font;
import com.lowagie.text.pdf.AcroFields;
import com.lowagie.text.pdf.BaseFont;
import com.lowagie.text.pdf.PdfReader;
import com.lowagie.text.pdf.PdfStamper;

import java.io.FileOutputStream;

/**
 * Fill in a simple registration form.
 */
public class Register {
    /**
     * Reads a form and fills in the fields.
     *
     * @param args no arguments needed
     */
    public static void main(String[] args) {
        System.out.println("Filling in a form");
        try {
            // we create a reader for a certain document
            PdfReader reader = new PdfReader("SimpleRegistrationForm.pdf");
            PdfStamper stamp1 = new PdfStamper(reader, new FileOutputStream("registered.pdf"));
            AcroFields form1 = stamp1.getAcroFields();
            //加粗字体
            BaseFont bfChinese = BaseFont.createFont("simsun.ttc,1", BaseFont.IDENTITY_H, BaseFont.EMBEDDED);
            Font font = new Font(bfChinese, 10, Font.BOLD);
            form1.addSubstitutionFont(font.getBaseFont());
            // filling in the form
            form1.setField("name", "中文中文中文中文中文中文中文中文");
            form1.setField("address", "Baeyensstraat 121, Sint-Amandsberg");
            form1.setField("postal_code", "BE-9040");
            form1.setField("email", "bruno@lowagie.com");
            stamp1.setFormFlattening(true);
            stamp1.close();
            // filling in the form and flatten
            reader = new PdfReader("SimpleRegistrationForm.pdf");
            PdfStamper stamp2 = new PdfStamper(reader, new FileOutputStream("registered_flat.pdf"));
            AcroFields form2 = stamp2.getAcroFields();
            form2.setField("name", "Bruno Lowagie");
            form2.setField("address", "Baeyensstraat 121, Sint-Amandsberg");
            form2.setField("postal_code", "BE-9040");
            form2.setField("email", "bruno@lowagie.com");
            stamp2.setFormFlattening(true);
            stamp2.close();
        } catch (Exception de) {
            de.printStackTrace();
        }
    }
}
`

**Comment by Lonzak** [comment]
Your heading translates to: "Fill in PDF form, no bold fonts possible." but my Chinese is a bit rusty. 
Just copying a class file doesn't help. What is the problem? Please describe this and use english.

**Comment by Lonzak** [comment]
Since the original author didn't answer I am voting to close this ticket.
