### ISSUE TITLE
Recent changes to PdfArray broke the Kids field

### ISSUE THREAD

**Issue by vp111** [LibrePDF/OpenPDF#81]
Recent changes in PdfArray.java broke the pdf creation. PdfPages.writePageTree creates empty "Kids" field. Maybe some other code parts affected. Reverting getArrayList (and getElements) to returning internal list fixes the issue.
There is pull request #80 on just the same issue (partially)

**Comment by roschdal** [comment]
#80 has been merged and included in the latest release. Please reopen if you still have this problem.
