### ISSUE TITLE
DocumentException should be unchecked 

### ISSUE THREAD

**Issue by EvgeniySokolov** [LibrePDF/OpenPDF#85]
DocumentException extends Extension that makes it checked exception. 

Basically, it's useless to force to catch it and making it harder to use (e.g. in lambda expressions).

**Comment by andreasrosdal** [comment]
Pull-requests welcome.

**Comment by andreasrosdal** [comment]
Please explain why this API-change is necessary.

**Comment by EvgeniySokolov** [comment]
Let me quote my original comment and add explanations: 

> Basically, it's useless to force to catch it and making it harder to use (e.g. in lambda expressions).
Example: 
  `   * @throws DocumentException
     *             when a document isn't open yet, or has been closed
     */
    public boolean add(Element element) throws DocumentException {
`
What would you do with this? The document is closed or not open, how are you going to react on it? 

Other example: 
`**
     * Constructs a <CODE>Table</CODE> with a certain number of columns.
     *
     * @param       columns         The number of columns in the table
     * @throws      BadElementException if the creator was called with less than 1 column
     */
    public Table(int columns) throws BadElementException {
        this(columns, 1);
    }`
Java already has exception for such cases - IllegalArgumentException and it's unchecked. 

Here is lambda example: 
`IntStream.range(0, 10).mapToObj(Integer::toString).forEach(value -> doc.add(new Phrase(value)));
`
You need to wrap doc.add() into a method and catch exception. 

Generally, it's good practise now not to generate checked exception, if it's not really important. 
In PDF creation I don't see a need to do this.

**Comment by EvgeniySokolov** [comment]
Shouldn't be any issues, since it's unchecked exception, so you can define in method declaration, still try/catch it. 

PR created

**Comment by tlxtellef** [comment]
Binary and compile wise it is compatible but when it comes to runtime control flow it is not. As these methods now throw a different exception as the already existing try/catch blocks are tuned in on an exception with a different signature. However, as you mentioned, what kind of useful response would there be to these exceptions?
