### ISSUE TITLE
SHA-1 is unsafe / deprecated

### ISSUE THREAD

**Issue by andreasrosdal** [LibrePDF/OpenPDF#88]
SHA-1 is unsafe / deprecated.  How should we handle this in OpenPDF?

https://en.wikipedia.org/wiki/SHA-1
https://itextpdf.com/blog/are-pdf-signatures-shattered

https://github.com/LibrePDF/OpenPDF/search?q=sha-1

**Comment by CallousedFinger** [comment]
In itself the deprecation isn't what OpenPDF should be "handling". The user decides which algorithm to use, so unless OpenPDF wants to prevent users using certain algorithms with a blacklist, there's nothing to do during the signing process.

What can be done is adding a DSS to the PDF to overcome this issue. This is done by implementing PAdES, in particular part 4, which deals with long term validation.
