### ISSUE TITLE
setFont method not working on paragraph and phrase.

### ISSUE THREAD

**Issue by devrj8** [LibrePDF/OpenPDF#897]
**Description**
setFont method not working on paragraph and phrase.

**Reproduce**
```
import com.lowagie.text.*;
import com.lowagie.text.pdf.PdfWriter;

import java.io.FileNotFoundException;
import java.io.FileOutputStream;

public class ReproduceBug {

    public static void main(String[] args) throws FileNotFoundException {

        Document document = new Document();
        FileOutputStream pdfOutputFile = new FileOutputStream("./bug.pdf");
        PdfWriter pdfWriter = PdfWriter.getInstance(document, pdfOutputFile);

        document.open();

//bug code
        Paragraph para1 = new Paragraph("Hello World!");
        para1.setFont(new Font(Font.COURIER, 30));
        document.add(para1);

//workaround
        Paragraph para2 = new Paragraph("Hello World!", new Font(Font.COURIER, 30));
        document.add(para2);

        document.close();
    }
}
```

**Expected behavior**
first line "Hello World" should also display with font size 30. but it is not displaying it.

**Screenshots**
Output Screenshot - 
![image](https://user-images.githubusercontent.com/25859158/233200701-a7570413-3b4c-469b-81cc-9c3acdc495bd.png)

**System:**
 - OS: Windows
 - Used Font: Font.COURIER

**Comment by mkl-public** [comment]
The `setFont` method sets the font to use for plain text added to the paragraph _afterwards_.

Thus, instead of
```
        Paragraph para1 = new Paragraph("Hello World!");
        para1.setFont(new Font(Font.COURIER, 30));
```
do
```
        Paragraph para1 = new Paragraph();
        para1.setFont(new Font(Font.COURIER, 30));
        para1.add("Hello World!");
```

**Comment by devrj8** [comment]
Thanks for the explanation. I will try that.
I feel this is a bug cause, it is just a paragraph object and setting font is not working using setter method. 
do you consider this as a bug?

**Comment by asturio** [comment]
I wouldn't consider this a bug.
We could add a check in setFont() if there is already some Elements in the Phrase. Or we just should update the JavaDoc.

**Comment by mkl-public** [comment]
@devrj8 

>I feel this is a bug cause, it is just a paragraph object and setting font is not working using setter method.
do you consider this as a bug?

But _setting font **is** working using setter method._ You merely incorrectly assume the _font_ here is the font used for all the paragraph content. But wouldn't that be a primitive model of a paragraph, having just content of a single font?

I have to admit, though, that the name of the property, _font_, is a bit imprecise and does not convey which font exactly is meant. Thus, a bit of JavaDocs documentation would be great, @asturio.
