### ISSUE TITLE
Is it possible to write a previously read pdf-file ?

### ISSUE THREAD

**Issue by Lolf1010** [LibrePDF/OpenPDF#910]
Hey everyone,
i have a question:

Is it possible to first read a pdf-file and then write it back to another file (maybe modifications in between)?
As far as i can tell i only found tests to create a new pdf via `Document` and then write it OR read a file.

- I can read with the `PdfReader` and write with `PdfWriter` but the `PdfWriter` requires a `Document`-Object which i am not able to get from the reader.
- Then there is `PdfStream`: there i get a NPE when i am using an empty `Document` for the `PdfWriter` even though the constructor also takes an InputStream - is that not the source of the data to stream? also one argument of the stream is a `PdfWriter` and OutputStream but the Methods `writeContent` and `toPdf` also have each an OutputStream and duplicate `PdfWriter`
- If i use `PRStream` instead of `PdfStream` then the resulting pdf-file is empty even though the file is not, looks like its because the length of the `PRStream` is zero when using the InputStream-Constructor and nothing is present in the hashMap in the superCalss `PdfDictionary` ?

Thank you for your help

**Comment by raodienne** [comment]
Hello, you should look into the PdfStamper class
