### ISSUE TITLE
Update to Commons-Imaging 1.0 release

### ISSUE THREAD

**Issue by wltjr** [LibrePDF/OpenPDF#92]
One of the new dependencies is an older version of sanselan/commons-imaging. The imports are sanselan instead of commons.imaging. Basically just need to swap out imports. No other changes are necessary. I am using sed locally to make this change on the fly for [my gentoo ebuilds](https://github.com/Obsidian-StudiosInc/os-xtoo/blob/master/dev-java/openpdf/openpdf-9999.ebuild#L44).

This repo [commons-imaging](https://github.com/apache/commons-imaging)

Not this [old sanselan](https://github.com/apache/sanselan) repo

I believe the problem lies in maven central not having anything for [commons-imaging](https://search.maven.org/classic/#search%7Cga%7C4%7Cg%3A%22org.apache.commons%22).  It only has a one for the [old sanselan](https://search.maven.org/classic/#search%7Cga%7C1%7Csanselan). This is the only [commons-imaging](https://search.maven.org/classic/#search%7Cga%7C1%7Ca%3A%22commons-imaging%22) on maven central and is not apache commons imaging. Likely need to file a bug with Apache to request pushing updated commons-imaging to maven central. Or update pom.xml to use apache commons-imaging directly from a repository. Then update imports to reflect the change in package names.

**Comment by andreasrosdal** [comment]
Yes, OpenPDF needs to update to a better Commons-Imaging release.
I have been asking on the Commons mailing lists for a proper release, and they seem to be
interested in creating a 1.0 release of Commons-Imaging soon:
http://mail-archives.apache.org/mod_mbox/commons-dev/201808.mbox/browser
So the future looks bright!

**Comment by wltjr** [comment]
Good news! Glad to hear you have already been working on it. I think 5 years of a RC is long enough, 1.0 release is overdue. Thanks for staying on top of it!

**Comment by andreasrosdal** [comment]
https://github.com/LibrePDF/OpenPDF/commit/3a19475c914e3a12c2ba7b954fcd7f5068cbfaf6
