### ISSUE TITLE
Empty line added to document when adding tabulator

### ISSUE THREAD

**Issue by jansorby** [LibrePDF/OpenPDF#927]
Adding a TAB at the rightmost position of the page as the last element of Paragraph causes an empty line to be added.

The following code is part of the Unit-test to provoke the error.

```
        Document document = new Document(PageSize.A4, 36, 72, 108, 180);

            paragraph = new Paragraph();
            paragraph.add("Leftmost column");
            Chunk newTab = new Chunk(new VerticalPositionMark(), 200);
            paragraph.add(newTab);
            paragraph.add("Center column");
            newTab = new Chunk(new VerticalPositionMark(), 360);
            paragraph.add(newTab);
            paragraph.add("Right column12345678");
            newTab = new Chunk(new VerticalPositionMark(), 400); // This triggers the error
            paragraph.add(newTab);
            document.add(paragraph);

            paragraph = new Paragraph();
            paragraph.add("Leftmost column");
            newTab = new Chunk(new VerticalPositionMark(), 200);
            paragraph.add(newTab);
            paragraph.add("Center column");
            newTab = new Chunk(new VerticalPositionMark(), 360);
            paragraph.add(newTab);
            paragraph.add("Right column12345678");
            document.add(paragraph);
```

I expected the next line to start immediately below the first line.

This is how it looks
![image](https://github.com/LibrePDF/OpenPDF/assets/6337159/c1a10a21-7560-4f88-ac14-a445c3d8d3a5)

This is how it should be
![image](https://github.com/LibrePDF/OpenPDF/assets/6337159/7d6ddff0-110a-4eeb-97f6-e58a3b8e46d7)

 - OS: Windows 10
 - Used Font: Default font

My suggestion is to fix this in PdfDocument.add(Element) by adding three lines.

                case Element.CHUNK: {
                    // if there isn't a current line available, we make one
                    if (line == null) {
                        carriageReturn();
                    }

                    // we cast the element to a chunk
                    PdfChunk chunk = new PdfChunk((Chunk) element, anchorAction);
                    // we try to add the chunk to the line, until we succeed
                    if (!chunk.isTab()) // <--- Add this line
                    {
                        PdfChunk overflow;
                        while ((overflow = line.add(chunk)) != null) {
                            carriageReturn();
                            chunk = overflow;
                            chunk.trimFirstSpace();
                        }
                    }
                    else // <--- Add this line
                        line.add(chunk); // <--- Add this line
                    pageEmpty = false;
                    if (chunk.isAttribute(Chunk.NEWPAGE)) {
                        newPage();
                    }
                    break;
                }

**Comment by asturio** [comment]
Is this issue still open? Or did the merge #794 fixed it?
