### ISSUE TITLE
Nested tables

### ISSUE THREAD

**Issue by bberto** [LibrePDF/OpenPDF#93]
Hello,

I've two issues with nested tables:
1. above third level of nesting, the border of enclosing cell disappears;
2. adding two nested tables to a cell, the second one has wrong size.

I attach a code snippet and current result. Code version 1.2.0.
```
  protected void buildPdfDocument(
      Map<String, Object> model,
      Document document,
      PdfWriter writer,
      HttpServletRequest request,
      HttpServletResponse response)
      throws Exception {

    Table subsubtable = newTable();
    subsubtable.addCell("key1");
    subsubtable.addCell("value1");
    subsubtable.addCell("key2");
    subsubtable.addCell("value2");
    
    Table subtable = newTable();
    subtable.addCell("key1");
    subtable.addCell("value1");
    subtable.addCell("key2");
    subtable.addCell(new Cell(subsubtable));
    
    Table table = newTable();
    table.addCell("key1");
    table.addCell("value1");
    table.addCell("key2");
    Cell cell = new Cell();
    cell.addElement(new Chunk("Element 1"));
    cell.addElement(subtable);
    cell.addElement(new Chunk("Element 2"));
    cell.addElement(subtable);
    table.addCell(cell);
    
    document.add(table);
  }

  protected Table newTable() {
    Table table = new Table(2);
    table.setWidth(95f);
    table.setPadding(2f);
    table.setWidths(new int[] {20, 80});
    return table;
  }
```
![image](https://user-images.githubusercontent.com/3389771/44020434-31bafcf6-9ee2-11e8-987d-e8c253f4a3ef.png)

**Comment by andreasrosdal** [comment]
Thanks for the bugreport. Pull-requests to fix this is welcome.

**Comment by andreasrosdal** [comment]
Do you know if this has worked correctly in a previous version? For example, OpenPDF 1.0.5, iText 1.2.7, or iText 4.2.0?

**Comment by bberto** [comment]
Tested with all suggested version, with no luck.  I think you meant iText 2.1.7, right?

**Comment by CallousedFinger** [comment]
Use PdfPTable and PdfPCell.

**Comment by andreasrosdal** [comment]
@bberto Did this solve your problem?

**Comment by andreasrosdal** [comment]
@bberto Please let us know if the proposed solution works. 

Then please reopen this bugreport.

**Comment by bberto** [comment]
It works! Thanks!
