### ISSUE TITLE
Further enhancements in OpenPDF

### ISSUE THREAD

**Issue by GitHubHans1** [LibrePDF/OpenPDF#945]
Hallo,

I have a specific and a general question regarding the enhancements in OpenPDF:

Specific:
Is there any plans in OpenPDF to support further PDF/A standards?
For example PDF/A-2, PDF/A-3a, PDF/A-3b or PDF/A-4?

General:
What is the current strategy regarding further enhancements in OpenPDF?
Is there a general plan to offer new standards in order to be a state-of-the-art library?

Best regards

**Comment by andreasrosdal** [comment]
Please submit pull requests in order to add these further enhancements to OpenPDF.
