### ISSUE TITLE
1.3.31-SNAPSHOT missing

### ISSUE THREAD

**Issue by NeilAgg2001** [LibrePDF/OpenPDF#956]
I got a new computer and am trying to set up my eclipse project.

When I go to compile it, I am getting this Maven error:
The following artifacts could not be resolved: com.github.librepdf:openpdf:jar:1.3.31-SNAPSHOT (absent): Could not find artifact com.github.librepdf:openpdf:jar:1.3.31-SNAPSHOT

Has this been removed?

**Comment by andreasrosdal** [comment]
Please try using this in your Maven pom.xml file:

<dependency>
  <groupId>com.github.librepdf</groupId>
  <artifactId>openpdf</artifactId>
  <version>1.3.31</version>
</dependency>
