### ISSUE TITLE
can i use this library for commercial? (lib included in my project)

### ISSUE THREAD

**Issue by erlangp** [LibrePDF/OpenPDF#96]

**Comment by andreasrosdal** [comment]
Yes! You can use OpenPDF as long as you comply with the LGPL and/or MPL licenses.

This is some background information about the licenses:
https://www.gnu.org/licenses/lgpl-3.0.en.html
https://www.mozilla.org/en-US/MPL/
https://github.com/LibrePDF/OpenPDF/blob/master/License.md
https://github.com/LibrePDF/OpenPDF/wiki/OpenPDF---License-MPL---LGPL-background-info

**Comment by erlangp** [comment]
thanks @andreasrosdal

**Comment by Lonzak** [comment]
It is the same license as the old *Text version 2.1.7. And I think that's why people do this whole project here...
