### ISSUE TITLE
OpenPdf license.

### ISSUE THREAD

**Issue by MPerez2021** [LibrePDF/OpenPDF#964]
I would like to use this library to generate medical reports in PDF format within a module of my web system, which is intended for online commercial use. I would appreciate confirmation on whether I can use this library without legal issues and without the obligation to share the source code.

**Comment by markolo25** [comment]
As long as you don't distribute your compiled application and only distribute the medical reports in PDF format you should be good.

**Comment by MPerez2021** [comment]
I understand, so I won't have any issues if I have my web system online with a module for generating PDFs using this library, am I correct?

**Comment by markolo25** [comment]
you should be good, as long as you don't distribute the binaries that generate the pdf.

**Comment by mikebgrep** [comment]
Hi, I am opening the issue with another question, can I use the library to another open source repository with Apache 2 license or I need to have the same license as the  OpenPDF.
