### ISSUE TITLE
Please make those has close() method class or interface implements AutoCloseable

### ISSUE THREAD

**Issue by kentyeh** [LibrePDF/OpenPDF#965]
I found an interface and some classes blow could implement/extends AutoCloseable.
those are

 com.lowagie.text.DocListener
 
 com.lowagie.text.pdf.MappedRandomAccessFile
 com.lowagie.text.pdf.PRTokeniser
 com.lowagie.text.pdf.PdfCopyFields
 com.lowagie.text.pdf.PdfCopyForms
 com.lowagie.text.pdf.PdfStamper
 com.lowagie.text.xml.xmp.XmpWriter

Please make those classes into try-with-resources.
Thanks.

**Comment by lokytech5** [comment]
hello, hacktoberfest here. Can you direct me to the location of the classes in the project? and the interface you found, is it from the Java package or a library we need to use?

**Comment by kentyeh** [comment]
I  have a requirement to using PdfStamper, but it is annoying to have to have a finally section to close it.

I found those class in [https://javadoc.io/doc/com.github.librepdf/openpdf/latest/index.html](https://javadoc.io/doc/com.github.librepdf/openpdf/latest/index.html) by filter close method to check whether exists AutoCloseable interface.

Would you to change those class  classes into try-with-resources.

**Comment by lokytech5** [comment]
Before proceeding, I want to verify whether the classes you've mentioned already possess a close() method or a similar resource-releasing mechanism. If they do, then making them implement the AutoCloseable interface would be straightforward. Here's a simple example 

public class PdfStamper implements AutoCloseable {
    @Override
    public void close() throws Exception {
   //logic here
}

}

Is this along the lines of what you were envisioning? If you'd like, I can take on this task. could you directly point me to the specific locations of the classes in question? thanks

**Comment by kentyeh** [comment]
Yes, just make those classes have a close() method implements AutoCloseable, even don't change close method signature.

for example,

```java
public class PdfStamper implements AutoCloseable {
  @Override
  public void close() throws DocumentException, IOException {
     //logic 
  }
}
```

[com.lowagie.text.DocListener](https://github.com/LibrePDF/OpenPDF/blob/master/openpdf/src/main/java/com/lowagie/text/DocListener.java#L79)

[com.lowagie.text.pdf.MappedRandomAccessFile](https://github.com/LibrePDF/OpenPDF/blob/master/openpdf/src/main/java/com/lowagie/text/pdf/MappedRandomAccessFile.java#L184)
[com.lowagie.text.pdf.PRTokeniser](https://github.com/LibrePDF/OpenPDF/blob/master/openpdf/src/main/java/com/lowagie/text/pdf/PRTokeniser.java#L130)
[com.lowagie.text.pdf.PdfCopyFields](https://github.com/LibrePDF/OpenPDF/blob/master/openpdf/src/main/java/com/lowagie/text/pdf/PdfCopyFields.java#L161)
[com.lowagie.text.pdf.PdfCopyForms](https://github.com/LibrePDF/OpenPDF/blob/master/openpdf/src/main/java/com/lowagie/text/pdf/PdfCopyFields.java#L161)
[com.lowagie.text.pdf.PdfStamper](https://github.com/LibrePDF/OpenPDF/blob/master/openpdf/src/main/java/com/lowagie/text/pdf/PdfStamper.java#L234)
[com.lowagie.text.xml.xmp.XmpWriter](https://github.com/LibrePDF/OpenPDF/blob/master/openpdf/src/main/java/com/lowagie/text/xml/xmp/XmpWriter.java#L297)

Thxs

**Comment by NicolaIsotta** [comment]
There's already PR #831

**Comment by lokytech5** [comment]
Thank you for pointing out PR #831. I took a moment to review it. It seems that SirLefti has already made changes to implement the AutoCloseable interface on the classes you mentioned. The PR has passed the SonarCloud Quality Gate with no reported issues.
However, there are a few things to note:
* 		The PR has been open for a while and has not been merged yet.
* 		@peterjohansen has previously requested for it to be merged.
* 		The PR is addressing a related issue, #812, which is still open.
* 		Another PR, #965, mentions the AutoCloseable implementation and might be related.
Please ensure that the changes in PR #831 cover all the classes you mentioned. If PR #831 does not get merged soon or if there are other classes you'd like to see updated, I'd be more than happy to assist. Please let me know how you'd like to proceed.

**Comment by SirLefti** [comment]
Issue can be closed, solved in PR https://github.com/LibrePDF/OpenPDF/pull/831.

**Comment by kentyeh** [comment]
PR [#831](https://github.com/LibrePDF/OpenPDF/pull/831) merged.
