### ISSUE TITLE
Upload Release 1.3.31 to Maven Central

### ISSUE THREAD

**Issue by zimmi** [LibrePDF/OpenPDF#974]
This is a follow-up to https://github.com/LibrePDF/OpenPDF/issues/961.

Release 1.3.31 should be [here](https://repo1.maven.org/maven2/com/github/librepdf/openpdf/), but it isn't.
@asturio if I understand correctly, the search index on Maven Central can lag behind, but if it's not in the linked structure, the upload failed somehow. Would you mind looking into this?

**Comment by andreasrosdal** [comment]
Fixed. I will release 1.3.32 today.

**Comment by asturio** [comment]
Maven Central can have a very long delay. Up to 2 days. 1.3.31 is there now.

**Comment by zimmi** [comment]
Thank you for the quick iteration time @asturio !

> Maven Central can have a very long delay. Up to 2 days. 1.3.31 is there now.

Yikes, good to know. Sorry for the noise then!
