### ISSUE TITLE
Run script build phase 'Run Script' will be run during every build because it does not specify any outputs.

### ISSUE THREAD

**Issue by Johnhong9527** [LibrePDF/OpenPDF#991]
![image](https://github.com/LibrePDF/OpenPDF/assets/20456201/d967536a-8ac2-4751-8c00-217183f16626)

If `Run script build phase 'Run Script' will be run during every build because it does not specify any outputs.` appears when compiling ios, an error will be reported. You can give a setting at will

如果在编译ios时出现`Run script build phase 'Run Script' will be run during every build because it does not specify any outputs.`报错。可以随意给出一个设置

**Comment by andreasrosdal** [comment]
Pull requests welcome.
